// <copyright file="UsedInAddendums.BrandAdmin.cs" company="clarity-ventures.com">
// Copyright (c) 2020-2023 clarity-ventures.com. All rights reserved.
// </copyright>
// <summary>Implements the used in addendums classes</summary>
// ReSharper disable MissingXmlDoc
#pragma warning disable SA1134 // Attributes should not share line
#pragma warning disable SA1502 // Element should not be on a single line
#pragma warning disable SA1516 // Elements should be separated by blank line
namespace Clarity.Ecommerce.Service
{
    [UsedInBrandAdmin] public partial class AdminGetAuctionsForPortal { }
    [UsedInBrandAdmin] public partial class AdminGetLotsForPortal { }
    [UsedInBrandAdmin] public partial class AdminGetProductsForPortal { }
    [UsedInBrandAdmin] public partial class AdminGetPurchaseOrdersForPortal { }
    [UsedInBrandAdmin] public partial class AdminGetSalesInvoicesForPortal { }
    [UsedInBrandAdmin] public partial class AdminGetSalesOrdersForPortal { }
    [UsedInBrandAdmin] public partial class AdminGetSalesQuotesForPortal { }
    [UsedInBrandAdmin] public partial class AdminGetSalesReturnsForPortal { }
    [UsedInBrandAdmin] public partial class CreateAuction { }
    [UsedInBrandAdmin] public partial class CreateBrandAuction { }
    [UsedInBrandAdmin] public partial class CreateBrandProduct { }
    [UsedInBrandAdmin] public partial class CreateCategory { }
    [UsedInBrandAdmin] public partial class CreateFranchiseProduct { }
    [UsedInBrandAdmin] public partial class CreateFranchiseUser { }
    [UsedInBrandAdmin] public partial class CreateInventoryLocations { }
    [UsedInBrandAdmin] public partial class CreateLot { }
    [UsedInBrandAdmin] public partial class CreateManufacturerProduct { }
    [UsedInBrandAdmin] public partial class CreateProduct { }
    [UsedInBrandAdmin] public partial class CreateProductAssociation { }
    [UsedInBrandAdmin] public partial class CreateProductImage { }
    [UsedInBrandAdmin] public partial class CreateStoreProduct { }
    [UsedInBrandAdmin] public partial class CreateStoreUser { }
    [UsedInBrandAdmin] public partial class CreateUserImage { }
    [UsedInBrandAdmin] public partial class CreateVendorProduct { }
    [UsedInBrandAdmin] public partial class DeactivateBrandProductByID { }
    [UsedInBrandAdmin] public partial class DeactivateFranchiseProductByID { }
    [UsedInBrandAdmin] public partial class DeactivateFranchiseUserByID { }
    [UsedInBrandAdmin] public partial class DeactivateManufacturerProductByID { }
    [UsedInBrandAdmin] public partial class DeactivateProductAssociationByID { }
    [UsedInBrandAdmin] public partial class DeactivateStoreProductByID { }
    [UsedInBrandAdmin] public partial class DeactivateStoreUserByID { }
    [UsedInBrandAdmin] public partial class DeactivateVendorProductByID { }
    [UsedInBrandAdmin] public partial class GetAccounts { }
    [UsedInBrandAdmin] public partial class GetAttributeTypes { }
    [UsedInBrandAdmin] public partial class GetAuctionByID { }
    [UsedInBrandAdmin] public partial class GetAuctions { }
    [UsedInBrandAdmin] public partial class GetAuctionStatuses { }
    [UsedInBrandAdmin] public partial class GetAuctionTypes { }
    [UsedInBrandAdmin] public partial class GetBrandAuctions { }
    [UsedInBrandAdmin] public partial class GetBrandProducts { }
    [UsedInBrandAdmin] public partial class GetBrands { }
    [UsedInBrandAdmin] public partial class GetBrandUsers { }
    [UsedInBrandAdmin] public partial class GetCategories { }
    [UsedInBrandAdmin] public partial class GetCategoryByID { }
    [UsedInBrandAdmin] public partial class GetCategoryTree { }
    [UsedInBrandAdmin] public partial class GetContactByID { }
    [UsedInBrandAdmin] public partial class GetCountries { }
    [UsedInBrandAdmin] public partial class GetCurrencies { }
    [UsedInBrandAdmin] public partial class GetCurrentAccountAddressBook { }
    [UsedInBrandAdmin] public partial class GetCurrentBrandAdministration { }
    [UsedInBrandAdmin] public partial class GetCurrentUser { }
    [UsedInBrandAdmin] public partial class GetFranchiseAuctions { }
    [UsedInBrandAdmin] public partial class GetFranchiseProducts { }
    [UsedInBrandAdmin] public partial class GetFranchises { }
    [UsedInBrandAdmin] public partial class GetFranchiseUsers { }
    [UsedInBrandAdmin] public partial class GetGeneralAttributes { }
    [UsedInBrandAdmin] public partial class GetInventoryLocations { }
    [UsedInBrandAdmin] public partial class GetLanguages { }
    [UsedInBrandAdmin] public partial class GetLotByID { }
    [UsedInBrandAdmin] public partial class GetLots { }
    [UsedInBrandAdmin] public partial class GetLotStatuses { }
    [UsedInBrandAdmin] public partial class GetLotTypes { }
    [UsedInBrandAdmin] public partial class GetManufacturerProducts { }
    [UsedInBrandAdmin] public partial class GetManufacturers { }
    [UsedInBrandAdmin] public partial class GetPackages { }
    [UsedInBrandAdmin] public partial class GetProductAssociations { }
    [UsedInBrandAdmin] public partial class GetProductAssociationTypes { }
    [UsedInBrandAdmin] public partial class GetProductByID { }
    [UsedInBrandAdmin] public partial class GetProducts { }
    [UsedInBrandAdmin] public partial class GetProductStatuses { }
    [UsedInBrandAdmin] public partial class GetProductTypes { }
    [UsedInBrandAdmin] public partial class GetPurchaseOrderByID { }
    [UsedInBrandAdmin] public partial class GetPurchaseOrderStatuses { }
    [UsedInBrandAdmin] public partial class GetPurchaseOrderTypes { }
    [UsedInBrandAdmin] public partial class GetRegions { }
    [UsedInBrandAdmin] public partial class GetSalesInvoiceStatuses { }
    [UsedInBrandAdmin] public partial class GetSalesOrderStatuses { }
    [UsedInBrandAdmin] public partial class GetStoreAuctions { }
    [UsedInBrandAdmin] public partial class GetStoreByID { }
    [UsedInBrandAdmin] public partial class GetStoreProducts { }
    [UsedInBrandAdmin] public partial class GetStores { }
    [UsedInBrandAdmin] public partial class GetStoreTypes { }
    [UsedInBrandAdmin] public partial class GetStoreUsers { }
    [UsedInBrandAdmin] public partial class GetUserByID { }
    [UsedInBrandAdmin] public partial class GetUsers { }
    [UsedInBrandAdmin] public partial class GetUserStatuses { }
    [UsedInBrandAdmin] public partial class GetUserTypes { }
    [UsedInBrandAdmin] public partial class GetVendorProducts { }
    [UsedInBrandAdmin] public partial class GetVendors { }
    [UsedInBrandAdmin] public partial class UpdateAuction { }
    [UsedInBrandAdmin] public partial class UpdateBrand { }
    [UsedInBrandAdmin] public partial class UpdateBrandAuction { }
    [UsedInBrandAdmin] public partial class UpdateCategory { }
    [UsedInBrandAdmin] public partial class UpdateFranchiseProduct { }
    [UsedInBrandAdmin] public partial class UpdateFranchiseUser { }
    [UsedInBrandAdmin] public partial class UpdateLot { }
    [UsedInBrandAdmin] public partial class UpdateManufacturerProduct { }
    [UsedInBrandAdmin] public partial class UpdateProduct { }
    [UsedInBrandAdmin] public partial class UpdateProductAssociation { }
    [UsedInBrandAdmin] public partial class UpdatePurchaseOrder { }
    [UsedInBrandAdmin] public partial class UpdateStore { }
    [UsedInBrandAdmin] public partial class UpdateStoreProduct { }
    [UsedInBrandAdmin] public partial class UpdateStoreUser { }
    [UsedInBrandAdmin] public partial class UpdateUser { }
    [UsedInBrandAdmin] public partial class UpdateVendorProduct { }
    [UsedInBrandAdmin] public partial class UpsertBrandAuction { }
    [UsedInBrandAdmin] public partial class UpsertInventoryLocation { }
}
