// <copyright file="201801221557427_JsonAttributesEverywhere.cs" company="clarity-ventures.com">
// Copyright (c) 2019-2023 clarity-ventures.com. All rights reserved.
// </copyright>
// <summary>Implements the 201801221557427 JSON attributes everywhere class</summary>
namespace Clarity.Ecommerce.DataModel.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class JsonAttributesEverywhere : DbMigration
    {
        public override void Up()
        {
            DropIndex("Vendors.Vendor", new[] { "VendorHash" });
            AddColumn("Accounts.AccountAttribute", "JsonAttributes", c => c.String());
            AddColumn("Attributes.AttributeValue", "JsonAttributes", c => c.String());
            AddColumn("Attributes.GeneralAttribute", "JsonAttributes", c => c.String());
            AddColumn("Attributes.AttributeType", "JsonAttributes", c => c.String());
            AddColumn("Accounts.AccountContact", "JsonAttributes", c => c.String());
            AddColumn("Contacts.Contact", "JsonAttributes", c => c.String());
            AddColumn("Geography.Address", "JsonAttributes", c => c.String());
            AddColumn("Geography.Country", "JsonAttributes", c => c.String());
            AddColumn("Geography.CountryCurrency", "JsonAttributes", c => c.String());
            AddColumn("Currencies.Currency", "JsonAttributes", c => c.String());
            AddColumn("Currencies.HistoricalCurrencyRate", "JsonAttributes", c => c.String());
            AddColumn("Currencies.CurrencyImage", "JsonAttributes", c => c.String());
            AddColumn("Currencies.CurrencyImageType", "JsonAttributes", c => c.String());
            AddColumn("Media.Library", "JsonAttributes", c => c.String());
            AddColumn("Media.Audio", "JsonAttributes", c => c.String());
            AddColumn("Media.File", "JsonAttributes", c => c.String());
            AddColumn("Media.FileData", "JsonAttributes", c => c.String());
            AddColumn("Media.Image", "JsonAttributes", c => c.String());
            AddColumn("Media.Document", "JsonAttributes", c => c.String());
            AddColumn("Media.LibraryType", "JsonAttributes", c => c.String());
            AddColumn("Media.Video", "JsonAttributes", c => c.String());
            AddColumn("Geography.CountryImage", "JsonAttributes", c => c.String());
            AddColumn("Geography.CountryImageType", "JsonAttributes", c => c.String());
            AddColumn("Geography.CountryLanguage", "JsonAttributes", c => c.String());
            AddColumn("Globalization.Language", "JsonAttributes", c => c.String());
            AddColumn("Globalization.LanguageImage", "JsonAttributes", c => c.String());
            AddColumn("Globalization.LanguageImageType", "JsonAttributes", c => c.String());
            AddColumn("Geography.Region", "JsonAttributes", c => c.String());
            AddColumn("Geography.RegionCurrency", "JsonAttributes", c => c.String());
            AddColumn("Geography.District", "JsonAttributes", c => c.String());
            AddColumn("Geography.DistrictCurrency", "JsonAttributes", c => c.String());
            AddColumn("Geography.DistrictImage", "JsonAttributes", c => c.String());
            AddColumn("Geography.DistrictImageType", "JsonAttributes", c => c.String());
            AddColumn("Geography.DistrictLanguage", "JsonAttributes", c => c.String());
            AddColumn("Tax.TaxDistrict", "JsonAttributes", c => c.String());
            AddColumn("Geography.RegionImage", "JsonAttributes", c => c.String());
            AddColumn("Geography.RegionImageType", "JsonAttributes", c => c.String());
            AddColumn("Geography.InterRegion", "JsonAttributes", c => c.String());
            AddColumn("Geography.RegionLanguage", "JsonAttributes", c => c.String());
            AddColumn("Tax.TaxRegion", "JsonAttributes", c => c.String());
            AddColumn("Tax.TaxCountry", "JsonAttributes", c => c.String());
            AddColumn("Purchasing.SalesOrderPurchaseOrder", "JsonAttributes", c => c.String());
            AddColumn("Invoicing.SalesOrderSalesInvoice", "JsonAttributes", c => c.String());
            AddColumn("Invoicing.SalesInvoiceAttribute", "JsonAttributes", c => c.String());
            AddColumn("Discounts.SalesInvoiceDiscounts", "JsonAttributes", c => c.String());
            AddColumn("Discounts.Discount", "JsonAttributes", c => c.String());
            AddColumn("Discounts.DiscountCategories", "JsonAttributes", c => c.String());
            AddColumn("Categories.CategoryAttribute", "JsonAttributes", c => c.String());
            AddColumn("Categories.CategoryImage", "JsonAttributes", c => c.String());
            AddColumn("Categories.CategoryFile", "JsonAttributes", c => c.String());
            AddColumn("Categories.CategoryImageNew", "JsonAttributes", c => c.String());
            AddColumn("Categories.CategoryImageType", "JsonAttributes", c => c.String());
            AddColumn("Products.ProductCategoryAttribute", "JsonAttributes", c => c.String());
            AddColumn("Products.ProductAttribute", "JsonAttributes", c => c.String());
            AddColumn("Shopping.CartItemAttribute", "JsonAttributes", c => c.String());
            AddColumn("Discounts.CartItemDiscounts", "JsonAttributes", c => c.String());
            AddColumn("Shopping.CartAttribute", "JsonAttributes", c => c.String());
            AddColumn("Discounts.CartDiscounts", "JsonAttributes", c => c.String());
            AddColumn("Shopping.CartFile", "JsonAttributes", c => c.String());
            AddColumn("System.Note", "JsonAttributes", c => c.String());
            AddColumn("Contacts.UserAttribute", "JsonAttributes", c => c.String());
            AddColumn("Messaging.ConversationUser", "JsonAttributes", c => c.String());
            AddColumn("Messaging.Conversation", "JsonAttributes", c => c.String());
            AddColumn("Messaging.Message", "JsonAttributes", c => c.String());
            AddColumn("Messaging.MessageAttachment", "JsonAttributes", c => c.String());
            AddColumn("Media.StoredFile", "JsonAttributes", c => c.String());
            AddColumn("Messaging.MessageRecipient", "JsonAttributes", c => c.String());
            AddColumn("Messaging.EmailQueue", "JsonAttributes", c => c.String());
            AddColumn("Messaging.EmailTemplate", "JsonAttributes", c => c.String());
            AddColumn("Messaging.EmailStatus", "JsonAttributes", c => c.String());
            AddColumn("Messaging.EmailType", "JsonAttributes", c => c.String());
            AddColumn("Groups.GroupUser", "JsonAttributes", c => c.String());
            AddColumn("Groups.GroupStatus", "JsonAttributes", c => c.String());
            AddColumn("Groups.GroupType", "JsonAttributes", c => c.String());
            AddColumn("Stores.BrandStore", "JsonAttributes", c => c.String());
            AddColumn("Stores.Brand", "JsonAttributes", c => c.String());
            AddColumn("Stores.BrandSiteDomain", "JsonAttributes", c => c.String());
            AddColumn("Stores.SiteDomainSocialProvider", "JsonAttributes", c => c.String());
            AddColumn("Stores.SocialProvider", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreSiteDomain", "JsonAttributes", c => c.String());
            AddColumn("Stores.BrandImage", "JsonAttributes", c => c.String());
            AddColumn("Stores.BrandImageType", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreImageNew", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreImageType", "JsonAttributes", c => c.String());
            AddColumn("Reviews.Review", "JsonAttributes", c => c.String());
            AddColumn("Manufacturers.Manufacturer", "JsonAttributes", c => c.String());
            AddColumn("Manufacturers.ManufacturerImage", "JsonAttributes", c => c.String());
            AddColumn("Manufacturers.ManufacturerImageType", "JsonAttributes", c => c.String());
            AddColumn("Manufacturers.ManufacturerProduct", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreManufacturer", "JsonAttributes", c => c.String());
            AddColumn("Vendors.VendorManufacturer", "JsonAttributes", c => c.String());
            AddColumn("Vendors.Vendor", "JsonAttributes", c => c.String());
            AddColumn("Contacts.ContactMethod", "JsonAttributes", c => c.String());
            AddColumn("Vendors.VendorImage", "JsonAttributes", c => c.String());
            AddColumn("Vendors.VendorImageType", "JsonAttributes", c => c.String());
            AddColumn("Shipping.Shipment", "JsonAttributes", c => c.String());
            AddColumn("Inventory.InventoryLocationSection", "JsonAttributes", c => c.String());
            AddColumn("Inventory.InventoryLocation", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreInventoryLocation", "JsonAttributes", c => c.String());
            AddColumn("Products.ProductInventoryLocationSection", "JsonAttributes", c => c.String());
            AddColumn("Ordering.SalesOrderItemAttribute", "JsonAttributes", c => c.String());
            AddColumn("Discounts.SalesOrderItemDiscounts", "JsonAttributes", c => c.String());
            AddColumn("Ordering.SalesOrderItemStatus", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreProduct", "JsonAttributes", c => c.String());
            AddColumn("Vendors.VendorProduct", "JsonAttributes", c => c.String());
            AddColumn("Shipping.ShipCarrier", "JsonAttributes", c => c.String());
            AddColumn("Shipping.CarrierInvoice", "JsonAttributes", c => c.String());
            AddColumn("Shipping.CarrierOrigin", "JsonAttributes", c => c.String());
            AddColumn("Shipping.ShipCarrierMethod", "JsonAttributes", c => c.String());
            AddColumn("Vendors.ShipVia", "JsonAttributes", c => c.String());
            AddColumn("Shipping.ShipmentEvent", "JsonAttributes", c => c.String());
            AddColumn("Shipping.ShipmentStatus", "JsonAttributes", c => c.String());
            AddColumn("Shipping.ShipmentType", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreVendor", "JsonAttributes", c => c.String());
            AddColumn("Vendors.Term", "JsonAttributes", c => c.String());
            AddColumn("Vendors.VendorTerm", "JsonAttributes", c => c.String());
            AddColumn("Reviews.ReviewType", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreAccount", "JsonAttributes", c => c.String());
            AddColumn("Pricing.PricePoint", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreBadge", "JsonAttributes", c => c.String());
            AddColumn("Stores.Badge", "JsonAttributes", c => c.String());
            AddColumn("Stores.BadgeImage", "JsonAttributes", c => c.String());
            AddColumn("Stores.BadgeImageType", "JsonAttributes", c => c.String());
            AddColumn("Stores.BadgeType", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreCategory", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreCategoryType", "JsonAttributes", c => c.String());
            AddColumn("Categories.CategoryType", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreContact", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreImage", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreSubscription", "JsonAttributes", c => c.String());
            AddColumn("Payments.Subscription", "JsonAttributes", c => c.String());
            AddColumn("Payments.RepeatType", "JsonAttributes", c => c.String());
            AddColumn("Payments.SubscriptionHistory", "JsonAttributes", c => c.String());
            AddColumn("Payments.Payment", "JsonAttributes", c => c.String());
            AddColumn("Payments.PaymentMethod", "JsonAttributes", c => c.String());
            AddColumn("Payments.PaymentStatus", "JsonAttributes", c => c.String());
            AddColumn("Payments.PaymentType", "JsonAttributes", c => c.String());
            AddColumn("Payments.SubscriptionStatus", "JsonAttributes", c => c.String());
            AddColumn("Products.ProductSubscriptionType", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreUser", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreUserType", "JsonAttributes", c => c.String());
            AddColumn("Contacts.UserType", "JsonAttributes", c => c.String());
            AddColumn("Stores.StoreType", "JsonAttributes", c => c.String());
            AddColumn("Favorites.FavoriteCategory", "JsonAttributes", c => c.String());
            AddColumn("Favorites.FavoriteManufacturer", "JsonAttributes", c => c.String());
            AddColumn("Favorites.FavoriteStore", "JsonAttributes", c => c.String());
            AddColumn("Favorites.FavoriteVendor", "JsonAttributes", c => c.String());
            AddColumn("Contacts.UserImage", "JsonAttributes", c => c.String());
            AddColumn("Contacts.UserImageType", "JsonAttributes", c => c.String());
            AddColumn("Contacts.ReferralCodeStatus", "JsonAttributes", c => c.String());
            AddColumn("Contacts.ReferralCodeType", "JsonAttributes", c => c.String());
            AddColumn("Contacts.RoleUser", "JsonAttributes", c => c.String());
            AddColumn("Quoting.SalesQuoteSalesOrder", "JsonAttributes", c => c.String());
            AddColumn("Quoting.SalesQuoteAttribute", "JsonAttributes", c => c.String());
            AddColumn("Discounts.SalesQuoteDiscounts", "JsonAttributes", c => c.String());
            AddColumn("Quoting.SalesQuoteFile", "JsonAttributes", c => c.String());
            AddColumn("Quoting.SalesQuoteItemAttribute", "JsonAttributes", c => c.String());
            AddColumn("Discounts.SalesQuoteItemDiscounts", "JsonAttributes", c => c.String());
            AddColumn("Quoting.SalesQuoteItemStatus", "JsonAttributes", c => c.String());
            AddColumn("Quoting.SalesQuoteCategory", "JsonAttributes", c => c.String());
            AddColumn("Shipping.ShipOption", "JsonAttributes", c => c.String());
            AddColumn("Quoting.SalesQuoteState", "JsonAttributes", c => c.String());
            AddColumn("Quoting.SalesQuoteStatus", "JsonAttributes", c => c.String());
            AddColumn("Quoting.SalesQuoteFileNew", "JsonAttributes", c => c.String());
            AddColumn("Quoting.SalesQuoteType", "JsonAttributes", c => c.String());
            AddColumn("Contacts.UserStatus", "JsonAttributes", c => c.String());
            AddColumn("CalendarEvents.UserEventAttendance", "JsonAttributes", c => c.String());
            AddColumn("CalendarEvents.CalendarEventFile", "JsonAttributes", c => c.String());
            AddColumn("CalendarEvents.CalendarEventProducts", "JsonAttributes", c => c.String());
            AddColumn("CalendarEvents.CalendarEventStatus", "JsonAttributes", c => c.String());
            AddColumn("CalendarEvents.CalendarEventFileNew", "JsonAttributes", c => c.String());
            AddColumn("CalendarEvents.CalendarEventType", "JsonAttributes", c => c.String());
            AddColumn("CalendarEvents.UserEventAttendanceType", "JsonAttributes", c => c.String());
            AddColumn("Contacts.UserOnlineStatus", "JsonAttributes", c => c.String());
            AddColumn("Payments.Wallet", "JsonAttributes", c => c.String());
            AddColumn("Returning.SalesReturnSalesOrder", "JsonAttributes", c => c.String());
            AddColumn("Returning.SalesReturnAttribute", "JsonAttributes", c => c.String());
            AddColumn("Contacts.CustomerPriority", "JsonAttributes", c => c.String());
            AddColumn("Discounts.SalesReturnDiscounts", "JsonAttributes", c => c.String());
            AddColumn("Returning.SalesReturnFile", "JsonAttributes", c => c.String());
            AddColumn("Returning.SalesReturnItemAttribute", "JsonAttributes", c => c.String());
            AddColumn("Discounts.SalesReturnItemDiscounts", "JsonAttributes", c => c.String());
            AddColumn("Returning.SalesReturnReason", "JsonAttributes", c => c.String());
            AddColumn("Returning.SalesReturnItemStatus", "JsonAttributes", c => c.String());
            AddColumn("Payments.SalesReturnPayment", "JsonAttributes", c => c.String());
            AddColumn("Returning.SalesReturnState", "JsonAttributes", c => c.String());
            AddColumn("Returning.SalesReturnStatus", "JsonAttributes", c => c.String());
            AddColumn("Returning.SalesReturnFileNew", "JsonAttributes", c => c.String());
            AddColumn("Returning.SalesReturnType", "JsonAttributes", c => c.String());
            AddColumn("Sampling.SampleRequestAttribute", "JsonAttributes", c => c.String());
            AddColumn("Discounts.SampleRequestDiscounts", "JsonAttributes", c => c.String());
            AddColumn("Sampling.SampleRequestFile", "JsonAttributes", c => c.String());
            AddColumn("Sampling.SampleRequestItemAttribute", "JsonAttributes", c => c.String());
            AddColumn("Discounts.SampleRequestItemDiscounts", "JsonAttributes", c => c.String());
            AddColumn("Sampling.SampleRequestItemStatus", "JsonAttributes", c => c.String());
            AddColumn("Sampling.SampleRequestState", "JsonAttributes", c => c.String());
            AddColumn("Sampling.SampleRequestStatus", "JsonAttributes", c => c.String());
            AddColumn("Sampling.SampleRequestFileNew", "JsonAttributes", c => c.String());
            AddColumn("Sampling.SampleRequestType", "JsonAttributes", c => c.String());
            AddColumn("System.NoteType", "JsonAttributes", c => c.String());
            AddColumn("Shopping.CartState", "JsonAttributes", c => c.String());
            AddColumn("Shopping.CartStatus", "JsonAttributes", c => c.String());
            AddColumn("Shopping.CartFileNew", "JsonAttributes", c => c.String());
            AddColumn("Shopping.CartType", "JsonAttributes", c => c.String());
            AddColumn("Shopping.CartItemStatus", "JsonAttributes", c => c.String());
            AddColumn("Discounts.DiscountProducts", "JsonAttributes", c => c.String());
            AddColumn("Products.ProductImageNew", "JsonAttributes", c => c.String());
            AddColumn("Products.ProductImageType", "JsonAttributes", c => c.String());
            AddColumn("Shipping.Package", "JsonAttributes", c => c.String());
            AddColumn("Shipping.PackageType", "JsonAttributes", c => c.String());
            AddColumn("Products.ProductAssociationAttribute", "JsonAttributes", c => c.String());
            AddColumn("Products.ProductAssociationType", "JsonAttributes", c => c.String());
            AddColumn("Products.ProductFile", "JsonAttributes", c => c.String());
            AddColumn("Products.ProductImage", "JsonAttributes", c => c.String());
            AddColumn("Products.ProductPricePoint", "JsonAttributes", c => c.String());
            AddColumn("Pricing.PriceRounding", "JsonAttributes", c => c.String());
            AddColumn("Products.ProductFileNew", "JsonAttributes", c => c.String());
            AddColumn("Products.ProductType", "JsonAttributes", c => c.String());
            AddColumn("Categories.CategoryFileNew", "JsonAttributes", c => c.String());
            AddColumn("Discounts.DiscountCode", "JsonAttributes", c => c.String());
            AddColumn("Discounts.DiscountProductType", "JsonAttributes", c => c.String());
            AddColumn("Discounts.DiscountShipCarrierMethods", "JsonAttributes", c => c.String());
            AddColumn("Discounts.DiscountStores", "JsonAttributes", c => c.String());
            AddColumn("Invoicing.SalesInvoiceFile", "JsonAttributes", c => c.String());
            AddColumn("Payments.SalesInvoicePayment", "JsonAttributes", c => c.String());
            AddColumn("Invoicing.SalesInvoiceItemAttribute", "JsonAttributes", c => c.String());
            AddColumn("Discounts.SalesInvoiceItemDiscounts", "JsonAttributes", c => c.String());
            AddColumn("Invoicing.SalesInvoiceItemStatus", "JsonAttributes", c => c.String());
            AddColumn("Invoicing.SalesInvoiceState", "JsonAttributes", c => c.String());
            AddColumn("Invoicing.SalesInvoiceStatus", "JsonAttributes", c => c.String());
            AddColumn("Invoicing.SalesInvoiceFileNew", "JsonAttributes", c => c.String());
            AddColumn("Invoicing.SalesInvoiceType", "JsonAttributes", c => c.String());
            AddColumn("Ordering.SalesOrderAttribute", "JsonAttributes", c => c.String());
            AddColumn("Discounts.SalesOrderDiscounts", "JsonAttributes", c => c.String());
            AddColumn("Ordering.SalesOrderFile", "JsonAttributes", c => c.String());
            AddColumn("Payments.SalesOrderPayment", "JsonAttributes", c => c.String());
            AddColumn("Ordering.SalesOrderState", "JsonAttributes", c => c.String());
            AddColumn("Ordering.SalesOrderStatus", "JsonAttributes", c => c.String());
            AddColumn("Ordering.SalesOrderFileNew", "JsonAttributes", c => c.String());
            AddColumn("Ordering.SalesOrderType", "JsonAttributes", c => c.String());
            AddColumn("Purchasing.PurchaseOrderAttribute", "JsonAttributes", c => c.String());
            AddColumn("Discounts.PurchaseOrderDiscounts", "JsonAttributes", c => c.String());
            AddColumn("Purchasing.PurchaseOrderFile", "JsonAttributes", c => c.String());
            AddColumn("Purchasing.FreeOnBoard", "JsonAttributes", c => c.String());
            AddColumn("Purchasing.PurchaseOrderItemAttribute", "JsonAttributes", c => c.String());
            AddColumn("Discounts.PurchaseOrderItemDiscounts", "JsonAttributes", c => c.String());
            AddColumn("Purchasing.PurchaseOrderItemStatus", "JsonAttributes", c => c.String());
            AddColumn("Purchasing.PurchaseOrderState", "JsonAttributes", c => c.String());
            AddColumn("Purchasing.PurchaseOrderStatus", "JsonAttributes", c => c.String());
            AddColumn("Purchasing.PurchaseOrderFileNew", "JsonAttributes", c => c.String());
            AddColumn("Purchasing.PurchaseOrderType", "JsonAttributes", c => c.String());
            AddColumn("Contacts.ContactImage", "JsonAttributes", c => c.String());
            AddColumn("Contacts.ContactImageType", "JsonAttributes", c => c.String());
            AddColumn("Contacts.ContactType", "JsonAttributes", c => c.String());
            AddColumn("Accounts.AccountPricePoint", "JsonAttributes", c => c.String());
            AddColumn("Accounts.AccountTerm", "JsonAttributes", c => c.String());
            AddColumn("Accounts.AccountImage", "JsonAttributes", c => c.String());
            AddColumn("Accounts.AccountImageType", "JsonAttributes", c => c.String());
            AddColumn("Contacts.Opportunities", "JsonAttributes", c => c.String());
            AddColumn("Accounts.AccountStatus", "JsonAttributes", c => c.String());
            AddColumn("Accounts.AccountType", "JsonAttributes", c => c.String());
            AddColumn("Advertising.AdAccount", "JsonAttributes", c => c.String());
            AddColumn("Advertising.Ad", "JsonAttributes", c => c.String());
            AddColumn("Advertising.AdImage", "JsonAttributes", c => c.String());
            AddColumn("Advertising.AdStore", "JsonAttributes", c => c.String());
            AddColumn("Advertising.AdZone", "JsonAttributes", c => c.String());
            AddColumn("Advertising.AdZoneAccess", "JsonAttributes", c => c.String());
            AddColumn("Counters.CounterLogType", "JsonAttributes", c => c.String());
            AddColumn("Counters.CounterType", "JsonAttributes", c => c.String());
            AddColumn("Advertising.Zone", "JsonAttributes", c => c.String());
            AddColumn("Advertising.ZoneStatus", "JsonAttributes", c => c.String());
            AddColumn("Advertising.ZoneType", "JsonAttributes", c => c.String());
            AddColumn("Tracking.CampaignAd", "JsonAttributes", c => c.String());
            AddColumn("Tracking.CampaignStatus", "JsonAttributes", c => c.String());
            AddColumn("Tracking.CampaignType", "JsonAttributes", c => c.String());
            AddColumn("Advertising.AdImageNew", "JsonAttributes", c => c.String());
            AddColumn("Advertising.AdImageType", "JsonAttributes", c => c.String());
            AddColumn("Advertising.AdStatus", "JsonAttributes", c => c.String());
            AddColumn("Advertising.AdType", "JsonAttributes", c => c.String());
            AddColumn("System.SystemLog", "JsonAttributes", c => c.String());
            AddColumn("Tracking.IPOrganization", "JsonAttributes", c => c.String());
            AddColumn("Tracking.IPOrganizationStatus", "JsonAttributes", c => c.String());
            AddColumn("Tracking.PageViewEvent", "JsonAttributes", c => c.String());
            AddColumn("Tracking.PageViewStatus", "JsonAttributes", c => c.String());
            AddColumn("Tracking.PageViewType", "JsonAttributes", c => c.String());
            AddColumn("Tracking.VisitStatus", "JsonAttributes", c => c.String());
            AddColumn("Tracking.EventStatus", "JsonAttributes", c => c.String());
            AddColumn("Tracking.EventType", "JsonAttributes", c => c.String());
            AddColumn("Favorites.FavoriteShipCarrier", "JsonAttributes", c => c.String());
            AddColumn("Geography.PhonePrefixLookup", "JsonAttributes", c => c.String());
            AddColumn("Pricing.PriceRuleAccount", "JsonAttributes", c => c.String());
            AddColumn("Pricing.PriceRule", "JsonAttributes", c => c.String());
            AddColumn("Pricing.PriceRuleAccountType", "JsonAttributes", c => c.String());
            AddColumn("Pricing.PriceRuleCategory", "JsonAttributes", c => c.String());
            AddColumn("Pricing.PriceRuleProduct", "JsonAttributes", c => c.String());
            AddColumn("Pricing.PriceRuleProductType", "JsonAttributes", c => c.String());
            AddColumn("Pricing.PriceRuleVendor", "JsonAttributes", c => c.String());
            AddColumn("Contacts.ProfanityFilter", "JsonAttributes", c => c.String());
            AddColumn("Reporting.Reports", "JsonAttributes", c => c.String());
            AddColumn("Reporting.ReportTypes", "JsonAttributes", c => c.String());
            AddColumn("Hangfire.ScheduledJobConfiguration", "JsonAttributes", c => c.String());
            AddColumn("Hangfire.ScheduledJobConfigurationSetting", "JsonAttributes", c => c.String());
            AddColumn("System.Setting", "JsonAttributes", c => c.String());
            AddColumn("System.SettingGroup", "JsonAttributes", c => c.String());
            AddColumn("System.SettingType", "JsonAttributes", c => c.String());
            AddColumn("Globalization.UIKey", "JsonAttributes", c => c.String());
            AddColumn("Globalization.UITranslation", "JsonAttributes", c => c.String());
            AddColumn("Shipping.UPSEndOfDay", "JsonAttributes", c => c.String());
            AddColumn("Geography.ZipCode", "JsonAttributes", c => c.String());
            AlterColumn("Discounts.CartItemDiscounts", "DiscountTotal", c => c.Decimal(nullable: false, precision: 18, scale: 4));
            AlterColumn("Vendors.Vendor", "RecommendedPurchaseOrderDollarAmount", c => c.Decimal(precision: 18, scale: 4));
            AlterColumn("Returning.SalesReturnReason", "RestockingFeePercent", c => c.Decimal(precision: 18, scale: 4));
            Sql("UPDATE [Vendors].[Vendor] SET [Hash] = [VendorHash] WHERE [Hash] IS NULL AND [VendorHash] IS NOT NULL");
            DropColumn("Contacts.Contact", "Gender");
            DropColumn("Vendors.Vendor", "VendorHash");
            DropColumn("Contacts.UserType", "IsAdministrator");
            DropColumn("Contacts.UserType", "IsCustomer");
        }

        public override void Down()
        {
            AddColumn("Contacts.UserType", "IsCustomer", c => c.Boolean(nullable: false));
            AddColumn("Contacts.UserType", "IsAdministrator", c => c.Boolean(nullable: false));
            AddColumn("Vendors.Vendor", "VendorHash", c => c.Long());
            AddColumn("Contacts.Contact", "Gender", c => c.Boolean(nullable: false));
            AlterColumn("Returning.SalesReturnReason", "RestockingFeePercent", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Vendors.Vendor", "RecommendedPurchaseOrderDollarAmount", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Discounts.CartItemDiscounts", "DiscountTotal", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            DropColumn("Geography.ZipCode", "JsonAttributes");
            DropColumn("Shipping.UPSEndOfDay", "JsonAttributes");
            DropColumn("Globalization.UITranslation", "JsonAttributes");
            DropColumn("Globalization.UIKey", "JsonAttributes");
            DropColumn("System.SettingType", "JsonAttributes");
            DropColumn("System.SettingGroup", "JsonAttributes");
            DropColumn("System.Setting", "JsonAttributes");
            DropColumn("Hangfire.ScheduledJobConfigurationSetting", "JsonAttributes");
            DropColumn("Hangfire.ScheduledJobConfiguration", "JsonAttributes");
            DropColumn("Reporting.ReportTypes", "JsonAttributes");
            DropColumn("Reporting.Reports", "JsonAttributes");
            DropColumn("Contacts.ProfanityFilter", "JsonAttributes");
            DropColumn("Pricing.PriceRuleVendor", "JsonAttributes");
            DropColumn("Pricing.PriceRuleProductType", "JsonAttributes");
            DropColumn("Pricing.PriceRuleProduct", "JsonAttributes");
            DropColumn("Pricing.PriceRuleCategory", "JsonAttributes");
            DropColumn("Pricing.PriceRuleAccountType", "JsonAttributes");
            DropColumn("Pricing.PriceRule", "JsonAttributes");
            DropColumn("Pricing.PriceRuleAccount", "JsonAttributes");
            DropColumn("Geography.PhonePrefixLookup", "JsonAttributes");
            DropColumn("Favorites.FavoriteShipCarrier", "JsonAttributes");
            DropColumn("Tracking.EventType", "JsonAttributes");
            DropColumn("Tracking.EventStatus", "JsonAttributes");
            DropColumn("Tracking.VisitStatus", "JsonAttributes");
            DropColumn("Tracking.PageViewType", "JsonAttributes");
            DropColumn("Tracking.PageViewStatus", "JsonAttributes");
            DropColumn("Tracking.PageViewEvent", "JsonAttributes");
            DropColumn("Tracking.IPOrganizationStatus", "JsonAttributes");
            DropColumn("Tracking.IPOrganization", "JsonAttributes");
            DropColumn("System.SystemLog", "JsonAttributes");
            DropColumn("Advertising.AdType", "JsonAttributes");
            DropColumn("Advertising.AdStatus", "JsonAttributes");
            DropColumn("Advertising.AdImageType", "JsonAttributes");
            DropColumn("Advertising.AdImageNew", "JsonAttributes");
            DropColumn("Tracking.CampaignType", "JsonAttributes");
            DropColumn("Tracking.CampaignStatus", "JsonAttributes");
            DropColumn("Tracking.CampaignAd", "JsonAttributes");
            DropColumn("Advertising.ZoneType", "JsonAttributes");
            DropColumn("Advertising.ZoneStatus", "JsonAttributes");
            DropColumn("Advertising.Zone", "JsonAttributes");
            DropColumn("Counters.CounterType", "JsonAttributes");
            DropColumn("Counters.CounterLogType", "JsonAttributes");
            DropColumn("Advertising.AdZoneAccess", "JsonAttributes");
            DropColumn("Advertising.AdZone", "JsonAttributes");
            DropColumn("Advertising.AdStore", "JsonAttributes");
            DropColumn("Advertising.AdImage", "JsonAttributes");
            DropColumn("Advertising.Ad", "JsonAttributes");
            DropColumn("Advertising.AdAccount", "JsonAttributes");
            DropColumn("Accounts.AccountType", "JsonAttributes");
            DropColumn("Accounts.AccountStatus", "JsonAttributes");
            DropColumn("Contacts.Opportunities", "JsonAttributes");
            DropColumn("Accounts.AccountImageType", "JsonAttributes");
            DropColumn("Accounts.AccountImage", "JsonAttributes");
            DropColumn("Accounts.AccountTerm", "JsonAttributes");
            DropColumn("Accounts.AccountPricePoint", "JsonAttributes");
            DropColumn("Contacts.ContactType", "JsonAttributes");
            DropColumn("Contacts.ContactImageType", "JsonAttributes");
            DropColumn("Contacts.ContactImage", "JsonAttributes");
            DropColumn("Purchasing.PurchaseOrderType", "JsonAttributes");
            DropColumn("Purchasing.PurchaseOrderFileNew", "JsonAttributes");
            DropColumn("Purchasing.PurchaseOrderStatus", "JsonAttributes");
            DropColumn("Purchasing.PurchaseOrderState", "JsonAttributes");
            DropColumn("Purchasing.PurchaseOrderItemStatus", "JsonAttributes");
            DropColumn("Discounts.PurchaseOrderItemDiscounts", "JsonAttributes");
            DropColumn("Purchasing.PurchaseOrderItemAttribute", "JsonAttributes");
            DropColumn("Purchasing.FreeOnBoard", "JsonAttributes");
            DropColumn("Purchasing.PurchaseOrderFile", "JsonAttributes");
            DropColumn("Discounts.PurchaseOrderDiscounts", "JsonAttributes");
            DropColumn("Purchasing.PurchaseOrderAttribute", "JsonAttributes");
            DropColumn("Ordering.SalesOrderType", "JsonAttributes");
            DropColumn("Ordering.SalesOrderFileNew", "JsonAttributes");
            DropColumn("Ordering.SalesOrderStatus", "JsonAttributes");
            DropColumn("Ordering.SalesOrderState", "JsonAttributes");
            DropColumn("Payments.SalesOrderPayment", "JsonAttributes");
            DropColumn("Ordering.SalesOrderFile", "JsonAttributes");
            DropColumn("Discounts.SalesOrderDiscounts", "JsonAttributes");
            DropColumn("Ordering.SalesOrderAttribute", "JsonAttributes");
            DropColumn("Invoicing.SalesInvoiceType", "JsonAttributes");
            DropColumn("Invoicing.SalesInvoiceFileNew", "JsonAttributes");
            DropColumn("Invoicing.SalesInvoiceStatus", "JsonAttributes");
            DropColumn("Invoicing.SalesInvoiceState", "JsonAttributes");
            DropColumn("Invoicing.SalesInvoiceItemStatus", "JsonAttributes");
            DropColumn("Discounts.SalesInvoiceItemDiscounts", "JsonAttributes");
            DropColumn("Invoicing.SalesInvoiceItemAttribute", "JsonAttributes");
            DropColumn("Payments.SalesInvoicePayment", "JsonAttributes");
            DropColumn("Invoicing.SalesInvoiceFile", "JsonAttributes");
            DropColumn("Discounts.DiscountStores", "JsonAttributes");
            DropColumn("Discounts.DiscountShipCarrierMethods", "JsonAttributes");
            DropColumn("Discounts.DiscountProductType", "JsonAttributes");
            DropColumn("Discounts.DiscountCode", "JsonAttributes");
            DropColumn("Categories.CategoryFileNew", "JsonAttributes");
            DropColumn("Products.ProductType", "JsonAttributes");
            DropColumn("Products.ProductFileNew", "JsonAttributes");
            DropColumn("Pricing.PriceRounding", "JsonAttributes");
            DropColumn("Products.ProductPricePoint", "JsonAttributes");
            DropColumn("Products.ProductImage", "JsonAttributes");
            DropColumn("Products.ProductFile", "JsonAttributes");
            DropColumn("Products.ProductAssociationType", "JsonAttributes");
            DropColumn("Products.ProductAssociationAttribute", "JsonAttributes");
            DropColumn("Shipping.PackageType", "JsonAttributes");
            DropColumn("Shipping.Package", "JsonAttributes");
            DropColumn("Products.ProductImageType", "JsonAttributes");
            DropColumn("Products.ProductImageNew", "JsonAttributes");
            DropColumn("Discounts.DiscountProducts", "JsonAttributes");
            DropColumn("Shopping.CartItemStatus", "JsonAttributes");
            DropColumn("Shopping.CartType", "JsonAttributes");
            DropColumn("Shopping.CartFileNew", "JsonAttributes");
            DropColumn("Shopping.CartStatus", "JsonAttributes");
            DropColumn("Shopping.CartState", "JsonAttributes");
            DropColumn("System.NoteType", "JsonAttributes");
            DropColumn("Sampling.SampleRequestType", "JsonAttributes");
            DropColumn("Sampling.SampleRequestFileNew", "JsonAttributes");
            DropColumn("Sampling.SampleRequestStatus", "JsonAttributes");
            DropColumn("Sampling.SampleRequestState", "JsonAttributes");
            DropColumn("Sampling.SampleRequestItemStatus", "JsonAttributes");
            DropColumn("Discounts.SampleRequestItemDiscounts", "JsonAttributes");
            DropColumn("Sampling.SampleRequestItemAttribute", "JsonAttributes");
            DropColumn("Sampling.SampleRequestFile", "JsonAttributes");
            DropColumn("Discounts.SampleRequestDiscounts", "JsonAttributes");
            DropColumn("Sampling.SampleRequestAttribute", "JsonAttributes");
            DropColumn("Returning.SalesReturnType", "JsonAttributes");
            DropColumn("Returning.SalesReturnFileNew", "JsonAttributes");
            DropColumn("Returning.SalesReturnStatus", "JsonAttributes");
            DropColumn("Returning.SalesReturnState", "JsonAttributes");
            DropColumn("Payments.SalesReturnPayment", "JsonAttributes");
            DropColumn("Returning.SalesReturnItemStatus", "JsonAttributes");
            DropColumn("Returning.SalesReturnReason", "JsonAttributes");
            DropColumn("Discounts.SalesReturnItemDiscounts", "JsonAttributes");
            DropColumn("Returning.SalesReturnItemAttribute", "JsonAttributes");
            DropColumn("Returning.SalesReturnFile", "JsonAttributes");
            DropColumn("Discounts.SalesReturnDiscounts", "JsonAttributes");
            DropColumn("Contacts.CustomerPriority", "JsonAttributes");
            DropColumn("Returning.SalesReturnAttribute", "JsonAttributes");
            DropColumn("Returning.SalesReturnSalesOrder", "JsonAttributes");
            DropColumn("Payments.Wallet", "JsonAttributes");
            DropColumn("Contacts.UserOnlineStatus", "JsonAttributes");
            DropColumn("CalendarEvents.UserEventAttendanceType", "JsonAttributes");
            DropColumn("CalendarEvents.CalendarEventType", "JsonAttributes");
            DropColumn("CalendarEvents.CalendarEventFileNew", "JsonAttributes");
            DropColumn("CalendarEvents.CalendarEventStatus", "JsonAttributes");
            DropColumn("CalendarEvents.CalendarEventProducts", "JsonAttributes");
            DropColumn("CalendarEvents.CalendarEventFile", "JsonAttributes");
            DropColumn("CalendarEvents.UserEventAttendance", "JsonAttributes");
            DropColumn("Contacts.UserStatus", "JsonAttributes");
            DropColumn("Quoting.SalesQuoteType", "JsonAttributes");
            DropColumn("Quoting.SalesQuoteFileNew", "JsonAttributes");
            DropColumn("Quoting.SalesQuoteStatus", "JsonAttributes");
            DropColumn("Quoting.SalesQuoteState", "JsonAttributes");
            DropColumn("Shipping.ShipOption", "JsonAttributes");
            DropColumn("Quoting.SalesQuoteCategory", "JsonAttributes");
            DropColumn("Quoting.SalesQuoteItemStatus", "JsonAttributes");
            DropColumn("Discounts.SalesQuoteItemDiscounts", "JsonAttributes");
            DropColumn("Quoting.SalesQuoteItemAttribute", "JsonAttributes");
            DropColumn("Quoting.SalesQuoteFile", "JsonAttributes");
            DropColumn("Discounts.SalesQuoteDiscounts", "JsonAttributes");
            DropColumn("Quoting.SalesQuoteAttribute", "JsonAttributes");
            DropColumn("Quoting.SalesQuoteSalesOrder", "JsonAttributes");
            DropColumn("Contacts.RoleUser", "JsonAttributes");
            DropColumn("Contacts.ReferralCodeType", "JsonAttributes");
            DropColumn("Contacts.ReferralCodeStatus", "JsonAttributes");
            DropColumn("Contacts.UserImageType", "JsonAttributes");
            DropColumn("Contacts.UserImage", "JsonAttributes");
            DropColumn("Favorites.FavoriteVendor", "JsonAttributes");
            DropColumn("Favorites.FavoriteStore", "JsonAttributes");
            DropColumn("Favorites.FavoriteManufacturer", "JsonAttributes");
            DropColumn("Favorites.FavoriteCategory", "JsonAttributes");
            DropColumn("Stores.StoreType", "JsonAttributes");
            DropColumn("Contacts.UserType", "JsonAttributes");
            DropColumn("Stores.StoreUserType", "JsonAttributes");
            DropColumn("Stores.StoreUser", "JsonAttributes");
            DropColumn("Products.ProductSubscriptionType", "JsonAttributes");
            DropColumn("Payments.SubscriptionStatus", "JsonAttributes");
            DropColumn("Payments.PaymentType", "JsonAttributes");
            DropColumn("Payments.PaymentStatus", "JsonAttributes");
            DropColumn("Payments.PaymentMethod", "JsonAttributes");
            DropColumn("Payments.Payment", "JsonAttributes");
            DropColumn("Payments.SubscriptionHistory", "JsonAttributes");
            DropColumn("Payments.RepeatType", "JsonAttributes");
            DropColumn("Payments.Subscription", "JsonAttributes");
            DropColumn("Stores.StoreSubscription", "JsonAttributes");
            DropColumn("Stores.StoreImage", "JsonAttributes");
            DropColumn("Stores.StoreContact", "JsonAttributes");
            DropColumn("Categories.CategoryType", "JsonAttributes");
            DropColumn("Stores.StoreCategoryType", "JsonAttributes");
            DropColumn("Stores.StoreCategory", "JsonAttributes");
            DropColumn("Stores.BadgeType", "JsonAttributes");
            DropColumn("Stores.BadgeImageType", "JsonAttributes");
            DropColumn("Stores.BadgeImage", "JsonAttributes");
            DropColumn("Stores.Badge", "JsonAttributes");
            DropColumn("Stores.StoreBadge", "JsonAttributes");
            DropColumn("Pricing.PricePoint", "JsonAttributes");
            DropColumn("Stores.StoreAccount", "JsonAttributes");
            DropColumn("Reviews.ReviewType", "JsonAttributes");
            DropColumn("Vendors.VendorTerm", "JsonAttributes");
            DropColumn("Vendors.Term", "JsonAttributes");
            DropColumn("Stores.StoreVendor", "JsonAttributes");
            DropColumn("Shipping.ShipmentType", "JsonAttributes");
            DropColumn("Shipping.ShipmentStatus", "JsonAttributes");
            DropColumn("Shipping.ShipmentEvent", "JsonAttributes");
            DropColumn("Vendors.ShipVia", "JsonAttributes");
            DropColumn("Shipping.ShipCarrierMethod", "JsonAttributes");
            DropColumn("Shipping.CarrierOrigin", "JsonAttributes");
            DropColumn("Shipping.CarrierInvoice", "JsonAttributes");
            DropColumn("Shipping.ShipCarrier", "JsonAttributes");
            DropColumn("Vendors.VendorProduct", "JsonAttributes");
            DropColumn("Stores.StoreProduct", "JsonAttributes");
            DropColumn("Ordering.SalesOrderItemStatus", "JsonAttributes");
            DropColumn("Discounts.SalesOrderItemDiscounts", "JsonAttributes");
            DropColumn("Ordering.SalesOrderItemAttribute", "JsonAttributes");
            DropColumn("Products.ProductInventoryLocationSection", "JsonAttributes");
            DropColumn("Stores.StoreInventoryLocation", "JsonAttributes");
            DropColumn("Inventory.InventoryLocation", "JsonAttributes");
            DropColumn("Inventory.InventoryLocationSection", "JsonAttributes");
            DropColumn("Shipping.Shipment", "JsonAttributes");
            DropColumn("Vendors.VendorImageType", "JsonAttributes");
            DropColumn("Vendors.VendorImage", "JsonAttributes");
            DropColumn("Contacts.ContactMethod", "JsonAttributes");
            DropColumn("Vendors.Vendor", "JsonAttributes");
            DropColumn("Vendors.VendorManufacturer", "JsonAttributes");
            DropColumn("Stores.StoreManufacturer", "JsonAttributes");
            DropColumn("Manufacturers.ManufacturerProduct", "JsonAttributes");
            DropColumn("Manufacturers.ManufacturerImageType", "JsonAttributes");
            DropColumn("Manufacturers.ManufacturerImage", "JsonAttributes");
            DropColumn("Manufacturers.Manufacturer", "JsonAttributes");
            DropColumn("Reviews.Review", "JsonAttributes");
            DropColumn("Stores.StoreImageType", "JsonAttributes");
            DropColumn("Stores.StoreImageNew", "JsonAttributes");
            DropColumn("Stores.BrandImageType", "JsonAttributes");
            DropColumn("Stores.BrandImage", "JsonAttributes");
            DropColumn("Stores.StoreSiteDomain", "JsonAttributes");
            DropColumn("Stores.SocialProvider", "JsonAttributes");
            DropColumn("Stores.SiteDomainSocialProvider", "JsonAttributes");
            DropColumn("Stores.BrandSiteDomain", "JsonAttributes");
            DropColumn("Stores.Brand", "JsonAttributes");
            DropColumn("Stores.BrandStore", "JsonAttributes");
            DropColumn("Groups.GroupType", "JsonAttributes");
            DropColumn("Groups.GroupStatus", "JsonAttributes");
            DropColumn("Groups.GroupUser", "JsonAttributes");
            DropColumn("Messaging.EmailType", "JsonAttributes");
            DropColumn("Messaging.EmailStatus", "JsonAttributes");
            DropColumn("Messaging.EmailTemplate", "JsonAttributes");
            DropColumn("Messaging.EmailQueue", "JsonAttributes");
            DropColumn("Messaging.MessageRecipient", "JsonAttributes");
            DropColumn("Media.StoredFile", "JsonAttributes");
            DropColumn("Messaging.MessageAttachment", "JsonAttributes");
            DropColumn("Messaging.Message", "JsonAttributes");
            DropColumn("Messaging.Conversation", "JsonAttributes");
            DropColumn("Messaging.ConversationUser", "JsonAttributes");
            DropColumn("Contacts.UserAttribute", "JsonAttributes");
            DropColumn("System.Note", "JsonAttributes");
            DropColumn("Shopping.CartFile", "JsonAttributes");
            DropColumn("Discounts.CartDiscounts", "JsonAttributes");
            DropColumn("Shopping.CartAttribute", "JsonAttributes");
            DropColumn("Discounts.CartItemDiscounts", "JsonAttributes");
            DropColumn("Shopping.CartItemAttribute", "JsonAttributes");
            DropColumn("Products.ProductAttribute", "JsonAttributes");
            DropColumn("Products.ProductCategoryAttribute", "JsonAttributes");
            DropColumn("Categories.CategoryImageType", "JsonAttributes");
            DropColumn("Categories.CategoryImageNew", "JsonAttributes");
            DropColumn("Categories.CategoryFile", "JsonAttributes");
            DropColumn("Categories.CategoryImage", "JsonAttributes");
            DropColumn("Categories.CategoryAttribute", "JsonAttributes");
            DropColumn("Discounts.DiscountCategories", "JsonAttributes");
            DropColumn("Discounts.Discount", "JsonAttributes");
            DropColumn("Discounts.SalesInvoiceDiscounts", "JsonAttributes");
            DropColumn("Invoicing.SalesInvoiceAttribute", "JsonAttributes");
            DropColumn("Invoicing.SalesOrderSalesInvoice", "JsonAttributes");
            DropColumn("Purchasing.SalesOrderPurchaseOrder", "JsonAttributes");
            DropColumn("Tax.TaxCountry", "JsonAttributes");
            DropColumn("Tax.TaxRegion", "JsonAttributes");
            DropColumn("Geography.RegionLanguage", "JsonAttributes");
            DropColumn("Geography.InterRegion", "JsonAttributes");
            DropColumn("Geography.RegionImageType", "JsonAttributes");
            DropColumn("Geography.RegionImage", "JsonAttributes");
            DropColumn("Tax.TaxDistrict", "JsonAttributes");
            DropColumn("Geography.DistrictLanguage", "JsonAttributes");
            DropColumn("Geography.DistrictImageType", "JsonAttributes");
            DropColumn("Geography.DistrictImage", "JsonAttributes");
            DropColumn("Geography.DistrictCurrency", "JsonAttributes");
            DropColumn("Geography.District", "JsonAttributes");
            DropColumn("Geography.RegionCurrency", "JsonAttributes");
            DropColumn("Geography.Region", "JsonAttributes");
            DropColumn("Globalization.LanguageImageType", "JsonAttributes");
            DropColumn("Globalization.LanguageImage", "JsonAttributes");
            DropColumn("Globalization.Language", "JsonAttributes");
            DropColumn("Geography.CountryLanguage", "JsonAttributes");
            DropColumn("Geography.CountryImageType", "JsonAttributes");
            DropColumn("Geography.CountryImage", "JsonAttributes");
            DropColumn("Media.Video", "JsonAttributes");
            DropColumn("Media.LibraryType", "JsonAttributes");
            DropColumn("Media.Document", "JsonAttributes");
            DropColumn("Media.Image", "JsonAttributes");
            DropColumn("Media.FileData", "JsonAttributes");
            DropColumn("Media.File", "JsonAttributes");
            DropColumn("Media.Audio", "JsonAttributes");
            DropColumn("Media.Library", "JsonAttributes");
            DropColumn("Currencies.CurrencyImageType", "JsonAttributes");
            DropColumn("Currencies.CurrencyImage", "JsonAttributes");
            DropColumn("Currencies.HistoricalCurrencyRate", "JsonAttributes");
            DropColumn("Currencies.Currency", "JsonAttributes");
            DropColumn("Geography.CountryCurrency", "JsonAttributes");
            DropColumn("Geography.Country", "JsonAttributes");
            DropColumn("Geography.Address", "JsonAttributes");
            DropColumn("Contacts.Contact", "JsonAttributes");
            DropColumn("Accounts.AccountContact", "JsonAttributes");
            DropColumn("Attributes.AttributeType", "JsonAttributes");
            DropColumn("Attributes.GeneralAttribute", "JsonAttributes");
            DropColumn("Attributes.AttributeValue", "JsonAttributes");
            DropColumn("Accounts.AccountAttribute", "JsonAttributes");
            CreateIndex("Vendors.Vendor", "VendorHash");
        }
    }
}
