// <copyright file="201903182024241_Overhaul2019Q1.cs" company="clarity-ventures.com">
// Copyright (c) 2019-2023 clarity-ventures.com. All rights reserved.
// </copyright>
// <summary>Implements the 201903182024241 overhaul 2019 q 1 class</summary>
namespace Clarity.Ecommerce.DataModel.Migrations
{
    using System.Data.Entity.Migrations;

    public partial class Overhaul2019Q1 : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("Vendors.Vendor", "ShipViaID", "Vendors.ShipVia");
            DropForeignKey("Vendors.Vendor", "TermID", "Vendors.Term");
            DropForeignKey("Returning.SalesReturn", "CustomerPriorityID", "Contacts.CustomerPriority");
            DropForeignKey("Ordering.SalesOrder", "CustomerPriorityID", "Contacts.CustomerPriority");
            DropForeignKey("Purchasing.PurchaseOrder", "FreeOnBoardID", "Purchasing.FreeOnBoard");
            DropForeignKey("Purchasing.PurchaseOrder", "VendorTermID", "Vendors.VendorTerm");
            DropIndex("Currencies.HistoricalCurrencyRate", new[] { "StartingCurrencyID" });
            DropIndex("Currencies.HistoricalCurrencyRate", new[] { "EndingCurrencyID" });
            DropIndex("Purchasing.PurchaseOrder", new[] { "FreeOnBoardID" });
            DropIndex("Purchasing.PurchaseOrder", new[] { "VendorTermID" });
            DropIndex("Ordering.SalesOrder", new[] { "CustomerPriorityID" });
            DropIndex("Shopping.Cart", "Unq_BySessionTypeUserActive");
            DropIndex("Vendors.Vendor", new[] { "TermID" });
            DropIndex("Vendors.Vendor", new[] { "ShipViaID" });
            DropIndex("Returning.SalesReturn", new[] { "CustomerPriorityID" });
            RenameColumn(table: "Accounts.AccountContact", name: "AccountID", newName: "MasterID");
            RenameColumn(table: "Accounts.AccountContact", name: "ContactID", newName: "SlaveID");
            RenameColumn(table: "Accounts.AccountPricePoint", name: "AccountID", newName: "MasterID");
            RenameColumn(table: "Accounts.AccountPricePoint", name: "PricePointID", newName: "SlaveID");
            RenameColumn(table: "Advertising.AdAccount", name: "AccountID", newName: "SlaveID");
            RenameColumn(table: "Advertising.AdAccount", name: "AdID", newName: "MasterID");
            RenameColumn(table: "Advertising.AdStore", name: "AdID", newName: "MasterID");
            RenameColumn(table: "Advertising.AdStore", name: "StoreID", newName: "SlaveID");
            RenameColumn(table: "Advertising.AdZone", name: "AdID", newName: "MasterID");
            RenameColumn(table: "Advertising.AdZone", name: "ZoneID", newName: "SlaveID");
            RenameColumn(table: "CalendarEvents.CalendarEventProducts", name: "CalendarEventID", newName: "MasterID");
            RenameColumn(table: "CalendarEvents.CalendarEventProducts", name: "ProductID", newName: "SlaveID");
            RenameColumn(table: "CalendarEvents.UserEventAttendance", name: "CalendarEventID", newName: "MasterID");
            RenameColumn(table: "CalendarEvents.UserEventAttendance", name: "UserID", newName: "SlaveID");
            RenameColumn(table: "Discounts.CartDiscounts", name: "DiscountID", newName: "SlaveID");
            RenameColumn(table: "Discounts.CartItemDiscounts", name: "DiscountID", newName: "SlaveID");
            RenameColumn(table: "Discounts.DiscountCategories", name: "CategoryID", newName: "SlaveID");
            RenameColumn(table: "Discounts.DiscountCategories", name: "DiscountID", newName: "MasterID");
            RenameColumn(table: "Discounts.DiscountProducts", name: "DiscountID", newName: "MasterID");
            RenameColumn(table: "Discounts.DiscountProducts", name: "ProductID", newName: "SlaveID");
            RenameColumn(table: "Discounts.DiscountProductType", name: "DiscountID", newName: "MasterID");
            RenameColumn(table: "Discounts.DiscountProductType", name: "ProductTypeID", newName: "SlaveID");
            RenameColumn(table: "Discounts.DiscountShipCarrierMethods", name: "DiscountID", newName: "MasterID");
            RenameColumn(table: "Discounts.DiscountShipCarrierMethods", name: "ShipCarrierMethodID", newName: "SlaveID");
            RenameColumn(table: "Discounts.DiscountStores", name: "DiscountID", newName: "MasterID");
            RenameColumn(table: "Discounts.DiscountStores", name: "StoreID", newName: "SlaveID");
            RenameColumn(table: "Discounts.PurchaseOrderDiscounts", name: "DiscountID", newName: "SlaveID");
            RenameColumn(table: "Discounts.PurchaseOrderItemDiscounts", name: "DiscountID", newName: "SlaveID");
            RenameColumn(table: "Discounts.SalesInvoiceDiscounts", name: "DiscountID", newName: "SlaveID");
            RenameColumn(table: "Discounts.SalesInvoiceItemDiscounts", name: "DiscountID", newName: "SlaveID");
            RenameColumn(table: "Discounts.SalesOrderDiscounts", name: "DiscountID", newName: "SlaveID");
            RenameColumn(table: "Discounts.SalesOrderItemDiscounts", name: "DiscountID", newName: "SlaveID");
            RenameColumn(table: "Discounts.SalesQuoteDiscounts", name: "DiscountID", newName: "SlaveID");
            RenameColumn(table: "Discounts.SalesQuoteItemDiscounts", name: "DiscountID", newName: "SlaveID");
            RenameColumn(table: "Discounts.SalesReturnDiscounts", name: "DiscountID", newName: "SlaveID");
            RenameColumn(table: "Discounts.SalesReturnItemDiscounts", name: "DiscountID", newName: "SlaveID");
            RenameColumn(table: "Discounts.SampleRequestDiscounts", name: "DiscountID", newName: "SlaveID");
            RenameColumn(table: "Discounts.SampleRequestItemDiscounts", name: "DiscountID", newName: "SlaveID");
            RenameColumn(table: "Favorites.FavoriteCategory", name: "FavoriteID", newName: "SlaveID");
            RenameColumn(table: "Favorites.FavoriteCategory", name: "UserID", newName: "MasterID");
            RenameColumn(table: "Favorites.FavoriteManufacturer", name: "FavoriteID", newName: "SlaveID");
            RenameColumn(table: "Favorites.FavoriteManufacturer", name: "UserID", newName: "MasterID");
            RenameColumn(table: "Favorites.FavoriteShipCarrier", name: "FavoriteID", newName: "SlaveID");
            RenameColumn(table: "Favorites.FavoriteShipCarrier", name: "UserID", newName: "MasterID");
            RenameColumn(table: "Favorites.FavoriteStore", name: "FavoriteID", newName: "SlaveID");
            RenameColumn(table: "Favorites.FavoriteStore", name: "UserID", newName: "MasterID");
            RenameColumn(table: "Favorites.FavoriteVendor", name: "FavoriteID", newName: "SlaveID");
            RenameColumn(table: "Favorites.FavoriteVendor", name: "UserID", newName: "MasterID");
            RenameColumn(table: "Geography.CountryCurrency", name: "CurrencyID", newName: "SlaveID");
            RenameColumn(table: "Geography.CountryLanguage", name: "LanguageID", newName: "SlaveID");
            RenameColumn(table: "Geography.DistrictCurrency", name: "CurrencyID", newName: "SlaveID");
            RenameColumn(table: "Geography.DistrictLanguage", name: "LanguageID", newName: "SlaveID");
            RenameColumn(table: "Geography.RegionCurrency", name: "CurrencyID", newName: "SlaveID");
            RenameColumn(table: "Geography.RegionLanguage", name: "LanguageID", newName: "SlaveID");
            RenameColumn(table: "Groups.GroupUser", name: "GroupID", newName: "MasterID");
            RenameColumn(table: "Groups.GroupUser", name: "UserID", newName: "SlaveID");
            RenameColumn(table: "Hangfire.ScheduledJobConfigurationSetting", name: "ScheduledJobConfigurationID", newName: "MasterID");
            RenameColumn(table: "Hangfire.ScheduledJobConfigurationSetting", name: "SettingID", newName: "SlaveID");
            RenameColumn(table: "Invoicing.SalesInvoiceContact", name: "ContactID", newName: "SlaveID");
            RenameColumn(table: "Invoicing.SalesInvoiceContact", name: "SalesInvoiceID", newName: "MasterID");
            RenameColumn(table: "Invoicing.SalesOrderSalesInvoice", name: "SalesInvoiceID", newName: "SlaveID");
            RenameColumn(table: "Invoicing.SalesOrderSalesInvoice", name: "SalesOrderID", newName: "MasterID");
            RenameColumn(table: "Manufacturers.ManufacturerProduct", name: "ManufacturerID", newName: "MasterID");
            RenameColumn(table: "Manufacturers.ManufacturerProduct", name: "ProductID", newName: "SlaveID");
            RenameColumn(table: "Messaging.ConversationUser", name: "ConversationID", newName: "MasterID");
            RenameColumn(table: "Messaging.ConversationUser", name: "UserID", newName: "SlaveID");
            RenameColumn(table: "Messaging.EmailQueueAttachment", name: "EmailQueueID", newName: "MasterID");
            RenameColumn(table: "Messaging.EmailQueueAttachment", name: "StoredFileID", newName: "SlaveID");
            RenameColumn(table: "Messaging.MessageAttachment", name: "MessageID", newName: "MasterID");
            RenameColumn(table: "Messaging.MessageAttachment", name: "StoredFileID", newName: "SlaveID");
            RenameColumn(table: "Messaging.MessageRecipient", name: "MessageID", newName: "MasterID");
            RenameColumn(table: "Messaging.MessageRecipient", name: "ToUserID", newName: "SlaveID");
            RenameColumn(table: "Ordering.SalesOrderContact", name: "ContactID", newName: "SlaveID");
            RenameColumn(table: "Ordering.SalesOrderContact", name: "SalesOrderID", newName: "MasterID");
            RenameColumn(table: "Payments.SalesInvoicePayment", name: "PaymentID", newName: "SlaveID");
            RenameColumn(table: "Payments.SalesInvoicePayment", name: "SalesInvoiceID", newName: "MasterID");
            RenameColumn(table: "Payments.SalesOrderPayment", name: "PaymentID", newName: "SlaveID");
            RenameColumn(table: "Payments.SalesOrderPayment", name: "SalesOrderID", newName: "MasterID");
            RenameColumn(table: "Payments.SalesReturnPayment", name: "PaymentID", newName: "SlaveID");
            RenameColumn(table: "Payments.SalesReturnPayment", name: "SalesReturnID", newName: "MasterID");
            RenameColumn(table: "Payments.SubscriptionHistory", name: "PaymentID", newName: "SlaveID");
            RenameColumn(table: "Payments.SubscriptionHistory", name: "SubscriptionID", newName: "MasterID");
            RenameColumn(table: "Pricing.PriceRuleAccount", name: "AccountID", newName: "SlaveID");
            RenameColumn(table: "Pricing.PriceRuleAccount", name: "PriceRuleID", newName: "MasterID");
            RenameColumn(table: "Pricing.PriceRuleAccountType", name: "AccountTypeID", newName: "SlaveID");
            RenameColumn(table: "Pricing.PriceRuleAccountType", name: "PriceRuleID", newName: "MasterID");
            RenameColumn(table: "Pricing.PriceRuleCategory", name: "CategoryID", newName: "SlaveID");
            RenameColumn(table: "Pricing.PriceRuleCategory", name: "PriceRuleID", newName: "MasterID");
            RenameColumn(table: "Pricing.PriceRuleCountry", name: "CountryID", newName: "SlaveID");
            RenameColumn(table: "Pricing.PriceRuleCountry", name: "PriceRuleID", newName: "MasterID");
            RenameColumn(table: "Pricing.PriceRuleManufacturer", name: "ManufacturerID", newName: "SlaveID");
            RenameColumn(table: "Pricing.PriceRuleManufacturer", name: "PriceRuleID", newName: "MasterID");
            RenameColumn(table: "Pricing.PriceRuleProduct", name: "PriceRuleID", newName: "MasterID");
            RenameColumn(table: "Pricing.PriceRuleProduct", name: "ProductID", newName: "SlaveID");
            RenameColumn(table: "Pricing.PriceRuleProductType", name: "PriceRuleID", newName: "MasterID");
            RenameColumn(table: "Pricing.PriceRuleProductType", name: "ProductTypeID", newName: "SlaveID");
            RenameColumn(table: "Pricing.PriceRuleStore", name: "PriceRuleID", newName: "MasterID");
            RenameColumn(table: "Pricing.PriceRuleStore", name: "StoreID", newName: "SlaveID");
            RenameColumn(table: "Pricing.PriceRuleVendor", name: "PriceRuleID", newName: "MasterID");
            RenameColumn(table: "Pricing.PriceRuleVendor", name: "VendorID", newName: "SlaveID");
            RenameColumn(table: "Products.ProductAssociation", name: "AssociatedProductID", newName: "SlaveID");
            RenameColumn(table: "Products.ProductAssociation", name: "PrimaryProductID", newName: "MasterID");
            RenameColumn(table: "Products.ProductCategory", name: "CategoryID", newName: "SlaveID");
            RenameColumn(table: "Products.ProductCategory", name: "ProductID", newName: "MasterID");
            RenameColumn(table: "Products.ProductInventoryLocationSection", name: "InventoryLocationSectionID", newName: "SlaveID");
            RenameColumn(table: "Products.ProductInventoryLocationSection", name: "ProductID", newName: "MasterID");
            RenameColumn(table: "Products.ProductPricePoint", name: "PricePointID", newName: "SlaveID");
            RenameColumn(table: "Products.ProductPricePoint", name: "ProductID", newName: "MasterID");
            RenameColumn(table: "Products.ProductSubscriptionType", name: "ProductID", newName: "MasterID");
            RenameColumn(table: "Products.ProductSubscriptionType", name: "SubscriptionTypeID", newName: "SlaveID");
            RenameColumn(table: "Purchasing.PurchaseOrderContact", name: "ContactID", newName: "SlaveID");
            RenameColumn(table: "Purchasing.PurchaseOrderContact", name: "PurchaseOrderID", newName: "MasterID");
            RenameColumn(table: "Purchasing.SalesOrderPurchaseOrder", name: "PurchaseOrderID", newName: "SlaveID");
            RenameColumn(table: "Purchasing.SalesOrderPurchaseOrder", name: "SalesOrderID", newName: "MasterID");
            RenameColumn(table: "Quoting.SalesQuoteCategory", name: "CategoryID", newName: "SlaveID");
            RenameColumn(table: "Quoting.SalesQuoteCategory", name: "SalesQuoteID", newName: "MasterID");
            RenameColumn(table: "Quoting.SalesQuoteContact", name: "ContactID", newName: "SlaveID");
            RenameColumn(table: "Quoting.SalesQuoteContact", name: "SalesQuoteID", newName: "MasterID");
            RenameColumn(table: "Quoting.SalesQuoteSalesOrder", name: "SalesOrderID", newName: "SlaveID");
            RenameColumn(table: "Quoting.SalesQuoteSalesOrder", name: "SalesQuoteID", newName: "MasterID");
            RenameColumn(table: "Returning.SalesReturnContact", name: "ContactID", newName: "SlaveID");
            RenameColumn(table: "Returning.SalesReturnContact", name: "SalesReturnID", newName: "MasterID");
            RenameColumn(table: "Returning.SalesReturnSalesOrder", name: "SalesOrderID", newName: "SlaveID");
            RenameColumn(table: "Returning.SalesReturnSalesOrder", name: "SalesReturnID", newName: "MasterID");
            RenameColumn(table: "Sampling.SampleRequestContact", name: "ContactID", newName: "SlaveID");
            RenameColumn(table: "Sampling.SampleRequestContact", name: "SampleRequestID", newName: "MasterID");
            RenameColumn(table: "Shopping.CartContact", name: "CartID", newName: "MasterID");
            RenameColumn(table: "Shopping.CartContact", name: "ContactID", newName: "SlaveID");
            RenameColumn(table: "Stores.BrandSiteDomain", name: "BrandID", newName: "MasterID");
            RenameColumn(table: "Stores.BrandSiteDomain", name: "SiteDomainID", newName: "SlaveID");
            RenameColumn(table: "Stores.BrandStore", name: "BrandID", newName: "MasterID");
            RenameColumn(table: "Stores.BrandStore", name: "StoreID", newName: "SlaveID");
            RenameColumn(table: "Stores.SiteDomainSocialProvider", name: "SiteDomainID", newName: "MasterID");
            RenameColumn(table: "Stores.SiteDomainSocialProvider", name: "SocialProviderID", newName: "SlaveID");
            RenameColumn(table: "Stores.StoreAccount", name: "AccountID", newName: "SlaveID");
            RenameColumn(table: "Stores.StoreAccount", name: "StoreID", newName: "MasterID");
            RenameColumn(table: "Stores.StoreBadge", name: "BadgeID", newName: "SlaveID");
            RenameColumn(table: "Stores.StoreBadge", name: "StoreID", newName: "MasterID");
            RenameColumn(table: "Stores.StoreCategory", name: "CategoryID", newName: "SlaveID");
            RenameColumn(table: "Stores.StoreCategory", name: "StoreID", newName: "MasterID");
            RenameColumn(table: "Stores.StoreCategoryType", name: "CategoryTypeID", newName: "SlaveID");
            RenameColumn(table: "Stores.StoreCategoryType", name: "StoreID", newName: "MasterID");
            RenameColumn(table: "Stores.StoreContact", name: "ContactID", newName: "SlaveID");
            RenameColumn(table: "Stores.StoreContact", name: "StoreID", newName: "MasterID");
            RenameColumn(table: "Stores.StoreInventoryLocation", name: "InventoryLocationID", newName: "SlaveID");
            RenameColumn(table: "Stores.StoreInventoryLocation", name: "StoreID", newName: "MasterID");
            RenameColumn(table: "Stores.StoreManufacturer", name: "ManufacturerID", newName: "SlaveID");
            RenameColumn(table: "Stores.StoreManufacturer", name: "StoreID", newName: "MasterID");
            RenameColumn(table: "Stores.StoreProduct", name: "ProductID", newName: "SlaveID");
            RenameColumn(table: "Stores.StoreProduct", name: "StoreID", newName: "MasterID");
            RenameColumn(table: "Stores.StoreSiteDomain", name: "SiteDomainID", newName: "SlaveID");
            RenameColumn(table: "Stores.StoreSiteDomain", name: "StoreID", newName: "MasterID");
            RenameColumn(table: "Stores.StoreSubscription", name: "StoreID", newName: "MasterID");
            RenameColumn(table: "Stores.StoreSubscription", name: "SubscriptionID", newName: "SlaveID");
            RenameColumn(table: "Stores.StoreUser", name: "StoreID", newName: "MasterID");
            RenameColumn(table: "Stores.StoreUser", name: "UserID", newName: "SlaveID");
            RenameColumn(table: "Stores.StoreUserType", name: "StoreID", newName: "MasterID");
            RenameColumn(table: "Stores.StoreUserType", name: "UserTypeID", newName: "SlaveID");
            RenameColumn(table: "Stores.StoreVendor", name: "StoreID", newName: "MasterID");
            RenameColumn(table: "Stores.StoreVendor", name: "VendorID", newName: "SlaveID");
            RenameColumn(table: "Tracking.CampaignAd", name: "AdID", newName: "SlaveID");
            RenameColumn(table: "Tracking.CampaignAd", name: "CampaignID", newName: "MasterID");
            RenameColumn(table: "Tracking.PageViewEvent", name: "EventID", newName: "SlaveID");
            RenameColumn(table: "Tracking.PageViewEvent", name: "PageViewID", newName: "MasterID");
            RenameColumn(table: "Vendors.VendorManufacturer", name: "ManufacturerID", newName: "SlaveID");
            RenameColumn(table: "Vendors.VendorManufacturer", name: "VendorID", newName: "MasterID");
            RenameColumn(table: "Vendors.VendorProduct", name: "ProductID", newName: "SlaveID");
            RenameColumn(table: "Vendors.VendorProduct", name: "VendorID", newName: "MasterID");
            RenameIndex(table: "Accounts.AccountContact", name: "IX_AccountID", newName: "IX_MasterID");
            RenameIndex(table: "Accounts.AccountContact", name: "IX_ContactID", newName: "IX_SlaveID");
            RenameIndex(table: "Accounts.AccountPricePoint", name: "IX_AccountID", newName: "IX_MasterID");
            RenameIndex(table: "Accounts.AccountPricePoint", name: "IX_PricePointID", newName: "IX_SlaveID");
            RenameIndex(table: "Advertising.AdAccount", name: "IX_AccountID", newName: "IX_SlaveID");
            RenameIndex(table: "Advertising.AdAccount", name: "IX_AdID", newName: "IX_MasterID");
            RenameIndex(table: "Advertising.AdStore", name: "IX_AdID", newName: "IX_MasterID");
            RenameIndex(table: "Advertising.AdStore", name: "IX_StoreID", newName: "IX_SlaveID");
            RenameIndex(table: "Advertising.AdZone", name: "IX_AdID", newName: "IX_MasterID");
            RenameIndex(table: "Advertising.AdZone", name: "IX_ZoneID", newName: "IX_SlaveID");
            RenameIndex(table: "CalendarEvents.CalendarEventProducts", name: "IX_CalendarEventID", newName: "IX_MasterID");
            RenameIndex(table: "CalendarEvents.CalendarEventProducts", name: "IX_ProductID", newName: "IX_SlaveID");
            RenameIndex(table: "CalendarEvents.UserEventAttendance", name: "IX_CalendarEventID", newName: "IX_MasterID");
            RenameIndex(table: "CalendarEvents.UserEventAttendance", name: "IX_UserID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.CartDiscounts", name: "IX_DiscountID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.CartItemDiscounts", name: "IX_DiscountID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.DiscountCategories", name: "IX_CategoryID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.DiscountCategories", name: "IX_DiscountID", newName: "IX_MasterID");
            RenameIndex(table: "Discounts.DiscountProducts", name: "IX_DiscountID", newName: "IX_MasterID");
            RenameIndex(table: "Discounts.DiscountProducts", name: "IX_ProductID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.DiscountProductType", name: "IX_DiscountID", newName: "IX_MasterID");
            RenameIndex(table: "Discounts.DiscountProductType", name: "IX_ProductTypeID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.DiscountShipCarrierMethods", name: "IX_DiscountID", newName: "IX_MasterID");
            RenameIndex(table: "Discounts.DiscountShipCarrierMethods", name: "IX_ShipCarrierMethodID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.DiscountStores", name: "IX_DiscountID", newName: "IX_MasterID");
            RenameIndex(table: "Discounts.DiscountStores", name: "IX_StoreID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.PurchaseOrderDiscounts", name: "IX_DiscountID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.PurchaseOrderItemDiscounts", name: "IX_DiscountID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.SalesInvoiceDiscounts", name: "IX_DiscountID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.SalesInvoiceItemDiscounts", name: "IX_DiscountID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.SalesOrderDiscounts", name: "IX_DiscountID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.SalesOrderItemDiscounts", name: "IX_DiscountID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.SalesQuoteDiscounts", name: "IX_DiscountID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.SalesQuoteItemDiscounts", name: "IX_DiscountID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.SalesReturnDiscounts", name: "IX_DiscountID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.SalesReturnItemDiscounts", name: "IX_DiscountID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.SampleRequestDiscounts", name: "IX_DiscountID", newName: "IX_SlaveID");
            RenameIndex(table: "Discounts.SampleRequestItemDiscounts", name: "IX_DiscountID", newName: "IX_SlaveID");
            RenameIndex(table: "Favorites.FavoriteCategory", name: "IX_FavoriteID", newName: "IX_SlaveID");
            RenameIndex(table: "Favorites.FavoriteCategory", name: "IX_UserID", newName: "IX_MasterID");
            RenameIndex(table: "Favorites.FavoriteManufacturer", name: "IX_FavoriteID", newName: "IX_SlaveID");
            RenameIndex(table: "Favorites.FavoriteManufacturer", name: "IX_UserID", newName: "IX_MasterID");
            RenameIndex(table: "Favorites.FavoriteShipCarrier", name: "IX_FavoriteID", newName: "IX_SlaveID");
            RenameIndex(table: "Favorites.FavoriteShipCarrier", name: "IX_UserID", newName: "IX_MasterID");
            RenameIndex(table: "Favorites.FavoriteStore", name: "IX_FavoriteID", newName: "IX_SlaveID");
            RenameIndex(table: "Favorites.FavoriteStore", name: "IX_UserID", newName: "IX_MasterID");
            RenameIndex(table: "Favorites.FavoriteVendor", name: "IX_FavoriteID", newName: "IX_SlaveID");
            RenameIndex(table: "Favorites.FavoriteVendor", name: "IX_UserID", newName: "IX_MasterID");
            RenameIndex(table: "Geography.CountryCurrency", name: "IX_CurrencyID", newName: "IX_SlaveID");
            RenameIndex(table: "Geography.CountryLanguage", name: "IX_LanguageID", newName: "IX_SlaveID");
            RenameIndex(table: "Geography.DistrictCurrency", name: "IX_CurrencyID", newName: "IX_SlaveID");
            RenameIndex(table: "Geography.DistrictLanguage", name: "IX_LanguageID", newName: "IX_SlaveID");
            RenameIndex(table: "Geography.RegionCurrency", name: "IX_CurrencyID", newName: "IX_SlaveID");
            RenameIndex(table: "Geography.RegionLanguage", name: "IX_LanguageID", newName: "IX_SlaveID");
            RenameIndex(table: "Groups.GroupUser", name: "IX_GroupID", newName: "IX_MasterID");
            RenameIndex(table: "Groups.GroupUser", name: "IX_UserID", newName: "IX_SlaveID");
            RenameIndex(table: "Hangfire.ScheduledJobConfigurationSetting", name: "IX_ScheduledJobConfigurationID", newName: "IX_MasterID");
            RenameIndex(table: "Hangfire.ScheduledJobConfigurationSetting", name: "IX_SettingID", newName: "IX_SlaveID");
            RenameIndex(table: "Invoicing.SalesInvoiceContact", name: "IX_ContactID", newName: "IX_SlaveID");
            RenameIndex(table: "Invoicing.SalesInvoiceContact", name: "IX_SalesInvoiceID", newName: "IX_MasterID");
            RenameIndex(table: "Invoicing.SalesOrderSalesInvoice", name: "IX_SalesInvoiceID", newName: "IX_SlaveID");
            RenameIndex(table: "Invoicing.SalesOrderSalesInvoice", name: "IX_SalesOrderID", newName: "IX_MasterID");
            RenameIndex(table: "Manufacturers.ManufacturerProduct", name: "IX_ManufacturerID", newName: "IX_MasterID");
            RenameIndex(table: "Manufacturers.ManufacturerProduct", name: "IX_ProductID", newName: "IX_SlaveID");
            RenameIndex(table: "Messaging.ConversationUser", name: "IX_ConversationID", newName: "IX_MasterID");
            RenameIndex(table: "Messaging.ConversationUser", name: "IX_UserID", newName: "IX_SlaveID");
            RenameIndex(table: "Messaging.EmailQueueAttachment", name: "IX_EmailQueueID", newName: "IX_MasterID");
            RenameIndex(table: "Messaging.EmailQueueAttachment", name: "IX_StoredFileID", newName: "IX_SlaveID");
            RenameIndex(table: "Messaging.MessageAttachment", name: "IX_MessageID", newName: "IX_MasterID");
            RenameIndex(table: "Messaging.MessageAttachment", name: "IX_StoredFileID", newName: "IX_SlaveID");
            RenameIndex(table: "Messaging.MessageRecipient", name: "IX_MessageID", newName: "IX_MasterID");
            RenameIndex(table: "Messaging.MessageRecipient", name: "IX_ToUserID", newName: "IX_SlaveID");
            RenameIndex(table: "Ordering.SalesOrderContact", name: "IX_ContactID", newName: "IX_SlaveID");
            RenameIndex(table: "Ordering.SalesOrderContact", name: "IX_SalesOrderID", newName: "IX_MasterID");
            RenameIndex(table: "Payments.SalesInvoicePayment", name: "IX_PaymentID", newName: "IX_SlaveID");
            RenameIndex(table: "Payments.SalesInvoicePayment", name: "IX_SalesInvoiceID", newName: "IX_MasterID");
            RenameIndex(table: "Payments.SalesOrderPayment", name: "IX_PaymentID", newName: "IX_SlaveID");
            RenameIndex(table: "Payments.SalesOrderPayment", name: "IX_SalesOrderID", newName: "IX_MasterID");
            RenameIndex(table: "Payments.SalesReturnPayment", name: "IX_PaymentID", newName: "IX_SlaveID");
            RenameIndex(table: "Payments.SalesReturnPayment", name: "IX_SalesReturnID", newName: "IX_MasterID");
            RenameIndex(table: "Payments.SubscriptionHistory", name: "IX_PaymentID", newName: "IX_SlaveID");
            RenameIndex(table: "Payments.SubscriptionHistory", name: "IX_SubscriptionID", newName: "IX_MasterID");
            RenameIndex(table: "Pricing.PriceRuleAccount", name: "IX_AccountID", newName: "IX_SlaveID");
            RenameIndex(table: "Pricing.PriceRuleAccount", name: "IX_PriceRuleID", newName: "IX_MasterID");
            RenameIndex(table: "Pricing.PriceRuleAccountType", name: "IX_AccountTypeID", newName: "IX_SlaveID");
            RenameIndex(table: "Pricing.PriceRuleAccountType", name: "IX_PriceRuleID", newName: "IX_MasterID");
            RenameIndex(table: "Pricing.PriceRuleCategory", name: "IX_CategoryID", newName: "IX_SlaveID");
            RenameIndex(table: "Pricing.PriceRuleCategory", name: "IX_PriceRuleID", newName: "IX_MasterID");
            RenameIndex(table: "Pricing.PriceRuleCountry", name: "IX_CountryID", newName: "IX_SlaveID");
            RenameIndex(table: "Pricing.PriceRuleCountry", name: "IX_PriceRuleID", newName: "IX_MasterID");
            RenameIndex(table: "Pricing.PriceRuleManufacturer", name: "IX_ManufacturerID", newName: "IX_SlaveID");
            RenameIndex(table: "Pricing.PriceRuleManufacturer", name: "IX_PriceRuleID", newName: "IX_MasterID");
            RenameIndex(table: "Pricing.PriceRuleProduct", name: "IX_PriceRuleID", newName: "IX_MasterID");
            RenameIndex(table: "Pricing.PriceRuleProduct", name: "IX_ProductID", newName: "IX_SlaveID");
            RenameIndex(table: "Pricing.PriceRuleProductType", name: "IX_PriceRuleID", newName: "IX_MasterID");
            RenameIndex(table: "Pricing.PriceRuleProductType", name: "IX_ProductTypeID", newName: "IX_SlaveID");
            RenameIndex(table: "Pricing.PriceRuleStore", name: "IX_PriceRuleID", newName: "IX_MasterID");
            RenameIndex(table: "Pricing.PriceRuleStore", name: "IX_StoreID", newName: "IX_SlaveID");
            RenameIndex(table: "Pricing.PriceRuleVendor", name: "IX_PriceRuleID", newName: "IX_MasterID");
            RenameIndex(table: "Pricing.PriceRuleVendor", name: "IX_VendorID", newName: "IX_SlaveID");
            RenameIndex(table: "Products.ProductAssociation", name: "IX_AssociatedProductID", newName: "IX_SlaveID");
            RenameIndex(table: "Products.ProductAssociation", name: "IX_PrimaryProductID", newName: "IX_MasterID");
            RenameIndex(table: "Products.ProductCategory", name: "IX_CategoryID", newName: "IX_SlaveID");
            RenameIndex(table: "Products.ProductCategory", name: "IX_ProductID", newName: "IX_MasterID");
            RenameIndex(table: "Products.ProductInventoryLocationSection", name: "IX_InventoryLocationSectionID", newName: "IX_SlaveID");
            RenameIndex(table: "Products.ProductInventoryLocationSection", name: "IX_ProductID", newName: "IX_MasterID");
            RenameIndex(table: "Products.ProductPricePoint", name: "IX_PricePointID", newName: "IX_SlaveID");
            RenameIndex(table: "Products.ProductPricePoint", name: "IX_ProductID", newName: "IX_MasterID");
            RenameIndex(table: "Products.ProductSubscriptionType", name: "IX_ProductID", newName: "IX_MasterID");
            RenameIndex(table: "Products.ProductSubscriptionType", name: "IX_SubscriptionTypeID", newName: "IX_SlaveID");
            RenameIndex(table: "Purchasing.PurchaseOrderContact", name: "IX_ContactID", newName: "IX_SlaveID");
            RenameIndex(table: "Purchasing.PurchaseOrderContact", name: "IX_PurchaseOrderID", newName: "IX_MasterID");
            RenameIndex(table: "Purchasing.SalesOrderPurchaseOrder", name: "IX_PurchaseOrderID", newName: "IX_SlaveID");
            RenameIndex(table: "Purchasing.SalesOrderPurchaseOrder", name: "IX_SalesOrderID", newName: "IX_MasterID");
            RenameIndex(table: "Quoting.SalesQuoteCategory", name: "IX_CategoryID", newName: "IX_SlaveID");
            RenameIndex(table: "Quoting.SalesQuoteCategory", name: "IX_SalesQuoteID", newName: "IX_MasterID");
            RenameIndex(table: "Quoting.SalesQuoteContact", name: "IX_ContactID", newName: "IX_SlaveID");
            RenameIndex(table: "Quoting.SalesQuoteContact", name: "IX_SalesQuoteID", newName: "IX_MasterID");
            RenameIndex(table: "Quoting.SalesQuoteSalesOrder", name: "IX_SalesOrderID", newName: "IX_SlaveID");
            RenameIndex(table: "Quoting.SalesQuoteSalesOrder", name: "IX_SalesQuoteID", newName: "IX_MasterID");
            RenameIndex(table: "Returning.SalesReturnContact", name: "IX_ContactID", newName: "IX_SlaveID");
            RenameIndex(table: "Returning.SalesReturnContact", name: "IX_SalesReturnID", newName: "IX_MasterID");
            RenameIndex(table: "Returning.SalesReturnSalesOrder", name: "IX_SalesOrderID", newName: "IX_SlaveID");
            RenameIndex(table: "Returning.SalesReturnSalesOrder", name: "IX_SalesReturnID", newName: "IX_MasterID");
            RenameIndex(table: "Sampling.SampleRequestContact", name: "IX_ContactID", newName: "IX_SlaveID");
            RenameIndex(table: "Sampling.SampleRequestContact", name: "IX_SampleRequestID", newName: "IX_MasterID");
            RenameIndex(table: "Shopping.CartContact", name: "IX_CartID", newName: "IX_MasterID");
            RenameIndex(table: "Shopping.CartContact", name: "IX_ContactID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.BrandSiteDomain", name: "IX_BrandID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.BrandSiteDomain", name: "IX_SiteDomainID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.BrandStore", name: "IX_BrandID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.BrandStore", name: "IX_StoreID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.SiteDomainSocialProvider", name: "IX_SiteDomainID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.SiteDomainSocialProvider", name: "IX_SocialProviderID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.StoreAccount", name: "IX_AccountID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.StoreAccount", name: "IX_StoreID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.StoreBadge", name: "IX_BadgeID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.StoreBadge", name: "IX_StoreID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.StoreCategory", name: "IX_CategoryID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.StoreCategory", name: "IX_StoreID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.StoreCategoryType", name: "IX_CategoryTypeID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.StoreCategoryType", name: "IX_StoreID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.StoreContact", name: "IX_ContactID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.StoreContact", name: "IX_StoreID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.StoreInventoryLocation", name: "IX_InventoryLocationID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.StoreInventoryLocation", name: "IX_StoreID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.StoreManufacturer", name: "IX_ManufacturerID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.StoreManufacturer", name: "IX_StoreID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.StoreProduct", name: "IX_ProductID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.StoreProduct", name: "IX_StoreID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.StoreSiteDomain", name: "IX_SiteDomainID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.StoreSiteDomain", name: "IX_StoreID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.StoreSubscription", name: "IX_StoreID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.StoreSubscription", name: "IX_SubscriptionID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.StoreUser", name: "IX_StoreID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.StoreUser", name: "IX_UserID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.StoreUserType", name: "IX_StoreID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.StoreUserType", name: "IX_UserTypeID", newName: "IX_SlaveID");
            RenameIndex(table: "Stores.StoreVendor", name: "IX_StoreID", newName: "IX_MasterID");
            RenameIndex(table: "Stores.StoreVendor", name: "IX_VendorID", newName: "IX_SlaveID");
            RenameIndex(table: "Tracking.CampaignAd", name: "IX_AdID", newName: "IX_SlaveID");
            RenameIndex(table: "Tracking.CampaignAd", name: "IX_CampaignID", newName: "IX_MasterID");
            RenameIndex(table: "Tracking.PageViewEvent", name: "IX_EventID", newName: "IX_SlaveID");
            RenameIndex(table: "Tracking.PageViewEvent", name: "IX_PageViewID", newName: "IX_MasterID");
            RenameIndex(table: "Vendors.VendorManufacturer", name: "IX_ManufacturerID", newName: "IX_SlaveID");
            RenameIndex(table: "Vendors.VendorManufacturer", name: "IX_VendorID", newName: "IX_MasterID");
            RenameIndex(table: "Vendors.VendorProduct", name: "IX_ProductID", newName: "IX_SlaveID");
            RenameIndex(table: "Vendors.VendorProduct", name: "IX_VendorID", newName: "IX_MasterID");
            CreateTable(
                "Accounts.AccountAssociation",
                c => new
                    {
                        ID = c.Int(nullable: false, identity: true),
                        CustomKey = c.String(maxLength: 128, unicode: false),
                        CreatedDate = c.DateTime(nullable: false, precision: 7, storeType: "datetime2"),
                        UpdatedDate = c.DateTime(precision: 7, storeType: "datetime2"),
                        Active = c.Boolean(nullable: false),
                        Hash = c.Long(),
                        JsonAttributes = c.String(),
                        MasterID = c.Int(nullable: false),
                        SlaveID = c.Int(nullable: false),
                        TypeID = c.Int(nullable: false),
                    })
                .PrimaryKey(t => t.ID)
                .ForeignKey("Accounts.Account", t => t.MasterID)
                .ForeignKey("Accounts.Account", t => t.SlaveID)
                .ForeignKey("Accounts.AccountAssociationType", t => t.TypeID, cascadeDelete: true)
                .Index(t => t.ID)
                .Index(t => t.CustomKey)
                .Index(t => t.CreatedDate)
                .Index(t => t.UpdatedDate)
                .Index(t => t.Active)
                .Index(t => t.Hash)
                .Index(t => t.MasterID)
                .Index(t => t.SlaveID)
                .Index(t => t.TypeID);

            CreateTable(
                "Accounts.AccountAssociationType",
                c => new
                    {
                        ID = c.Int(nullable: false, identity: true),
                        CustomKey = c.String(maxLength: 128, unicode: false),
                        CreatedDate = c.DateTime(nullable: false, precision: 7, storeType: "datetime2"),
                        UpdatedDate = c.DateTime(precision: 7, storeType: "datetime2"),
                        Active = c.Boolean(nullable: false),
                        Hash = c.Long(),
                        JsonAttributes = c.String(),
                        Name = c.String(maxLength: 256, unicode: false),
                        Description = c.String(unicode: false),
                        DisplayName = c.String(maxLength: 256, unicode: false),
                        SortOrder = c.Int(),
                    })
                .PrimaryKey(t => t.ID)
                .Index(t => t.ID)
                .Index(t => t.CustomKey)
                .Index(t => t.CreatedDate)
                .Index(t => t.UpdatedDate)
                .Index(t => t.Active)
                .Index(t => t.Hash)
                .Index(t => t.Name)
                .Index(t => t.DisplayName)
                .Index(t => t.SortOrder);

            AddColumn("Messaging.EmailQueueAttachment", "SeoUrl", c => c.String(maxLength: 512, unicode: false));
            AddColumn("Messaging.EmailQueueAttachment", "SeoKeywords", c => c.String(maxLength: 512, unicode: false));
            AddColumn("Messaging.EmailQueueAttachment", "SeoPageTitle", c => c.String(maxLength: 75, unicode: false));
            AddColumn("Messaging.EmailQueueAttachment", "SeoDescription", c => c.String(maxLength: 256, unicode: false));
            AddColumn("Messaging.EmailQueueAttachment", "SeoMetaData", c => c.String(maxLength: 512, unicode: false));
            AddColumn("Messaging.EmailQueueAttachment", "FileAccessTypeID", c => c.Int(nullable: false));
            AddColumn("Messaging.EmailQueueAttachment", "SortOrder", c => c.Int());
            AddColumn("Payments.Payment", "CheckNumber", c => c.String(maxLength: 8));
            AddColumn("Payments.Payment", "RoutingNumberLast4", c => c.String(maxLength: 4));
            AddColumn("Payments.Payment", "AccountNumberLast4", c => c.String(maxLength: 4));
            AddColumn("Payments.Payment", "BankName", c => c.String(maxLength: 100));
            AddColumn("Discounts.DiscountCode", "UserID", c => c.Int());
            Sql("UPDATE [Accounts].[Account] SET [IsTaxable] = 1 WHERE [IsTaxable] IS NULL");
            AlterColumn("Accounts.Account", "IsTaxable", c => c.Boolean(nullable: false));
            AlterColumn("Accounts.Account", "TaxExemptionNo", c => c.String(maxLength: 128, unicode: false));
            AlterColumn("Accounts.Account", "TaxEntityUseCode", c => c.String(maxLength: 128, unicode: false));
            AlterColumn("Stores.Store", "OperatingHoursMondayStart", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Stores.Store", "OperatingHoursMondayEnd", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Stores.Store", "OperatingHoursTuesdayStart", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Stores.Store", "OperatingHoursTuesdayEnd", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Stores.Store", "OperatingHoursWednesdayStart", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Stores.Store", "OperatingHoursWednesdayEnd", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Stores.Store", "OperatingHoursThursdayStart", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Stores.Store", "OperatingHoursThursdayEnd", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Stores.Store", "OperatingHoursFridayStart", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Stores.Store", "OperatingHoursFridayEnd", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Stores.Store", "OperatingHoursSaturdayStart", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Stores.Store", "OperatingHoursSaturdayEnd", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Stores.Store", "OperatingHoursSundayStart", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Stores.Store", "OperatingHoursSundayEnd", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Stores.SiteDomain", "Url", c => c.String(nullable: false, maxLength: 512, unicode: false));
            AlterColumn("Stores.SiteDomainSocialProvider", "UrlValues", c => c.String(unicode: false));
            AlterColumn("Stores.SocialProvider", "Url", c => c.String(maxLength: 1024, unicode: false));
            AlterColumn("Stores.SocialProvider", "UrlFormat", c => c.String(maxLength: 1024, unicode: false));
            AlterColumn("Discounts.CartItemDiscounts", "DiscountTotal", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AlterColumn("Media.StoredFile", "DisplayName", c => c.String(maxLength: 128));
            AlterColumn("Media.StoredFile", "SeoTitle", c => c.String(maxLength: 75));
            AlterColumn("Media.StoredFile", "Author", c => c.String(maxLength: 512));
            AlterColumn("Media.StoredFile", "Copyright", c => c.String(maxLength: 512));
            AlterColumn("Media.StoredFile", "FileFormat", c => c.String(maxLength: 512));
            AlterColumn("Media.StoredFile", "FileName", c => c.String(maxLength: 512));
            AlterColumn("Stores.StoreProduct", "PriceBase", c => c.Decimal(precision: 18, scale: 4));
            AlterColumn("Stores.StoreProduct", "PriceMsrp", c => c.Decimal(precision: 18, scale: 4));
            AlterColumn("Stores.StoreProduct", "PriceReduction", c => c.Decimal(precision: 18, scale: 4));
            AlterColumn("Stores.StoreProduct", "PriceSale", c => c.Decimal(precision: 18, scale: 4));
            AlterColumn("Payments.Payment", "Amount", c => c.Decimal(precision: 18, scale: 5));
            AlterColumn("Payments.Payment", "Last4CardDigits", c => c.String(maxLength: 4));
            AlterColumn("Payments.Subscription", "Memo", c => c.String(maxLength: 128, unicode: false));
            AlterColumn("Payments.Subscription", "CreditUponUpgrade", c => c.Decimal(precision: 18, scale: 4));
            AlterColumn("Payments.Subscription", "FilterKey1", c => c.String(maxLength: 128, unicode: false));
            AlterColumn("Payments.Subscription", "FilterKey2", c => c.String(maxLength: 128, unicode: false));
            AlterColumn("Payments.Subscription", "FilterKey3", c => c.String(maxLength: 128, unicode: false));
            AlterColumn("Payments.SubscriptionHistory", "Memo", c => c.String(nullable: false, maxLength: 128, unicode: false));
            AlterColumn("CalendarEvents.CalendarEvent", "ShortDescription", c => c.String(maxLength: 256, unicode: false));
            AlterColumn("CalendarEvents.CalendarEvent", "EventDurationUnitOfMeasure", c => c.String(maxLength: 128, unicode: false));
            AlterColumn("CalendarEvents.CalendarEvent", "RecurrenceString", c => c.String(maxLength: 1024, unicode: false));
            AlterColumn("CalendarEvents.CalendarEventDetail", "Location", c => c.String(maxLength: 256, unicode: false));
            AlterColumn("Products.ProductAssociation", "UnitOfMeasure", c => c.String(maxLength: 128, unicode: false));
            AlterColumn("Ordering.SalesOrderEvent", "OldBalanceDue", c => c.Decimal(precision: 18, scale: 4));
            AlterColumn("Ordering.SalesOrderEvent", "NewBalanceDue", c => c.Decimal(precision: 18, scale: 4));
            AlterColumn("Advertising.Ad", "TargetURL", c => c.String(nullable: false, maxLength: 512, unicode: false));
            CreateIndex("Currencies.HistoricalCurrencyRate", "StartingCurrencyID");
            CreateIndex("Currencies.HistoricalCurrencyRate", "EndingCurrencyID");
            CreateIndex("Shopping.Cart", new[] { "SessionID", "TypeID", "UserID", "Active" }, unique: true, name: "Unq_BySessionTypeUserActive");
            CreateIndex("Discounts.DiscountCode", "UserID");
            AddForeignKey("Discounts.DiscountCode", "UserID", "Contacts.User", "ID");
            DropColumn("Accounts.Account", "Website");
            DropColumn("Accounts.Account", "AccountTermID");
            DropColumn("Contacts.Contact", "Fax2");
            DropColumn("Contacts.Contact", "Fax3");
            DropColumn("Contacts.Contact", "NotificationPhone");
            DropColumn("Contacts.Contact", "NotificationEmail");
            DropColumn("Contacts.Contact", "NotificationViaEmail");
            DropColumn("Contacts.Contact", "NotificationViaSMSPhone");
            DropColumn("Contacts.Contact", "DateOfBirth");
            DropColumn("Purchasing.PurchaseOrder", "FreeOnBoardID");
            DropColumn("Purchasing.PurchaseOrder", "VendorTermID");
            DropColumn("Ordering.SalesOrder", "CustomerPriorityID");
            DropColumn("Discounts.Discount", "Enable");
            DropColumn("Contacts.User", "IsEmailSubscriber");
            DropColumn("Contacts.User", "IsCatalogSubscriber");
            DropColumn("Contacts.User", "PercentDiscount");
            DropColumn("Contacts.User", "IsSuperAdmin");
            DropColumn("Contacts.User", "SalesRepContactsUserID");
            DropColumn("Vendors.Vendor", "TermID");
            DropColumn("Vendors.Vendor", "ShipViaID");
            DropColumn("Returning.SalesReturn", "CustomerPriorityID");
            DropColumn("Payments.Payment", "AVS");
            DropColumn("Payments.Subscription", "AccountKey");
            DropColumn("Payments.Subscription", "UserKey");
            DropColumn("Attributes.GeneralAttribute", "Group");
        }

        public override void Down()
        {
            AddColumn("Attributes.GeneralAttribute", "Group", c => c.String(maxLength: 128, unicode: false));
            AddColumn("Payments.Subscription", "UserKey", c => c.String());
            AddColumn("Payments.Subscription", "AccountKey", c => c.String());
            AddColumn("Payments.Payment", "AVS", c => c.String(maxLength: 100));
            AddColumn("Returning.SalesReturn", "CustomerPriorityID", c => c.Int());
            AddColumn("Vendors.Vendor", "ShipViaID", c => c.Int());
            AddColumn("Vendors.Vendor", "TermID", c => c.Int());
            AddColumn("Contacts.User", "SalesRepContactsUserID", c => c.Int());
            AddColumn("Contacts.User", "IsSuperAdmin", c => c.Boolean(nullable: false));
            AddColumn("Contacts.User", "PercentDiscount", c => c.Int());
            AddColumn("Contacts.User", "IsCatalogSubscriber", c => c.Boolean(nullable: false));
            AddColumn("Contacts.User", "IsEmailSubscriber", c => c.Boolean(nullable: false));
            AddColumn("Discounts.Discount", "Enable", c => c.Boolean(nullable: false));
            AddColumn("Ordering.SalesOrder", "CustomerPriorityID", c => c.Int());
            AddColumn("Purchasing.PurchaseOrder", "VendorTermID", c => c.Int());
            AddColumn("Purchasing.PurchaseOrder", "FreeOnBoardID", c => c.Int());
            AddColumn("Contacts.Contact", "DateOfBirth", c => c.DateTime(precision: 7, storeType: "datetime2"));
            AddColumn("Contacts.Contact", "NotificationViaSMSPhone", c => c.Boolean(nullable: false));
            AddColumn("Contacts.Contact", "NotificationViaEmail", c => c.Boolean(nullable: false));
            AddColumn("Contacts.Contact", "NotificationEmail", c => c.String(maxLength: 1000, unicode: false));
            AddColumn("Contacts.Contact", "NotificationPhone", c => c.String(maxLength: 50, unicode: false));
            AddColumn("Contacts.Contact", "Fax3", c => c.String(maxLength: 50, unicode: false));
            AddColumn("Contacts.Contact", "Fax2", c => c.String(maxLength: 50, unicode: false));
            AddColumn("Accounts.Account", "AccountTermID", c => c.Int());
            AddColumn("Accounts.Account", "Website", c => c.String(maxLength: 1000, unicode: false));
            DropForeignKey("Accounts.AccountAssociation", "TypeID", "Accounts.AccountAssociationType");
            DropForeignKey("Accounts.AccountAssociation", "SlaveID", "Accounts.Account");
            DropForeignKey("Accounts.AccountAssociation", "MasterID", "Accounts.Account");
            DropForeignKey("Discounts.DiscountCode", "UserID", "Contacts.User");
            DropIndex("Accounts.AccountAssociationType", new[] { "SortOrder" });
            DropIndex("Accounts.AccountAssociationType", new[] { "DisplayName" });
            DropIndex("Accounts.AccountAssociationType", new[] { "Name" });
            DropIndex("Accounts.AccountAssociationType", new[] { "Hash" });
            DropIndex("Accounts.AccountAssociationType", new[] { "Active" });
            DropIndex("Accounts.AccountAssociationType", new[] { "UpdatedDate" });
            DropIndex("Accounts.AccountAssociationType", new[] { "CreatedDate" });
            DropIndex("Accounts.AccountAssociationType", new[] { "CustomKey" });
            DropIndex("Accounts.AccountAssociationType", new[] { "ID" });
            DropIndex("Discounts.DiscountCode", new[] { "UserID" });
            DropIndex("Shopping.Cart", "Unq_BySessionTypeUserActive");
            DropIndex("Currencies.HistoricalCurrencyRate", new[] { "EndingCurrencyID" });
            DropIndex("Currencies.HistoricalCurrencyRate", new[] { "StartingCurrencyID" });
            DropIndex("Accounts.AccountAssociation", new[] { "TypeID" });
            DropIndex("Accounts.AccountAssociation", new[] { "SlaveID" });
            DropIndex("Accounts.AccountAssociation", new[] { "MasterID" });
            DropIndex("Accounts.AccountAssociation", new[] { "Hash" });
            DropIndex("Accounts.AccountAssociation", new[] { "Active" });
            DropIndex("Accounts.AccountAssociation", new[] { "UpdatedDate" });
            DropIndex("Accounts.AccountAssociation", new[] { "CreatedDate" });
            DropIndex("Accounts.AccountAssociation", new[] { "CustomKey" });
            DropIndex("Accounts.AccountAssociation", new[] { "ID" });
            AlterColumn("Advertising.Ad", "TargetURL", c => c.String(maxLength: 512, unicode: false));
            AlterColumn("Ordering.SalesOrderEvent", "NewBalanceDue", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Ordering.SalesOrderEvent", "OldBalanceDue", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Products.ProductAssociation", "UnitOfMeasure", c => c.String());
            AlterColumn("CalendarEvents.CalendarEventDetail", "Location", c => c.String());
            AlterColumn("CalendarEvents.CalendarEvent", "RecurrenceString", c => c.String());
            AlterColumn("CalendarEvents.CalendarEvent", "EventDurationUnitOfMeasure", c => c.String());
            AlterColumn("CalendarEvents.CalendarEvent", "ShortDescription", c => c.String(unicode: false));
            AlterColumn("Payments.SubscriptionHistory", "Memo", c => c.String(nullable: false));
            AlterColumn("Payments.Subscription", "FilterKey3", c => c.String());
            AlterColumn("Payments.Subscription", "FilterKey2", c => c.String());
            AlterColumn("Payments.Subscription", "FilterKey1", c => c.String());
            AlterColumn("Payments.Subscription", "CreditUponUpgrade", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Payments.Subscription", "Memo", c => c.String());
            AlterColumn("Payments.Payment", "Last4CardDigits", c => c.String(maxLength: 100));
            AlterColumn("Payments.Payment", "Amount", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.StoreProduct", "PriceSale", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.StoreProduct", "PriceReduction", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.StoreProduct", "PriceMsrp", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.StoreProduct", "PriceBase", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Media.StoredFile", "FileName", c => c.String());
            AlterColumn("Media.StoredFile", "FileFormat", c => c.String());
            AlterColumn("Media.StoredFile", "Copyright", c => c.String());
            AlterColumn("Media.StoredFile", "Author", c => c.String());
            AlterColumn("Media.StoredFile", "SeoTitle", c => c.String());
            AlterColumn("Media.StoredFile", "DisplayName", c => c.String());
            AlterColumn("Discounts.CartItemDiscounts", "DiscountTotal", c => c.Decimal(nullable: false, precision: 18, scale: 4));
            AlterColumn("Stores.SocialProvider", "UrlFormat", c => c.String());
            AlterColumn("Stores.SocialProvider", "Url", c => c.String());
            AlterColumn("Stores.SiteDomainSocialProvider", "UrlValues", c => c.String());
            AlterColumn("Stores.SiteDomain", "Url", c => c.String(maxLength: 512, unicode: false));
            AlterColumn("Stores.Store", "OperatingHoursSundayEnd", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.Store", "OperatingHoursSundayStart", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.Store", "OperatingHoursSaturdayEnd", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.Store", "OperatingHoursSaturdayStart", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.Store", "OperatingHoursFridayEnd", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.Store", "OperatingHoursFridayStart", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.Store", "OperatingHoursThursdayEnd", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.Store", "OperatingHoursThursdayStart", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.Store", "OperatingHoursWednesdayEnd", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.Store", "OperatingHoursWednesdayStart", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.Store", "OperatingHoursTuesdayEnd", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.Store", "OperatingHoursTuesdayStart", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.Store", "OperatingHoursMondayEnd", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Stores.Store", "OperatingHoursMondayStart", c => c.Decimal(precision: 18, scale: 2));
            AlterColumn("Accounts.Account", "TaxEntityUseCode", c => c.String());
            AlterColumn("Accounts.Account", "TaxExemptionNo", c => c.String());
            AlterColumn("Accounts.Account", "IsTaxable", c => c.Boolean());
            DropColumn("Discounts.DiscountCode", "UserID");
            DropColumn("Payments.Payment", "BankName");
            DropColumn("Payments.Payment", "AccountNumberLast4");
            DropColumn("Payments.Payment", "RoutingNumberLast4");
            DropColumn("Payments.Payment", "CheckNumber");
            DropColumn("Messaging.EmailQueueAttachment", "SortOrder");
            DropColumn("Messaging.EmailQueueAttachment", "FileAccessTypeID");
            DropColumn("Messaging.EmailQueueAttachment", "SeoMetaData");
            DropColumn("Messaging.EmailQueueAttachment", "SeoDescription");
            DropColumn("Messaging.EmailQueueAttachment", "SeoPageTitle");
            DropColumn("Messaging.EmailQueueAttachment", "SeoKeywords");
            DropColumn("Messaging.EmailQueueAttachment", "SeoUrl");
            DropTable("Accounts.AccountAssociationType");
            DropTable("Accounts.AccountAssociation");
            RenameIndex(table: "Hangfire.ScheduledJobConfigurationSetting", name: "IX_SlaveID", newName: "IX_SettingID");
            RenameIndex(table: "Hangfire.ScheduledJobConfigurationSetting", name: "IX_MasterID", newName: "IX_ScheduledJobConfigurationID");
            RenameIndex(table: "Pricing.PriceRuleVendor", name: "IX_SlaveID", newName: "IX_VendorID");
            RenameIndex(table: "Pricing.PriceRuleVendor", name: "IX_MasterID", newName: "IX_PriceRuleID");
            RenameIndex(table: "Pricing.PriceRuleStore", name: "IX_SlaveID", newName: "IX_StoreID");
            RenameIndex(table: "Pricing.PriceRuleStore", name: "IX_MasterID", newName: "IX_PriceRuleID");
            RenameIndex(table: "Pricing.PriceRuleProductType", name: "IX_SlaveID", newName: "IX_ProductTypeID");
            RenameIndex(table: "Pricing.PriceRuleProductType", name: "IX_MasterID", newName: "IX_PriceRuleID");
            RenameIndex(table: "Pricing.PriceRuleProduct", name: "IX_SlaveID", newName: "IX_ProductID");
            RenameIndex(table: "Pricing.PriceRuleProduct", name: "IX_MasterID", newName: "IX_PriceRuleID");
            RenameIndex(table: "Pricing.PriceRuleManufacturer", name: "IX_SlaveID", newName: "IX_ManufacturerID");
            RenameIndex(table: "Pricing.PriceRuleManufacturer", name: "IX_MasterID", newName: "IX_PriceRuleID");
            RenameIndex(table: "Pricing.PriceRuleCountry", name: "IX_SlaveID", newName: "IX_CountryID");
            RenameIndex(table: "Pricing.PriceRuleCountry", name: "IX_MasterID", newName: "IX_PriceRuleID");
            RenameIndex(table: "Pricing.PriceRuleCategory", name: "IX_SlaveID", newName: "IX_CategoryID");
            RenameIndex(table: "Pricing.PriceRuleCategory", name: "IX_MasterID", newName: "IX_PriceRuleID");
            RenameIndex(table: "Pricing.PriceRuleAccountType", name: "IX_SlaveID", newName: "IX_AccountTypeID");
            RenameIndex(table: "Pricing.PriceRuleAccountType", name: "IX_MasterID", newName: "IX_PriceRuleID");
            RenameIndex(table: "Pricing.PriceRuleAccount", name: "IX_SlaveID", newName: "IX_AccountID");
            RenameIndex(table: "Pricing.PriceRuleAccount", name: "IX_MasterID", newName: "IX_PriceRuleID");
            RenameIndex(table: "Favorites.FavoriteShipCarrier", name: "IX_SlaveID", newName: "IX_FavoriteID");
            RenameIndex(table: "Favorites.FavoriteShipCarrier", name: "IX_MasterID", newName: "IX_UserID");
            RenameIndex(table: "Tracking.PageViewEvent", name: "IX_SlaveID", newName: "IX_EventID");
            RenameIndex(table: "Tracking.PageViewEvent", name: "IX_MasterID", newName: "IX_PageViewID");
            RenameIndex(table: "Advertising.AdStore", name: "IX_SlaveID", newName: "IX_StoreID");
            RenameIndex(table: "Advertising.AdStore", name: "IX_MasterID", newName: "IX_AdID");
            RenameIndex(table: "Tracking.CampaignAd", name: "IX_SlaveID", newName: "IX_AdID");
            RenameIndex(table: "Tracking.CampaignAd", name: "IX_MasterID", newName: "IX_CampaignID");
            RenameIndex(table: "Advertising.AdZone", name: "IX_SlaveID", newName: "IX_ZoneID");
            RenameIndex(table: "Advertising.AdZone", name: "IX_MasterID", newName: "IX_AdID");
            RenameIndex(table: "Advertising.AdAccount", name: "IX_SlaveID", newName: "IX_AccountID");
            RenameIndex(table: "Advertising.AdAccount", name: "IX_MasterID", newName: "IX_AdID");
            RenameIndex(table: "Accounts.AccountPricePoint", name: "IX_SlaveID", newName: "IX_PricePointID");
            RenameIndex(table: "Accounts.AccountPricePoint", name: "IX_MasterID", newName: "IX_AccountID");
            RenameIndex(table: "Discounts.PurchaseOrderDiscounts", name: "IX_SlaveID", newName: "IX_DiscountID");
            RenameIndex(table: "Purchasing.PurchaseOrderContact", name: "IX_SlaveID", newName: "IX_ContactID");
            RenameIndex(table: "Purchasing.PurchaseOrderContact", name: "IX_MasterID", newName: "IX_PurchaseOrderID");
            RenameIndex(table: "Payments.SalesOrderPayment", name: "IX_SlaveID", newName: "IX_PaymentID");
            RenameIndex(table: "Payments.SalesOrderPayment", name: "IX_MasterID", newName: "IX_SalesOrderID");
            RenameIndex(table: "Discounts.SalesOrderDiscounts", name: "IX_SlaveID", newName: "IX_DiscountID");
            RenameIndex(table: "Ordering.SalesOrderContact", name: "IX_SlaveID", newName: "IX_ContactID");
            RenameIndex(table: "Ordering.SalesOrderContact", name: "IX_MasterID", newName: "IX_SalesOrderID");
            RenameIndex(table: "Payments.SalesInvoicePayment", name: "IX_SlaveID", newName: "IX_PaymentID");
            RenameIndex(table: "Payments.SalesInvoicePayment", name: "IX_MasterID", newName: "IX_SalesInvoiceID");
            RenameIndex(table: "Discounts.DiscountStores", name: "IX_SlaveID", newName: "IX_StoreID");
            RenameIndex(table: "Discounts.DiscountStores", name: "IX_MasterID", newName: "IX_DiscountID");
            RenameIndex(table: "Discounts.DiscountShipCarrierMethods", name: "IX_SlaveID", newName: "IX_ShipCarrierMethodID");
            RenameIndex(table: "Discounts.DiscountShipCarrierMethods", name: "IX_MasterID", newName: "IX_DiscountID");
            RenameIndex(table: "Discounts.DiscountProductType", name: "IX_SlaveID", newName: "IX_ProductTypeID");
            RenameIndex(table: "Discounts.DiscountProductType", name: "IX_MasterID", newName: "IX_DiscountID");
            RenameIndex(table: "Products.ProductPricePoint", name: "IX_SlaveID", newName: "IX_PricePointID");
            RenameIndex(table: "Products.ProductPricePoint", name: "IX_MasterID", newName: "IX_ProductID");
            RenameIndex(table: "Products.ProductCategory", name: "IX_SlaveID", newName: "IX_CategoryID");
            RenameIndex(table: "Products.ProductCategory", name: "IX_MasterID", newName: "IX_ProductID");
            RenameIndex(table: "Products.ProductAssociation", name: "IX_SlaveID", newName: "IX_AssociatedProductID");
            RenameIndex(table: "Products.ProductAssociation", name: "IX_MasterID", newName: "IX_PrimaryProductID");
            RenameIndex(table: "Discounts.DiscountProducts", name: "IX_SlaveID", newName: "IX_ProductID");
            RenameIndex(table: "Discounts.DiscountProducts", name: "IX_MasterID", newName: "IX_DiscountID");
            RenameIndex(table: "Discounts.SalesOrderItemDiscounts", name: "IX_SlaveID", newName: "IX_DiscountID");
            RenameIndex(table: "Discounts.SalesInvoiceItemDiscounts", name: "IX_SlaveID", newName: "IX_DiscountID");
            RenameIndex(table: "Discounts.PurchaseOrderItemDiscounts", name: "IX_SlaveID", newName: "IX_DiscountID");
            RenameIndex(table: "CalendarEvents.CalendarEventProducts", name: "IX_SlaveID", newName: "IX_ProductID");
            RenameIndex(table: "CalendarEvents.CalendarEventProducts", name: "IX_MasterID", newName: "IX_CalendarEventID");
            RenameIndex(table: "CalendarEvents.UserEventAttendance", name: "IX_SlaveID", newName: "IX_UserID");
            RenameIndex(table: "CalendarEvents.UserEventAttendance", name: "IX_MasterID", newName: "IX_CalendarEventID");
            RenameIndex(table: "Quoting.SalesQuoteCategory", name: "IX_SlaveID", newName: "IX_CategoryID");
            RenameIndex(table: "Quoting.SalesQuoteCategory", name: "IX_MasterID", newName: "IX_SalesQuoteID");
            RenameIndex(table: "Discounts.SalesQuoteItemDiscounts", name: "IX_SlaveID", newName: "IX_DiscountID");
            RenameIndex(table: "Discounts.SampleRequestItemDiscounts", name: "IX_SlaveID", newName: "IX_DiscountID");
            RenameIndex(table: "Discounts.SampleRequestDiscounts", name: "IX_SlaveID", newName: "IX_DiscountID");
            RenameIndex(table: "Sampling.SampleRequestContact", name: "IX_SlaveID", newName: "IX_ContactID");
            RenameIndex(table: "Sampling.SampleRequestContact", name: "IX_MasterID", newName: "IX_SampleRequestID");
            RenameIndex(table: "Payments.SalesReturnPayment", name: "IX_SlaveID", newName: "IX_PaymentID");
            RenameIndex(table: "Payments.SalesReturnPayment", name: "IX_MasterID", newName: "IX_SalesReturnID");
            RenameIndex(table: "Discounts.SalesReturnItemDiscounts", name: "IX_SlaveID", newName: "IX_DiscountID");
            RenameIndex(table: "Discounts.SalesReturnDiscounts", name: "IX_SlaveID", newName: "IX_DiscountID");
            RenameIndex(table: "Returning.SalesReturnContact", name: "IX_SlaveID", newName: "IX_ContactID");
            RenameIndex(table: "Returning.SalesReturnContact", name: "IX_MasterID", newName: "IX_SalesReturnID");
            RenameIndex(table: "Returning.SalesReturnSalesOrder", name: "IX_SlaveID", newName: "IX_SalesOrderID");
            RenameIndex(table: "Returning.SalesReturnSalesOrder", name: "IX_MasterID", newName: "IX_SalesReturnID");
            RenameIndex(table: "Discounts.SalesQuoteDiscounts", name: "IX_SlaveID", newName: "IX_DiscountID");
            RenameIndex(table: "Quoting.SalesQuoteContact", name: "IX_SlaveID", newName: "IX_ContactID");
            RenameIndex(table: "Quoting.SalesQuoteContact", name: "IX_MasterID", newName: "IX_SalesQuoteID");
            RenameIndex(table: "Quoting.SalesQuoteSalesOrder", name: "IX_SlaveID", newName: "IX_SalesOrderID");
            RenameIndex(table: "Quoting.SalesQuoteSalesOrder", name: "IX_MasterID", newName: "IX_SalesQuoteID");
            RenameIndex(table: "Favorites.FavoriteVendor", name: "IX_SlaveID", newName: "IX_FavoriteID");
            RenameIndex(table: "Favorites.FavoriteVendor", name: "IX_MasterID", newName: "IX_UserID");
            RenameIndex(table: "Favorites.FavoriteStore", name: "IX_SlaveID", newName: "IX_FavoriteID");
            RenameIndex(table: "Favorites.FavoriteStore", name: "IX_MasterID", newName: "IX_UserID");
            RenameIndex(table: "Favorites.FavoriteManufacturer", name: "IX_SlaveID", newName: "IX_FavoriteID");
            RenameIndex(table: "Favorites.FavoriteManufacturer", name: "IX_MasterID", newName: "IX_UserID");
            RenameIndex(table: "Favorites.FavoriteCategory", name: "IX_SlaveID", newName: "IX_FavoriteID");
            RenameIndex(table: "Favorites.FavoriteCategory", name: "IX_MasterID", newName: "IX_UserID");
            RenameIndex(table: "Stores.StoreUserType", name: "IX_SlaveID", newName: "IX_UserTypeID");
            RenameIndex(table: "Stores.StoreUserType", name: "IX_MasterID", newName: "IX_StoreID");
            RenameIndex(table: "Stores.StoreUser", name: "IX_SlaveID", newName: "IX_UserID");
            RenameIndex(table: "Stores.StoreUser", name: "IX_MasterID", newName: "IX_StoreID");
            RenameIndex(table: "Products.ProductSubscriptionType", name: "IX_SlaveID", newName: "IX_SubscriptionTypeID");
            RenameIndex(table: "Products.ProductSubscriptionType", name: "IX_MasterID", newName: "IX_ProductID");
            RenameIndex(table: "Payments.SubscriptionHistory", name: "IX_SlaveID", newName: "IX_PaymentID");
            RenameIndex(table: "Payments.SubscriptionHistory", name: "IX_MasterID", newName: "IX_SubscriptionID");
            RenameIndex(table: "Stores.StoreSubscription", name: "IX_SlaveID", newName: "IX_SubscriptionID");
            RenameIndex(table: "Stores.StoreSubscription", name: "IX_MasterID", newName: "IX_StoreID");
            RenameIndex(table: "Stores.StoreProduct", name: "IX_SlaveID", newName: "IX_ProductID");
            RenameIndex(table: "Stores.StoreProduct", name: "IX_MasterID", newName: "IX_StoreID");
            RenameIndex(table: "Stores.StoreContact", name: "IX_SlaveID", newName: "IX_ContactID");
            RenameIndex(table: "Stores.StoreContact", name: "IX_MasterID", newName: "IX_StoreID");
            RenameIndex(table: "Stores.StoreCategoryType", name: "IX_SlaveID", newName: "IX_CategoryTypeID");
            RenameIndex(table: "Stores.StoreCategoryType", name: "IX_MasterID", newName: "IX_StoreID");
            RenameIndex(table: "Stores.StoreCategory", name: "IX_SlaveID", newName: "IX_CategoryID");
            RenameIndex(table: "Stores.StoreCategory", name: "IX_MasterID", newName: "IX_StoreID");
            RenameIndex(table: "Stores.StoreBadge", name: "IX_SlaveID", newName: "IX_BadgeID");
            RenameIndex(table: "Stores.StoreBadge", name: "IX_MasterID", newName: "IX_StoreID");
            RenameIndex(table: "Stores.StoreAccount", name: "IX_SlaveID", newName: "IX_AccountID");
            RenameIndex(table: "Stores.StoreAccount", name: "IX_MasterID", newName: "IX_StoreID");
            RenameIndex(table: "Vendors.VendorProduct", name: "IX_SlaveID", newName: "IX_ProductID");
            RenameIndex(table: "Vendors.VendorProduct", name: "IX_MasterID", newName: "IX_VendorID");
            RenameIndex(table: "Stores.StoreVendor", name: "IX_SlaveID", newName: "IX_VendorID");
            RenameIndex(table: "Stores.StoreVendor", name: "IX_MasterID", newName: "IX_StoreID");
            RenameIndex(table: "Products.ProductInventoryLocationSection", name: "IX_SlaveID", newName: "IX_InventoryLocationSectionID");
            RenameIndex(table: "Products.ProductInventoryLocationSection", name: "IX_MasterID", newName: "IX_ProductID");
            RenameIndex(table: "Stores.StoreInventoryLocation", name: "IX_SlaveID", newName: "IX_InventoryLocationID");
            RenameIndex(table: "Stores.StoreInventoryLocation", name: "IX_MasterID", newName: "IX_StoreID");
            RenameIndex(table: "Vendors.VendorManufacturer", name: "IX_SlaveID", newName: "IX_ManufacturerID");
            RenameIndex(table: "Vendors.VendorManufacturer", name: "IX_MasterID", newName: "IX_VendorID");
            RenameIndex(table: "Stores.StoreManufacturer", name: "IX_SlaveID", newName: "IX_ManufacturerID");
            RenameIndex(table: "Stores.StoreManufacturer", name: "IX_MasterID", newName: "IX_StoreID");
            RenameIndex(table: "Manufacturers.ManufacturerProduct", name: "IX_SlaveID", newName: "IX_ProductID");
            RenameIndex(table: "Manufacturers.ManufacturerProduct", name: "IX_MasterID", newName: "IX_ManufacturerID");
            RenameIndex(table: "Stores.StoreSiteDomain", name: "IX_SlaveID", newName: "IX_SiteDomainID");
            RenameIndex(table: "Stores.StoreSiteDomain", name: "IX_MasterID", newName: "IX_StoreID");
            RenameIndex(table: "Stores.SiteDomainSocialProvider", name: "IX_SlaveID", newName: "IX_SocialProviderID");
            RenameIndex(table: "Stores.SiteDomainSocialProvider", name: "IX_MasterID", newName: "IX_SiteDomainID");
            RenameIndex(table: "Stores.BrandSiteDomain", name: "IX_SlaveID", newName: "IX_SiteDomainID");
            RenameIndex(table: "Stores.BrandSiteDomain", name: "IX_MasterID", newName: "IX_BrandID");
            RenameIndex(table: "Stores.BrandStore", name: "IX_SlaveID", newName: "IX_StoreID");
            RenameIndex(table: "Stores.BrandStore", name: "IX_MasterID", newName: "IX_BrandID");
            RenameIndex(table: "Groups.GroupUser", name: "IX_SlaveID", newName: "IX_UserID");
            RenameIndex(table: "Groups.GroupUser", name: "IX_MasterID", newName: "IX_GroupID");
            RenameIndex(table: "Messaging.EmailQueueAttachment", name: "IX_SlaveID", newName: "IX_StoredFileID");
            RenameIndex(table: "Messaging.EmailQueueAttachment", name: "IX_MasterID", newName: "IX_EmailQueueID");
            RenameIndex(table: "Messaging.MessageRecipient", name: "IX_SlaveID", newName: "IX_ToUserID");
            RenameIndex(table: "Messaging.MessageRecipient", name: "IX_MasterID", newName: "IX_MessageID");
            RenameIndex(table: "Messaging.MessageAttachment", name: "IX_SlaveID", newName: "IX_StoredFileID");
            RenameIndex(table: "Messaging.MessageAttachment", name: "IX_MasterID", newName: "IX_MessageID");
            RenameIndex(table: "Messaging.ConversationUser", name: "IX_SlaveID", newName: "IX_UserID");
            RenameIndex(table: "Messaging.ConversationUser", name: "IX_MasterID", newName: "IX_ConversationID");
            RenameIndex(table: "Discounts.CartDiscounts", name: "IX_SlaveID", newName: "IX_DiscountID");
            RenameIndex(table: "Shopping.CartContact", name: "IX_SlaveID", newName: "IX_ContactID");
            RenameIndex(table: "Shopping.CartContact", name: "IX_MasterID", newName: "IX_CartID");
            RenameIndex(table: "Discounts.CartItemDiscounts", name: "IX_SlaveID", newName: "IX_DiscountID");
            RenameIndex(table: "Discounts.DiscountCategories", name: "IX_SlaveID", newName: "IX_CategoryID");
            RenameIndex(table: "Discounts.DiscountCategories", name: "IX_MasterID", newName: "IX_DiscountID");
            RenameIndex(table: "Discounts.SalesInvoiceDiscounts", name: "IX_SlaveID", newName: "IX_DiscountID");
            RenameIndex(table: "Invoicing.SalesInvoiceContact", name: "IX_SlaveID", newName: "IX_ContactID");
            RenameIndex(table: "Invoicing.SalesInvoiceContact", name: "IX_MasterID", newName: "IX_SalesInvoiceID");
            RenameIndex(table: "Invoicing.SalesOrderSalesInvoice", name: "IX_SlaveID", newName: "IX_SalesInvoiceID");
            RenameIndex(table: "Invoicing.SalesOrderSalesInvoice", name: "IX_MasterID", newName: "IX_SalesOrderID");
            RenameIndex(table: "Purchasing.SalesOrderPurchaseOrder", name: "IX_SlaveID", newName: "IX_PurchaseOrderID");
            RenameIndex(table: "Purchasing.SalesOrderPurchaseOrder", name: "IX_MasterID", newName: "IX_SalesOrderID");
            RenameIndex(table: "Geography.RegionLanguage", name: "IX_SlaveID", newName: "IX_LanguageID");
            RenameIndex(table: "Geography.DistrictLanguage", name: "IX_SlaveID", newName: "IX_LanguageID");
            RenameIndex(table: "Geography.DistrictCurrency", name: "IX_SlaveID", newName: "IX_CurrencyID");
            RenameIndex(table: "Geography.RegionCurrency", name: "IX_SlaveID", newName: "IX_CurrencyID");
            RenameIndex(table: "Geography.CountryLanguage", name: "IX_SlaveID", newName: "IX_LanguageID");
            RenameIndex(table: "Geography.CountryCurrency", name: "IX_SlaveID", newName: "IX_CurrencyID");
            RenameIndex(table: "Accounts.AccountContact", name: "IX_SlaveID", newName: "IX_ContactID");
            RenameIndex(table: "Accounts.AccountContact", name: "IX_MasterID", newName: "IX_AccountID");
            RenameColumn(table: "Hangfire.ScheduledJobConfigurationSetting", name: "SlaveID", newName: "SettingID");
            RenameColumn(table: "Pricing.PriceRuleVendor", name: "SlaveID", newName: "VendorID");
            RenameColumn(table: "Pricing.PriceRuleStore", name: "SlaveID", newName: "StoreID");
            RenameColumn(table: "Pricing.PriceRuleProductType", name: "SlaveID", newName: "ProductTypeID");
            RenameColumn(table: "Pricing.PriceRuleProduct", name: "SlaveID", newName: "ProductID");
            RenameColumn(table: "Pricing.PriceRuleManufacturer", name: "SlaveID", newName: "ManufacturerID");
            RenameColumn(table: "Pricing.PriceRuleCountry", name: "SlaveID", newName: "CountryID");
            RenameColumn(table: "Pricing.PriceRuleCategory", name: "SlaveID", newName: "CategoryID");
            RenameColumn(table: "Pricing.PriceRuleAccountType", name: "SlaveID", newName: "AccountTypeID");
            RenameColumn(table: "Pricing.PriceRuleAccount", name: "SlaveID", newName: "AccountID");
            RenameColumn(table: "Favorites.FavoriteShipCarrier", name: "MasterID", newName: "UserID");
            RenameColumn(table: "Favorites.FavoriteShipCarrier", name: "SlaveID", newName: "FavoriteID");
            RenameColumn(table: "Advertising.AdStore", name: "SlaveID", newName: "StoreID");
            RenameColumn(table: "Advertising.AdStore", name: "MasterID", newName: "AdID");
            RenameColumn(table: "Advertising.AdAccount", name: "SlaveID", newName: "AccountID");
            RenameColumn(table: "Accounts.AccountContact", name: "SlaveID", newName: "ContactID");
            RenameColumn(table: "Accounts.AccountPricePoint", name: "SlaveID", newName: "PricePointID");
            RenameColumn(table: "Stores.StoreContact", name: "SlaveID", newName: "ContactID");
            RenameColumn(table: "Stores.StoreBadge", name: "SlaveID", newName: "BadgeID");
            RenameColumn(table: "Discounts.PurchaseOrderDiscounts", name: "SlaveID", newName: "DiscountID");
            RenameColumn(table: "Purchasing.PurchaseOrderContact", name: "SlaveID", newName: "ContactID");
            RenameColumn(table: "Payments.SalesOrderPayment", name: "SlaveID", newName: "PaymentID");
            RenameColumn(table: "Discounts.SalesOrderDiscounts", name: "SlaveID", newName: "DiscountID");
            RenameColumn(table: "Ordering.SalesOrderContact", name: "SlaveID", newName: "ContactID");
            RenameColumn(table: "Payments.SalesInvoicePayment", name: "SlaveID", newName: "PaymentID");
            RenameColumn(table: "Discounts.SalesInvoiceDiscounts", name: "SlaveID", newName: "DiscountID");
            RenameColumn(table: "Discounts.DiscountStores", name: "SlaveID", newName: "StoreID");
            RenameColumn(table: "Discounts.DiscountShipCarrierMethods", name: "SlaveID", newName: "ShipCarrierMethodID");
            RenameColumn(table: "Discounts.DiscountProductType", name: "SlaveID", newName: "ProductTypeID");
            RenameColumn(table: "Discounts.DiscountCategories", name: "SlaveID", newName: "CategoryID");
            RenameColumn(table: "Products.ProductPricePoint", name: "SlaveID", newName: "PricePointID");
            RenameColumn(table: "Discounts.SalesOrderItemDiscounts", name: "SlaveID", newName: "DiscountID");
            RenameColumn(table: "Discounts.SalesInvoiceItemDiscounts", name: "SlaveID", newName: "DiscountID");
            RenameColumn(table: "Discounts.PurchaseOrderItemDiscounts", name: "SlaveID", newName: "DiscountID");
            RenameColumn(table: "CalendarEvents.CalendarEventProducts", name: "SlaveID", newName: "ProductID");
            RenameColumn(table: "Payments.SubscriptionHistory", name: "SlaveID", newName: "PaymentID");
            RenameColumn(table: "Quoting.SalesQuoteCategory", name: "SlaveID", newName: "CategoryID");
            RenameColumn(table: "Discounts.SalesQuoteItemDiscounts", name: "SlaveID", newName: "DiscountID");
            RenameColumn(table: "Discounts.SampleRequestItemDiscounts", name: "SlaveID", newName: "DiscountID");
            RenameColumn(table: "Discounts.SampleRequestDiscounts", name: "SlaveID", newName: "DiscountID");
            RenameColumn(table: "Sampling.SampleRequestContact", name: "SlaveID", newName: "ContactID");
            RenameColumn(table: "Payments.SalesReturnPayment", name: "SlaveID", newName: "PaymentID");
            RenameColumn(table: "Discounts.SalesReturnItemDiscounts", name: "SlaveID", newName: "DiscountID");
            RenameColumn(table: "Discounts.SalesReturnDiscounts", name: "SlaveID", newName: "DiscountID");
            RenameColumn(table: "Returning.SalesReturnContact", name: "SlaveID", newName: "ContactID");
            RenameColumn(table: "Discounts.SalesQuoteDiscounts", name: "SlaveID", newName: "DiscountID");
            RenameColumn(table: "Quoting.SalesQuoteContact", name: "SlaveID", newName: "ContactID");
            RenameColumn(table: "Favorites.FavoriteVendor", name: "SlaveID", newName: "FavoriteID");
            RenameColumn(table: "Favorites.FavoriteStore", name: "SlaveID", newName: "FavoriteID");
            RenameColumn(table: "Favorites.FavoriteManufacturer", name: "SlaveID", newName: "FavoriteID");
            RenameColumn(table: "Favorites.FavoriteCategory", name: "SlaveID", newName: "FavoriteID");
            RenameColumn(table: "Groups.GroupUser", name: "SlaveID", newName: "UserID");
            RenameColumn(table: "Messaging.EmailQueueAttachment", name: "SlaveID", newName: "StoredFileID");
            RenameColumn(table: "Messaging.MessageAttachment", name: "SlaveID", newName: "StoredFileID");
            RenameColumn(table: "Discounts.CartDiscounts", name: "SlaveID", newName: "DiscountID");
            RenameColumn(table: "Shopping.CartContact", name: "SlaveID", newName: "ContactID");
            RenameColumn(table: "Discounts.CartItemDiscounts", name: "SlaveID", newName: "DiscountID");
            RenameColumn(table: "Invoicing.SalesInvoiceContact", name: "SlaveID", newName: "ContactID");
            RenameColumn(table: "Geography.RegionLanguage", name: "SlaveID", newName: "LanguageID");
            RenameColumn(table: "Geography.DistrictLanguage", name: "SlaveID", newName: "LanguageID");
            RenameColumn(table: "Geography.DistrictCurrency", name: "SlaveID", newName: "CurrencyID");
            RenameColumn(table: "Geography.RegionCurrency", name: "SlaveID", newName: "CurrencyID");
            RenameColumn(table: "Geography.CountryLanguage", name: "SlaveID", newName: "LanguageID");
            RenameColumn(table: "Geography.CountryCurrency", name: "SlaveID", newName: "CurrencyID");
            RenameColumn(table: "Hangfire.ScheduledJobConfigurationSetting", name: "MasterID", newName: "ScheduledJobConfigurationID");
            RenameColumn(table: "Pricing.PriceRuleVendor", name: "MasterID", newName: "PriceRuleID");
            RenameColumn(table: "Pricing.PriceRuleStore", name: "MasterID", newName: "PriceRuleID");
            RenameColumn(table: "Pricing.PriceRuleProductType", name: "MasterID", newName: "PriceRuleID");
            RenameColumn(table: "Pricing.PriceRuleProduct", name: "MasterID", newName: "PriceRuleID");
            RenameColumn(table: "Pricing.PriceRuleManufacturer", name: "MasterID", newName: "PriceRuleID");
            RenameColumn(table: "Pricing.PriceRuleCountry", name: "MasterID", newName: "PriceRuleID");
            RenameColumn(table: "Pricing.PriceRuleCategory", name: "MasterID", newName: "PriceRuleID");
            RenameColumn(table: "Pricing.PriceRuleAccountType", name: "MasterID", newName: "PriceRuleID");
            RenameColumn(table: "Pricing.PriceRuleAccount", name: "MasterID", newName: "PriceRuleID");
            RenameColumn(table: "Tracking.PageViewEvent", name: "MasterID", newName: "PageViewID");
            RenameColumn(table: "Tracking.PageViewEvent", name: "SlaveID", newName: "EventID");
            RenameColumn(table: "Tracking.CampaignAd", name: "MasterID", newName: "CampaignID");
            RenameColumn(table: "Advertising.AdZone", name: "SlaveID", newName: "ZoneID");
            RenameColumn(table: "Tracking.CampaignAd", name: "SlaveID", newName: "AdID");
            RenameColumn(table: "Advertising.AdZone", name: "MasterID", newName: "AdID");
            RenameColumn(table: "Advertising.AdAccount", name: "MasterID", newName: "AdID");
            RenameColumn(table: "Stores.StoreCategoryType", name: "SlaveID", newName: "CategoryTypeID");
            RenameColumn(table: "CalendarEvents.UserEventAttendance", name: "MasterID", newName: "CalendarEventID");
            RenameColumn(table: "CalendarEvents.CalendarEventProducts", name: "MasterID", newName: "CalendarEventID");
            RenameColumn(table: "Stores.StoreUserType", name: "SlaveID", newName: "UserTypeID");
            RenameColumn(table: "Products.ProductSubscriptionType", name: "SlaveID", newName: "SubscriptionTypeID");
            RenameColumn(table: "Payments.SubscriptionHistory", name: "MasterID", newName: "SubscriptionID");
            RenameColumn(table: "Stores.StoreSubscription", name: "SlaveID", newName: "SubscriptionID");
            RenameColumn(table: "Sampling.SampleRequestContact", name: "MasterID", newName: "SampleRequestID");
            RenameColumn(table: "Payments.SalesReturnPayment", name: "MasterID", newName: "SalesReturnID");
            RenameColumn(table: "Returning.SalesReturnContact", name: "MasterID", newName: "SalesReturnID");
            RenameColumn(table: "Returning.SalesReturnSalesOrder", name: "MasterID", newName: "SalesReturnID");
            RenameColumn(table: "Quoting.SalesQuoteCategory", name: "MasterID", newName: "SalesQuoteID");
            RenameColumn(table: "Quoting.SalesQuoteContact", name: "MasterID", newName: "SalesQuoteID");
            RenameColumn(table: "Quoting.SalesQuoteSalesOrder", name: "MasterID", newName: "SalesQuoteID");
            RenameColumn(table: "Stores.StoreInventoryLocation", name: "SlaveID", newName: "InventoryLocationID");
            RenameColumn(table: "Products.ProductInventoryLocationSection", name: "SlaveID", newName: "InventoryLocationSectionID");
            RenameColumn(table: "Vendors.VendorProduct", name: "MasterID", newName: "VendorID");
            RenameColumn(table: "Vendors.VendorManufacturer", name: "MasterID", newName: "VendorID");
            RenameColumn(table: "Stores.StoreVendor", name: "SlaveID", newName: "VendorID");
            RenameColumn(table: "Vendors.VendorManufacturer", name: "SlaveID", newName: "ManufacturerID");
            RenameColumn(table: "Stores.StoreManufacturer", name: "SlaveID", newName: "ManufacturerID");
            RenameColumn(table: "Manufacturers.ManufacturerProduct", name: "MasterID", newName: "ManufacturerID");
            RenameColumn(table: "Groups.GroupUser", name: "MasterID", newName: "GroupID");
            RenameColumn(table: "Messaging.EmailQueueAttachment", name: "MasterID", newName: "EmailQueueID");
            RenameColumn(table: "Messaging.MessageRecipient", name: "MasterID", newName: "MessageID");
            RenameColumn(table: "Messaging.MessageAttachment", name: "MasterID", newName: "MessageID");
            RenameColumn(table: "Messaging.ConversationUser", name: "MasterID", newName: "ConversationID");
            RenameColumn(table: "CalendarEvents.UserEventAttendance", name: "SlaveID", newName: "UserID");
            RenameColumn(table: "Stores.StoreUser", name: "SlaveID", newName: "UserID");
            RenameColumn(table: "Messaging.MessageRecipient", name: "SlaveID", newName: "ToUserID");
            RenameColumn(table: "Favorites.FavoriteVendor", name: "MasterID", newName: "UserID");
            RenameColumn(table: "Favorites.FavoriteStore", name: "MasterID", newName: "UserID");
            RenameColumn(table: "Favorites.FavoriteManufacturer", name: "MasterID", newName: "UserID");
            RenameColumn(table: "Favorites.FavoriteCategory", name: "MasterID", newName: "UserID");
            RenameColumn(table: "Messaging.ConversationUser", name: "SlaveID", newName: "UserID");
            RenameColumn(table: "Shopping.CartContact", name: "MasterID", newName: "CartID");
            RenameColumn(table: "Vendors.VendorProduct", name: "SlaveID", newName: "ProductID");
            RenameColumn(table: "Stores.StoreProduct", name: "SlaveID", newName: "ProductID");
            RenameColumn(table: "Products.ProductSubscriptionType", name: "MasterID", newName: "ProductID");
            RenameColumn(table: "Products.ProductAssociation", name: "SlaveID", newName: "AssociatedProductID");
            RenameColumn(table: "Products.ProductPricePoint", name: "MasterID", newName: "ProductID");
            RenameColumn(table: "Products.ProductInventoryLocationSection", name: "MasterID", newName: "ProductID");
            RenameColumn(table: "Products.ProductCategory", name: "MasterID", newName: "ProductID");
            RenameColumn(table: "Products.ProductAssociation", name: "MasterID", newName: "PrimaryProductID");
            RenameColumn(table: "Manufacturers.ManufacturerProduct", name: "SlaveID", newName: "ProductID");
            RenameColumn(table: "Discounts.DiscountProducts", name: "SlaveID", newName: "ProductID");
            RenameColumn(table: "Stores.StoreCategory", name: "SlaveID", newName: "CategoryID");
            RenameColumn(table: "Products.ProductCategory", name: "SlaveID", newName: "CategoryID");
            RenameColumn(table: "Discounts.DiscountStores", name: "MasterID", newName: "DiscountID");
            RenameColumn(table: "Discounts.DiscountShipCarrierMethods", name: "MasterID", newName: "DiscountID");
            RenameColumn(table: "Discounts.DiscountProductType", name: "MasterID", newName: "DiscountID");
            RenameColumn(table: "Discounts.DiscountProducts", name: "MasterID", newName: "DiscountID");
            RenameColumn(table: "Discounts.DiscountCategories", name: "MasterID", newName: "DiscountID");
            RenameColumn(table: "Payments.SalesInvoicePayment", name: "MasterID", newName: "SalesInvoiceID");
            RenameColumn(table: "Invoicing.SalesInvoiceContact", name: "MasterID", newName: "SalesInvoiceID");
            RenameColumn(table: "Invoicing.SalesOrderSalesInvoice", name: "SlaveID", newName: "SalesInvoiceID");
            RenameColumn(table: "Payments.SalesOrderPayment", name: "MasterID", newName: "SalesOrderID");
            RenameColumn(table: "Ordering.SalesOrderContact", name: "MasterID", newName: "SalesOrderID");
            RenameColumn(table: "Returning.SalesReturnSalesOrder", name: "SlaveID", newName: "SalesOrderID");
            RenameColumn(table: "Quoting.SalesQuoteSalesOrder", name: "SlaveID", newName: "SalesOrderID");
            RenameColumn(table: "Invoicing.SalesOrderSalesInvoice", name: "MasterID", newName: "SalesOrderID");
            RenameColumn(table: "Purchasing.SalesOrderPurchaseOrder", name: "MasterID", newName: "SalesOrderID");
            RenameColumn(table: "Purchasing.PurchaseOrderContact", name: "MasterID", newName: "PurchaseOrderID");
            RenameColumn(table: "Purchasing.SalesOrderPurchaseOrder", name: "SlaveID", newName: "PurchaseOrderID");
            RenameColumn(table: "Stores.SiteDomainSocialProvider", name: "SlaveID", newName: "SocialProviderID");
            RenameColumn(table: "Stores.StoreSiteDomain", name: "SlaveID", newName: "SiteDomainID");
            RenameColumn(table: "Stores.SiteDomainSocialProvider", name: "MasterID", newName: "SiteDomainID");
            RenameColumn(table: "Stores.BrandSiteDomain", name: "SlaveID", newName: "SiteDomainID");
            RenameColumn(table: "Stores.BrandStore", name: "MasterID", newName: "BrandID");
            RenameColumn(table: "Stores.BrandSiteDomain", name: "MasterID", newName: "BrandID");
            RenameColumn(table: "Stores.StoreVendor", name: "MasterID", newName: "StoreID");
            RenameColumn(table: "Stores.StoreUserType", name: "MasterID", newName: "StoreID");
            RenameColumn(table: "Stores.StoreUser", name: "MasterID", newName: "StoreID");
            RenameColumn(table: "Stores.StoreSubscription", name: "MasterID", newName: "StoreID");
            RenameColumn(table: "Stores.StoreSiteDomain", name: "MasterID", newName: "StoreID");
            RenameColumn(table: "Stores.StoreProduct", name: "MasterID", newName: "StoreID");
            RenameColumn(table: "Stores.StoreManufacturer", name: "MasterID", newName: "StoreID");
            RenameColumn(table: "Stores.StoreInventoryLocation", name: "MasterID", newName: "StoreID");
            RenameColumn(table: "Stores.StoreContact", name: "MasterID", newName: "StoreID");
            RenameColumn(table: "Stores.StoreCategoryType", name: "MasterID", newName: "StoreID");
            RenameColumn(table: "Stores.StoreCategory", name: "MasterID", newName: "StoreID");
            RenameColumn(table: "Stores.StoreBadge", name: "MasterID", newName: "StoreID");
            RenameColumn(table: "Stores.StoreAccount", name: "MasterID", newName: "StoreID");
            RenameColumn(table: "Stores.BrandStore", name: "SlaveID", newName: "StoreID");
            RenameColumn(table: "Stores.StoreAccount", name: "SlaveID", newName: "AccountID");
            RenameColumn(table: "Accounts.AccountPricePoint", name: "MasterID", newName: "AccountID");
            RenameColumn(table: "Accounts.AccountContact", name: "MasterID", newName: "AccountID");
            CreateIndex("Returning.SalesReturn", "CustomerPriorityID");
            CreateIndex("Vendors.Vendor", "ShipViaID");
            CreateIndex("Vendors.Vendor", "TermID");
            CreateIndex("Shopping.Cart", new[] { "SessionID", "TypeID", "UserID" }, unique: true, name: "Unq_BySessionTypeUserActive");
            CreateIndex("Ordering.SalesOrder", "CustomerPriorityID");
            CreateIndex("Purchasing.PurchaseOrder", "VendorTermID");
            CreateIndex("Purchasing.PurchaseOrder", "FreeOnBoardID");
            CreateIndex("Currencies.HistoricalCurrencyRate", "EndingCurrencyID");
            CreateIndex("Currencies.HistoricalCurrencyRate", "StartingCurrencyID");
            AddForeignKey("Purchasing.PurchaseOrder", "VendorTermID", "Vendors.VendorTerm", "ID");
            AddForeignKey("Purchasing.PurchaseOrder", "FreeOnBoardID", "Purchasing.FreeOnBoard", "ID");
            AddForeignKey("Ordering.SalesOrder", "CustomerPriorityID", "Contacts.CustomerPriority", "ID");
            AddForeignKey("Returning.SalesReturn", "CustomerPriorityID", "Contacts.CustomerPriority", "ID");
            AddForeignKey("Vendors.Vendor", "TermID", "Vendors.Term", "ID");
            AddForeignKey("Vendors.Vendor", "ShipViaID", "Vendors.ShipVia", "ID");
        }
    }
}
