// <auto-generated />
namespace Clarity.Ecommerce.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TargetApplicationsUsed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TargetApplicationsUsed));
        
        string IMigrationMetadata.Id
        {
            get { return "202106260124509_TargetApplicationsUsed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
