/**
* @file framework/admin/controls/system/clearCacheButtonsWidget.ts
* @author Copyright(c) 2018-2022 clarity-ventures.com. All rights reserved.
* @desc NOTE: This file is generated via the clearCacheButtons.tt T4 in the UI Project
*/
module cef.admin {
class ClearCacheButtonsWidgetController extends core.TemplatedControllerBase {
// Properties
// <None>
// Functions
clearAccountsCache(): void { this.clearAnySpecificCache("Accounts", this.cvApi.accounts.ClearAccountCache); }
clearAccountAssociationsCache(): void { this.clearAnySpecificCache("AccountAssociations", this.cvApi.accounts.ClearAccountAssociationCache); }
clearAccountAssociationTypesCache(): void { this.clearAnySpecificCache("AccountAssociationTypes", this.cvApi.accounts.ClearAccountAssociationTypeCache); }
clearAccountContactsCache(): void { this.clearAnySpecificCache("AccountContacts", this.cvApi.accounts.ClearAccountContactCache); }
clearAccountCurrenciesCache(): void { this.clearAnySpecificCache("AccountCurrencies", this.cvApi.accounts.ClearAccountCurrencyCache); }
clearAccountFilesCache(): void { this.clearAnySpecificCache("AccountFiles", this.cvApi.accounts.ClearAccountFileCache); }
clearAccountImagesCache(): void { this.clearAnySpecificCache("AccountImages", this.cvApi.accounts.ClearAccountImageCache); }
clearAccountImageTypesCache(): void { this.clearAnySpecificCache("AccountImageTypes", this.cvApi.accounts.ClearAccountImageTypeCache); }
clearAccountPricePointsCache(): void { this.clearAnySpecificCache("AccountPricePoints", this.cvApi.accounts.ClearAccountPricePointCache); }
clearAccountProductsCache(): void { this.clearAnySpecificCache("AccountProducts", this.cvApi.accounts.ClearAccountProductCache); }
clearAccountProductTypesCache(): void { this.clearAnySpecificCache("AccountProductTypes", this.cvApi.accounts.ClearAccountProductTypeCache); }
clearAccountStatusesCache(): void { this.clearAnySpecificCache("AccountStatuses", this.cvApi.accounts.ClearAccountStatusCache); }
clearAccountTypesCache(): void { this.clearAnySpecificCache("AccountTypes", this.cvApi.accounts.ClearAccountTypeCache); }
clearAccountUsageBalancesCache(): void { this.clearAnySpecificCache("AccountUsageBalances", this.cvApi.accounts.ClearAccountUsageBalanceCache); }
clearContractorsCache(): void { this.clearAnySpecificCache("Contractors", this.cvApi.accounts.ClearContractorCache); }
clearServiceAreasCache(): void { this.clearAnySpecificCache("ServiceAreas", this.cvApi.accounts.ClearServiceAreaCache); }
clearAdsCache(): void { this.clearAnySpecificCache("Ads", this.cvApi.advertising.ClearAdCache); }
clearAdAccountsCache(): void { this.clearAnySpecificCache("AdAccounts", this.cvApi.advertising.ClearAdAccountCache); }
clearAdBrandsCache(): void { this.clearAnySpecificCache("AdBrands", this.cvApi.advertising.ClearAdBrandCache); }
clearAdFranchisesCache(): void { this.clearAnySpecificCache("AdFranchises", this.cvApi.advertising.ClearAdFranchiseCache); }
clearAdImagesCache(): void { this.clearAnySpecificCache("AdImages", this.cvApi.advertising.ClearAdImageCache); }
clearAdImageTypesCache(): void { this.clearAnySpecificCache("AdImageTypes", this.cvApi.advertising.ClearAdImageTypeCache); }
clearAdStatusesCache(): void { this.clearAnySpecificCache("AdStatuses", this.cvApi.advertising.ClearAdStatusCache); }
clearAdStoresCache(): void { this.clearAnySpecificCache("AdStores", this.cvApi.advertising.ClearAdStoreCache); }
clearAdTypesCache(): void { this.clearAnySpecificCache("AdTypes", this.cvApi.advertising.ClearAdTypeCache); }
clearAdZonesCache(): void { this.clearAnySpecificCache("AdZones", this.cvApi.advertising.ClearAdZoneCache); }
clearAdZoneAccessesCache(): void { this.clearAnySpecificCache("AdZoneAccesses", this.cvApi.advertising.ClearAdZoneAccessCache); }
clearZonesCache(): void { this.clearAnySpecificCache("Zones", this.cvApi.advertising.ClearZoneCache); }
clearZoneStatusesCache(): void { this.clearAnySpecificCache("ZoneStatuses", this.cvApi.advertising.ClearZoneStatusCache); }
clearZoneTypesCache(): void { this.clearAnySpecificCache("ZoneTypes", this.cvApi.advertising.ClearZoneTypeCache); }
clearAttributeGroupsCache(): void { this.clearAnySpecificCache("AttributeGroups", this.cvApi.attributes.ClearAttributeGroupCache); }
clearAttributeTabsCache(): void { this.clearAnySpecificCache("AttributeTabs", this.cvApi.attributes.ClearAttributeTabCache); }
clearAttributeTypesCache(): void { this.clearAnySpecificCache("AttributeTypes", this.cvApi.attributes.ClearAttributeTypeCache); }
clearGeneralAttributesCache(): void { this.clearAnySpecificCache("GeneralAttributes", this.cvApi.attributes.ClearGeneralAttributeCache); }
clearGeneralAttributePredefinedOptionsCache(): void { this.clearAnySpecificCache("GeneralAttributePredefinedOptions", this.cvApi.attributes.ClearGeneralAttributePredefinedOptionCache); }
clearAuctionsCache(): void { this.clearAnySpecificCache("Auctions", this.cvApi.auctions.ClearAuctionCache); }
clearAuctionCategoriesCache(): void { this.clearAnySpecificCache("AuctionCategories", this.cvApi.auctions.ClearAuctionCategoryCache); }
clearAuctionStatusesCache(): void { this.clearAnySpecificCache("AuctionStatuses", this.cvApi.auctions.ClearAuctionStatusCache); }
clearAuctionTypesCache(): void { this.clearAnySpecificCache("AuctionTypes", this.cvApi.auctions.ClearAuctionTypeCache); }
clearBidsCache(): void { this.clearAnySpecificCache("Bids", this.cvApi.auctions.ClearBidCache); }
clearBidStatusesCache(): void { this.clearAnySpecificCache("BidStatuses", this.cvApi.auctions.ClearBidStatusCache); }
clearBrandAuctionsCache(): void { this.clearAnySpecificCache("BrandAuctions", this.cvApi.auctions.ClearBrandAuctionCache); }
clearFranchiseAuctionsCache(): void { this.clearAnySpecificCache("FranchiseAuctions", this.cvApi.auctions.ClearFranchiseAuctionCache); }
clearLotsCache(): void { this.clearAnySpecificCache("Lots", this.cvApi.auctions.ClearLotCache); }
clearLotCategoriesCache(): void { this.clearAnySpecificCache("LotCategories", this.cvApi.auctions.ClearLotCategoryCache); }
clearLotGroupsCache(): void { this.clearAnySpecificCache("LotGroups", this.cvApi.auctions.ClearLotGroupCache); }
clearLotStatusesCache(): void { this.clearAnySpecificCache("LotStatuses", this.cvApi.auctions.ClearLotStatusCache); }
clearLotTypesCache(): void { this.clearAnySpecificCache("LotTypes", this.cvApi.auctions.ClearLotTypeCache); }
clearStoreAuctionsCache(): void { this.clearAnySpecificCache("StoreAuctions", this.cvApi.auctions.ClearStoreAuctionCache); }
clearBadgesCache(): void { this.clearAnySpecificCache("Badges", this.cvApi.badges.ClearBadgeCache); }
clearBadgeImagesCache(): void { this.clearAnySpecificCache("BadgeImages", this.cvApi.badges.ClearBadgeImageCache); }
clearBadgeImageTypesCache(): void { this.clearAnySpecificCache("BadgeImageTypes", this.cvApi.badges.ClearBadgeImageTypeCache); }
clearBadgeTypesCache(): void { this.clearAnySpecificCache("BadgeTypes", this.cvApi.badges.ClearBadgeTypeCache); }
clearBrandsCache(): void { this.clearAnySpecificCache("Brands", this.cvApi.brands.ClearBrandCache); }
clearBrandAccountsCache(): void { this.clearAnySpecificCache("BrandAccounts", this.cvApi.brands.ClearBrandAccountCache); }
clearBrandCategoriesCache(): void { this.clearAnySpecificCache("BrandCategories", this.cvApi.brands.ClearBrandCategoryCache); }
clearBrandCurrenciesCache(): void { this.clearAnySpecificCache("BrandCurrencies", this.cvApi.brands.ClearBrandCurrencyCache); }
clearBrandFranchisesCache(): void { this.clearAnySpecificCache("BrandFranchises", this.cvApi.brands.ClearBrandFranchiseCache); }
clearBrandImagesCache(): void { this.clearAnySpecificCache("BrandImages", this.cvApi.brands.ClearBrandImageCache); }
clearBrandImageTypesCache(): void { this.clearAnySpecificCache("BrandImageTypes", this.cvApi.brands.ClearBrandImageTypeCache); }
clearBrandInventoryLocationsCache(): void { this.clearAnySpecificCache("BrandInventoryLocations", this.cvApi.brands.ClearBrandInventoryLocationCache); }
clearBrandInventoryLocationTypesCache(): void { this.clearAnySpecificCache("BrandInventoryLocationTypes", this.cvApi.brands.ClearBrandInventoryLocationTypeCache); }
clearBrandLanguagesCache(): void { this.clearAnySpecificCache("BrandLanguages", this.cvApi.brands.ClearBrandLanguageCache); }
clearBrandManufacturersCache(): void { this.clearAnySpecificCache("BrandManufacturers", this.cvApi.brands.ClearBrandManufacturerCache); }
clearBrandProductsCache(): void { this.clearAnySpecificCache("BrandProducts", this.cvApi.brands.ClearBrandProductCache); }
clearBrandSiteDomainsCache(): void { this.clearAnySpecificCache("BrandSiteDomains", this.cvApi.brands.ClearBrandSiteDomainCache); }
clearBrandStoresCache(): void { this.clearAnySpecificCache("BrandStores", this.cvApi.brands.ClearBrandStoreCache); }
clearBrandUsersCache(): void { this.clearAnySpecificCache("BrandUsers", this.cvApi.brands.ClearBrandUserCache); }
clearBrandVendorsCache(): void { this.clearAnySpecificCache("BrandVendors", this.cvApi.brands.ClearBrandVendorCache); }
clearCalendarEventsCache(): void { this.clearAnySpecificCache("CalendarEvents", this.cvApi.calendarEvents.ClearCalendarEventCache); }
clearCalendarEventDetailsCache(): void { this.clearAnySpecificCache("CalendarEventDetails", this.cvApi.calendarEvents.ClearCalendarEventDetailCache); }
clearCalendarEventFilesCache(): void { this.clearAnySpecificCache("CalendarEventFiles", this.cvApi.calendarEvents.ClearCalendarEventFileCache); }
clearCalendarEventImagesCache(): void { this.clearAnySpecificCache("CalendarEventImages", this.cvApi.calendarEvents.ClearCalendarEventImageCache); }
clearCalendarEventImageTypesCache(): void { this.clearAnySpecificCache("CalendarEventImageTypes", this.cvApi.calendarEvents.ClearCalendarEventImageTypeCache); }
clearCalendarEventProductsCache(): void { this.clearAnySpecificCache("CalendarEventProducts", this.cvApi.calendarEvents.ClearCalendarEventProductCache); }
clearCalendarEventStatusesCache(): void { this.clearAnySpecificCache("CalendarEventStatuses", this.cvApi.calendarEvents.ClearCalendarEventStatusCache); }
clearCalendarEventTypesCache(): void { this.clearAnySpecificCache("CalendarEventTypes", this.cvApi.calendarEvents.ClearCalendarEventTypeCache); }
clearUserEventAttendancesCache(): void { this.clearAnySpecificCache("UserEventAttendances", this.cvApi.calendarEvents.ClearUserEventAttendanceCache); }
clearUserEventAttendanceTypesCache(): void { this.clearAnySpecificCache("UserEventAttendanceTypes", this.cvApi.calendarEvents.ClearUserEventAttendanceTypeCache); }
clearCategoriesCache(): void { this.clearAnySpecificCache("Categories", this.cvApi.categories.ClearCategoryCache); }
clearCategoryFilesCache(): void { this.clearAnySpecificCache("CategoryFiles", this.cvApi.categories.ClearCategoryFileCache); }
clearCategoryImagesCache(): void { this.clearAnySpecificCache("CategoryImages", this.cvApi.categories.ClearCategoryImageCache); }
clearCategoryImageTypesCache(): void { this.clearAnySpecificCache("CategoryImageTypes", this.cvApi.categories.ClearCategoryImageTypeCache); }
clearCategoryTypesCache(): void { this.clearAnySpecificCache("CategoryTypes", this.cvApi.categories.ClearCategoryTypeCache); }
clearContactsCache(): void { this.clearAnySpecificCache("Contacts", this.cvApi.contacts.ClearContactCache); }
clearContactImagesCache(): void { this.clearAnySpecificCache("ContactImages", this.cvApi.contacts.ClearContactImageCache); }
clearContactImageTypesCache(): void { this.clearAnySpecificCache("ContactImageTypes", this.cvApi.contacts.ClearContactImageTypeCache); }
clearContactTypesCache(): void { this.clearAnySpecificCache("ContactTypes", this.cvApi.contacts.ClearContactTypeCache); }
clearProfanityFiltersCache(): void { this.clearAnySpecificCache("ProfanityFilters", this.cvApi.contacts.ClearProfanityFilterCache); }
clearReferralCodesCache(): void { this.clearAnySpecificCache("ReferralCodes", this.cvApi.contacts.ClearReferralCodeCache); }
clearReferralCodeStatusesCache(): void { this.clearAnySpecificCache("ReferralCodeStatuses", this.cvApi.contacts.ClearReferralCodeStatusCache); }
clearReferralCodeTypesCache(): void { this.clearAnySpecificCache("ReferralCodeTypes", this.cvApi.contacts.ClearReferralCodeTypeCache); }
clearUsersCache(): void { this.clearAnySpecificCache("Users", this.cvApi.contacts.ClearUserCache); }
clearUserFilesCache(): void { this.clearAnySpecificCache("UserFiles", this.cvApi.contacts.ClearUserFileCache); }
clearUserImagesCache(): void { this.clearAnySpecificCache("UserImages", this.cvApi.contacts.ClearUserImageCache); }
clearUserImageTypesCache(): void { this.clearAnySpecificCache("UserImageTypes", this.cvApi.contacts.ClearUserImageTypeCache); }
clearUserOnlineStatusesCache(): void { this.clearAnySpecificCache("UserOnlineStatuses", this.cvApi.contacts.ClearUserOnlineStatusCache); }
clearUserProductTypesCache(): void { this.clearAnySpecificCache("UserProductTypes", this.cvApi.contacts.ClearUserProductTypeCache); }
clearUserStatusesCache(): void { this.clearAnySpecificCache("UserStatuses", this.cvApi.contacts.ClearUserStatusCache); }
clearUserTypesCache(): void { this.clearAnySpecificCache("UserTypes", this.cvApi.contacts.ClearUserTypeCache); }
clearCountersCache(): void { this.clearAnySpecificCache("Counters", this.cvApi.counters.ClearCounterCache); }
clearCounterLogsCache(): void { this.clearAnySpecificCache("CounterLogs", this.cvApi.counters.ClearCounterLogCache); }
clearCounterLogTypesCache(): void { this.clearAnySpecificCache("CounterLogTypes", this.cvApi.counters.ClearCounterLogTypeCache); }
clearCounterTypesCache(): void { this.clearAnySpecificCache("CounterTypes", this.cvApi.counters.ClearCounterTypeCache); }
clearCurrenciesCache(): void { this.clearAnySpecificCache("Currencies", this.cvApi.currencies.ClearCurrencyCache); }
clearCurrencyConversionsCache(): void { this.clearAnySpecificCache("CurrencyConversions", this.cvApi.currencies.ClearCurrencyConversionCache); }
clearCurrencyImagesCache(): void { this.clearAnySpecificCache("CurrencyImages", this.cvApi.currencies.ClearCurrencyImageCache); }
clearCurrencyImageTypesCache(): void { this.clearAnySpecificCache("CurrencyImageTypes", this.cvApi.currencies.ClearCurrencyImageTypeCache); }
clearHistoricalCurrencyRatesCache(): void { this.clearAnySpecificCache("HistoricalCurrencyRates", this.cvApi.currencies.ClearHistoricalCurrencyRateCache); }
clearAppliedCartDiscountsCache(): void { this.clearAnySpecificCache("AppliedCartDiscounts", this.cvApi.discounts.ClearAppliedCartDiscountCache); }
clearAppliedCartItemDiscountsCache(): void { this.clearAnySpecificCache("AppliedCartItemDiscounts", this.cvApi.discounts.ClearAppliedCartItemDiscountCache); }
clearDiscountsCache(): void { this.clearAnySpecificCache("Discounts", this.cvApi.discounts.ClearDiscountCache); }
clearDiscountAccountsCache(): void { this.clearAnySpecificCache("DiscountAccounts", this.cvApi.discounts.ClearDiscountAccountCache); }
clearDiscountAccountTypesCache(): void { this.clearAnySpecificCache("DiscountAccountTypes", this.cvApi.discounts.ClearDiscountAccountTypeCache); }
clearDiscountBrandsCache(): void { this.clearAnySpecificCache("DiscountBrands", this.cvApi.discounts.ClearDiscountBrandCache); }
clearDiscountCategoriesCache(): void { this.clearAnySpecificCache("DiscountCategories", this.cvApi.discounts.ClearDiscountCategoryCache); }
clearDiscountCodesCache(): void { this.clearAnySpecificCache("DiscountCodes", this.cvApi.discounts.ClearDiscountCodeCache); }
clearDiscountCountriesCache(): void { this.clearAnySpecificCache("DiscountCountries", this.cvApi.discounts.ClearDiscountCountryCache); }
clearDiscountFranchisesCache(): void { this.clearAnySpecificCache("DiscountFranchises", this.cvApi.discounts.ClearDiscountFranchiseCache); }
clearDiscountManufacturersCache(): void { this.clearAnySpecificCache("DiscountManufacturers", this.cvApi.discounts.ClearDiscountManufacturerCache); }
clearDiscountProductsCache(): void { this.clearAnySpecificCache("DiscountProducts", this.cvApi.discounts.ClearDiscountProductCache); }
clearDiscountProductTypesCache(): void { this.clearAnySpecificCache("DiscountProductTypes", this.cvApi.discounts.ClearDiscountProductTypeCache); }
clearDiscountShipCarrierMethodsCache(): void { this.clearAnySpecificCache("DiscountShipCarrierMethods", this.cvApi.discounts.ClearDiscountShipCarrierMethodCache); }
clearDiscountStoresCache(): void { this.clearAnySpecificCache("DiscountStores", this.cvApi.discounts.ClearDiscountStoreCache); }
clearDiscountUsersCache(): void { this.clearAnySpecificCache("DiscountUsers", this.cvApi.discounts.ClearDiscountUserCache); }
clearDiscountUserRolesCache(): void { this.clearAnySpecificCache("DiscountUserRoles", this.cvApi.discounts.ClearDiscountUserRoleCache); }
clearDiscountVendorsCache(): void { this.clearAnySpecificCache("DiscountVendors", this.cvApi.discounts.ClearDiscountVendorCache); }
clearAppliedPurchaseOrderDiscountsCache(): void { this.clearAnySpecificCache("AppliedPurchaseOrderDiscounts", this.cvApi.discounts.ClearAppliedPurchaseOrderDiscountCache); }
clearAppliedPurchaseOrderItemDiscountsCache(): void { this.clearAnySpecificCache("AppliedPurchaseOrderItemDiscounts", this.cvApi.discounts.ClearAppliedPurchaseOrderItemDiscountCache); }
clearAppliedSalesInvoiceDiscountsCache(): void { this.clearAnySpecificCache("AppliedSalesInvoiceDiscounts", this.cvApi.discounts.ClearAppliedSalesInvoiceDiscountCache); }
clearAppliedSalesInvoiceItemDiscountsCache(): void { this.clearAnySpecificCache("AppliedSalesInvoiceItemDiscounts", this.cvApi.discounts.ClearAppliedSalesInvoiceItemDiscountCache); }
clearAppliedSalesOrderDiscountsCache(): void { this.clearAnySpecificCache("AppliedSalesOrderDiscounts", this.cvApi.discounts.ClearAppliedSalesOrderDiscountCache); }
clearAppliedSalesOrderItemDiscountsCache(): void { this.clearAnySpecificCache("AppliedSalesOrderItemDiscounts", this.cvApi.discounts.ClearAppliedSalesOrderItemDiscountCache); }
clearAppliedSalesQuoteDiscountsCache(): void { this.clearAnySpecificCache("AppliedSalesQuoteDiscounts", this.cvApi.discounts.ClearAppliedSalesQuoteDiscountCache); }
clearAppliedSalesQuoteItemDiscountsCache(): void { this.clearAnySpecificCache("AppliedSalesQuoteItemDiscounts", this.cvApi.discounts.ClearAppliedSalesQuoteItemDiscountCache); }
clearAppliedSalesReturnDiscountsCache(): void { this.clearAnySpecificCache("AppliedSalesReturnDiscounts", this.cvApi.discounts.ClearAppliedSalesReturnDiscountCache); }
clearAppliedSalesReturnItemDiscountsCache(): void { this.clearAnySpecificCache("AppliedSalesReturnItemDiscounts", this.cvApi.discounts.ClearAppliedSalesReturnItemDiscountCache); }
clearAppliedSampleRequestDiscountsCache(): void { this.clearAnySpecificCache("AppliedSampleRequestDiscounts", this.cvApi.discounts.ClearAppliedSampleRequestDiscountCache); }
clearAppliedSampleRequestItemDiscountsCache(): void { this.clearAnySpecificCache("AppliedSampleRequestItemDiscounts", this.cvApi.discounts.ClearAppliedSampleRequestItemDiscountCache); }
clearFavoriteCategoriesCache(): void { this.clearAnySpecificCache("FavoriteCategories", this.cvApi.favorites.ClearFavoriteCategoryCache); }
clearFavoriteManufacturersCache(): void { this.clearAnySpecificCache("FavoriteManufacturers", this.cvApi.favorites.ClearFavoriteManufacturerCache); }
clearFavoriteShipCarriersCache(): void { this.clearAnySpecificCache("FavoriteShipCarriers", this.cvApi.favorites.ClearFavoriteShipCarrierCache); }
clearFavoriteStoresCache(): void { this.clearAnySpecificCache("FavoriteStores", this.cvApi.favorites.ClearFavoriteStoreCache); }
clearFavoriteVendorsCache(): void { this.clearAnySpecificCache("FavoriteVendors", this.cvApi.favorites.ClearFavoriteVendorCache); }
clearFranchisesCache(): void { this.clearAnySpecificCache("Franchises", this.cvApi.franchises.ClearFranchiseCache); }
clearFranchiseAccountsCache(): void { this.clearAnySpecificCache("FranchiseAccounts", this.cvApi.franchises.ClearFranchiseAccountCache); }
clearFranchiseCategoriesCache(): void { this.clearAnySpecificCache("FranchiseCategories", this.cvApi.franchises.ClearFranchiseCategoryCache); }
clearFranchiseCountriesCache(): void { this.clearAnySpecificCache("FranchiseCountries", this.cvApi.franchises.ClearFranchiseCountryCache); }
clearFranchiseCurrenciesCache(): void { this.clearAnySpecificCache("FranchiseCurrencies", this.cvApi.franchises.ClearFranchiseCurrencyCache); }
clearFranchiseDistrictsCache(): void { this.clearAnySpecificCache("FranchiseDistricts", this.cvApi.franchises.ClearFranchiseDistrictCache); }
clearFranchiseImagesCache(): void { this.clearAnySpecificCache("FranchiseImages", this.cvApi.franchises.ClearFranchiseImageCache); }
clearFranchiseImageTypesCache(): void { this.clearAnySpecificCache("FranchiseImageTypes", this.cvApi.franchises.ClearFranchiseImageTypeCache); }
clearFranchiseInventoryLocationsCache(): void { this.clearAnySpecificCache("FranchiseInventoryLocations", this.cvApi.franchises.ClearFranchiseInventoryLocationCache); }
clearFranchiseInventoryLocationTypesCache(): void { this.clearAnySpecificCache("FranchiseInventoryLocationTypes", this.cvApi.franchises.ClearFranchiseInventoryLocationTypeCache); }
clearFranchiseLanguagesCache(): void { this.clearAnySpecificCache("FranchiseLanguages", this.cvApi.franchises.ClearFranchiseLanguageCache); }
clearFranchiseManufacturersCache(): void { this.clearAnySpecificCache("FranchiseManufacturers", this.cvApi.franchises.ClearFranchiseManufacturerCache); }
clearFranchiseProductsCache(): void { this.clearAnySpecificCache("FranchiseProducts", this.cvApi.franchises.ClearFranchiseProductCache); }
clearFranchiseRegionsCache(): void { this.clearAnySpecificCache("FranchiseRegions", this.cvApi.franchises.ClearFranchiseRegionCache); }
clearFranchiseSiteDomainsCache(): void { this.clearAnySpecificCache("FranchiseSiteDomains", this.cvApi.franchises.ClearFranchiseSiteDomainCache); }
clearFranchiseStoresCache(): void { this.clearAnySpecificCache("FranchiseStores", this.cvApi.franchises.ClearFranchiseStoreCache); }
clearFranchiseTypesCache(): void { this.clearAnySpecificCache("FranchiseTypes", this.cvApi.franchises.ClearFranchiseTypeCache); }
clearFranchiseUsersCache(): void { this.clearAnySpecificCache("FranchiseUsers", this.cvApi.franchises.ClearFranchiseUserCache); }
clearFranchiseVendorsCache(): void { this.clearAnySpecificCache("FranchiseVendors", this.cvApi.franchises.ClearFranchiseVendorCache); }
clearAddressesCache(): void { this.clearAnySpecificCache("Addresses", this.cvApi.geography.ClearAddressCache); }
clearCountriesCache(): void { this.clearAnySpecificCache("Countries", this.cvApi.geography.ClearCountryCache); }
clearCountryCurrenciesCache(): void { this.clearAnySpecificCache("CountryCurrencies", this.cvApi.geography.ClearCountryCurrencyCache); }
clearCountryImagesCache(): void { this.clearAnySpecificCache("CountryImages", this.cvApi.geography.ClearCountryImageCache); }
clearCountryImageTypesCache(): void { this.clearAnySpecificCache("CountryImageTypes", this.cvApi.geography.ClearCountryImageTypeCache); }
clearCountryLanguagesCache(): void { this.clearAnySpecificCache("CountryLanguages", this.cvApi.geography.ClearCountryLanguageCache); }
clearDistrictsCache(): void { this.clearAnySpecificCache("Districts", this.cvApi.geography.ClearDistrictCache); }
clearDistrictCurrenciesCache(): void { this.clearAnySpecificCache("DistrictCurrencies", this.cvApi.geography.ClearDistrictCurrencyCache); }
clearDistrictImagesCache(): void { this.clearAnySpecificCache("DistrictImages", this.cvApi.geography.ClearDistrictImageCache); }
clearDistrictImageTypesCache(): void { this.clearAnySpecificCache("DistrictImageTypes", this.cvApi.geography.ClearDistrictImageTypeCache); }
clearDistrictLanguagesCache(): void { this.clearAnySpecificCache("DistrictLanguages", this.cvApi.geography.ClearDistrictLanguageCache); }
clearHistoricalAddressValidationsCache(): void { this.clearAnySpecificCache("HistoricalAddressValidations", this.cvApi.geography.ClearHistoricalAddressValidationCache); }
clearPhonePrefixLookupsCache(): void { this.clearAnySpecificCache("PhonePrefixLookups", this.cvApi.geography.ClearPhonePrefixLookupCache); }
clearRegionsCache(): void { this.clearAnySpecificCache("Regions", this.cvApi.geography.ClearRegionCache); }
clearRegionCurrenciesCache(): void { this.clearAnySpecificCache("RegionCurrencies", this.cvApi.geography.ClearRegionCurrencyCache); }
clearRegionImagesCache(): void { this.clearAnySpecificCache("RegionImages", this.cvApi.geography.ClearRegionImageCache); }
clearRegionImageTypesCache(): void { this.clearAnySpecificCache("RegionImageTypes", this.cvApi.geography.ClearRegionImageTypeCache); }
clearRegionLanguagesCache(): void { this.clearAnySpecificCache("RegionLanguages", this.cvApi.geography.ClearRegionLanguageCache); }
clearZipCodesCache(): void { this.clearAnySpecificCache("ZipCodes", this.cvApi.geography.ClearZipCodeCache); }
clearLanguagesCache(): void { this.clearAnySpecificCache("Languages", this.cvApi.globalization.ClearLanguageCache); }
clearLanguageImagesCache(): void { this.clearAnySpecificCache("LanguageImages", this.cvApi.globalization.ClearLanguageImageCache); }
clearLanguageImageTypesCache(): void { this.clearAnySpecificCache("LanguageImageTypes", this.cvApi.globalization.ClearLanguageImageTypeCache); }
clearUiKeysCache(): void { this.clearAnySpecificCache("UiKeys", this.cvApi.globalization.ClearUiKeyCache); }
clearUiTranslationsCache(): void { this.clearAnySpecificCache("UiTranslations", this.cvApi.globalization.ClearUiTranslationCache); }
clearGroupsCache(): void { this.clearAnySpecificCache("Groups", this.cvApi.groups.ClearGroupCache); }
clearGroupStatusesCache(): void { this.clearAnySpecificCache("GroupStatuses", this.cvApi.groups.ClearGroupStatusCache); }
clearGroupTypesCache(): void { this.clearAnySpecificCache("GroupTypes", this.cvApi.groups.ClearGroupTypeCache); }
clearGroupUsersCache(): void { this.clearAnySpecificCache("GroupUsers", this.cvApi.groups.ClearGroupUserCache); }
clearScheduledJobConfigurationsCache(): void { this.clearAnySpecificCache("ScheduledJobConfigurations", this.cvApi.hangfire.ClearScheduledJobConfigurationCache); }
clearScheduledJobConfigurationSettingsCache(): void { this.clearAnySpecificCache("ScheduledJobConfigurationSettings", this.cvApi.hangfire.ClearScheduledJobConfigurationSettingCache); }
clearInventoryLocationsCache(): void { this.clearAnySpecificCache("InventoryLocations", this.cvApi.inventory.ClearInventoryLocationCache); }
clearInventoryLocationRegionsCache(): void { this.clearAnySpecificCache("InventoryLocationRegions", this.cvApi.inventory.ClearInventoryLocationRegionCache); }
clearInventoryLocationSectionsCache(): void { this.clearAnySpecificCache("InventoryLocationSections", this.cvApi.inventory.ClearInventoryLocationSectionCache); }
clearInventoryLocationUsersCache(): void { this.clearAnySpecificCache("InventoryLocationUsers", this.cvApi.inventory.ClearInventoryLocationUserCache); }
clearSalesInvoicesCache(): void { this.clearAnySpecificCache("SalesInvoices", this.cvApi.invoicing.ClearSalesInvoiceCache); }
clearSalesInvoiceContactsCache(): void { this.clearAnySpecificCache("SalesInvoiceContacts", this.cvApi.invoicing.ClearSalesInvoiceContactCache); }
clearSalesInvoiceEventsCache(): void { this.clearAnySpecificCache("SalesInvoiceEvents", this.cvApi.invoicing.ClearSalesInvoiceEventCache); }
clearSalesInvoiceEventTypesCache(): void { this.clearAnySpecificCache("SalesInvoiceEventTypes", this.cvApi.invoicing.ClearSalesInvoiceEventTypeCache); }
clearSalesInvoiceFilesCache(): void { this.clearAnySpecificCache("SalesInvoiceFiles", this.cvApi.invoicing.ClearSalesInvoiceFileCache); }
clearSalesInvoiceItemsCache(): void { this.clearAnySpecificCache("SalesInvoiceItems", this.cvApi.invoicing.ClearSalesInvoiceItemCache); }
clearSalesInvoiceItemTargetsCache(): void { this.clearAnySpecificCache("SalesInvoiceItemTargets", this.cvApi.invoicing.ClearSalesInvoiceItemTargetCache); }
clearSalesInvoiceStatesCache(): void { this.clearAnySpecificCache("SalesInvoiceStates", this.cvApi.invoicing.ClearSalesInvoiceStateCache); }
clearSalesInvoiceStatusesCache(): void { this.clearAnySpecificCache("SalesInvoiceStatuses", this.cvApi.invoicing.ClearSalesInvoiceStatusCache); }
clearSalesInvoiceTypesCache(): void { this.clearAnySpecificCache("SalesInvoiceTypes", this.cvApi.invoicing.ClearSalesInvoiceTypeCache); }
clearSalesOrderSalesInvoicesCache(): void { this.clearAnySpecificCache("SalesOrderSalesInvoices", this.cvApi.invoicing.ClearSalesOrderSalesInvoiceCache); }
clearManufacturersCache(): void { this.clearAnySpecificCache("Manufacturers", this.cvApi.manufacturers.ClearManufacturerCache); }
clearManufacturerImagesCache(): void { this.clearAnySpecificCache("ManufacturerImages", this.cvApi.manufacturers.ClearManufacturerImageCache); }
clearManufacturerImageTypesCache(): void { this.clearAnySpecificCache("ManufacturerImageTypes", this.cvApi.manufacturers.ClearManufacturerImageTypeCache); }
clearManufacturerProductsCache(): void { this.clearAnySpecificCache("ManufacturerProducts", this.cvApi.manufacturers.ClearManufacturerProductCache); }
clearManufacturerTypesCache(): void { this.clearAnySpecificCache("ManufacturerTypes", this.cvApi.manufacturers.ClearManufacturerTypeCache); }
clearStoredFilesCache(): void { this.clearAnySpecificCache("StoredFiles", this.cvApi.media.ClearStoredFileCache); }
clearConversationsCache(): void { this.clearAnySpecificCache("Conversations", this.cvApi.messaging.ClearConversationCache); }
clearConversationUsersCache(): void { this.clearAnySpecificCache("ConversationUsers", this.cvApi.messaging.ClearConversationUserCache); }
clearEmailQueuesCache(): void { this.clearAnySpecificCache("EmailQueues", this.cvApi.messaging.ClearEmailQueueCache); }
clearEmailQueueAttachmentsCache(): void { this.clearAnySpecificCache("EmailQueueAttachments", this.cvApi.messaging.ClearEmailQueueAttachmentCache); }
clearEmailStatusesCache(): void { this.clearAnySpecificCache("EmailStatuses", this.cvApi.messaging.ClearEmailStatusCache); }
clearEmailTemplatesCache(): void { this.clearAnySpecificCache("EmailTemplates", this.cvApi.messaging.ClearEmailTemplateCache); }
clearEmailTypesCache(): void { this.clearAnySpecificCache("EmailTypes", this.cvApi.messaging.ClearEmailTypeCache); }
clearMessagesCache(): void { this.clearAnySpecificCache("Messages", this.cvApi.messaging.ClearMessageCache); }
clearMessageAttachmentsCache(): void { this.clearAnySpecificCache("MessageAttachments", this.cvApi.messaging.ClearMessageAttachmentCache); }
clearMessageRecipientsCache(): void { this.clearAnySpecificCache("MessageRecipients", this.cvApi.messaging.ClearMessageRecipientCache); }
clearProductNotificationsCache(): void { this.clearAnySpecificCache("ProductNotifications", this.cvApi.messaging.ClearProductNotificationCache); }
clearSalesOrdersCache(): void { this.clearAnySpecificCache("SalesOrders", this.cvApi.ordering.ClearSalesOrderCache); }
clearSalesOrderContactsCache(): void { this.clearAnySpecificCache("SalesOrderContacts", this.cvApi.ordering.ClearSalesOrderContactCache); }
clearSalesOrderEventsCache(): void { this.clearAnySpecificCache("SalesOrderEvents", this.cvApi.ordering.ClearSalesOrderEventCache); }
clearSalesOrderEventTypesCache(): void { this.clearAnySpecificCache("SalesOrderEventTypes", this.cvApi.ordering.ClearSalesOrderEventTypeCache); }
clearSalesOrderFilesCache(): void { this.clearAnySpecificCache("SalesOrderFiles", this.cvApi.ordering.ClearSalesOrderFileCache); }
clearSalesOrderItemsCache(): void { this.clearAnySpecificCache("SalesOrderItems", this.cvApi.ordering.ClearSalesOrderItemCache); }
clearSalesOrderItemTargetsCache(): void { this.clearAnySpecificCache("SalesOrderItemTargets", this.cvApi.ordering.ClearSalesOrderItemTargetCache); }
clearSalesOrderStatesCache(): void { this.clearAnySpecificCache("SalesOrderStates", this.cvApi.ordering.ClearSalesOrderStateCache); }
clearSalesOrderStatusesCache(): void { this.clearAnySpecificCache("SalesOrderStatuses", this.cvApi.ordering.ClearSalesOrderStatusCache); }
clearSalesOrderTypesCache(): void { this.clearAnySpecificCache("SalesOrderTypes", this.cvApi.ordering.ClearSalesOrderTypeCache); }
clearMembershipsCache(): void { this.clearAnySpecificCache("Memberships", this.cvApi.payments.ClearMembershipCache); }
clearMembershipAdZoneAccessesCache(): void { this.clearAnySpecificCache("MembershipAdZoneAccesses", this.cvApi.payments.ClearMembershipAdZoneAccessCache); }
clearMembershipAdZoneAccessByLevelsCache(): void { this.clearAnySpecificCache("MembershipAdZoneAccessByLevels", this.cvApi.payments.ClearMembershipAdZoneAccessByLevelCache); }
clearMembershipLevelsCache(): void { this.clearAnySpecificCache("MembershipLevels", this.cvApi.payments.ClearMembershipLevelCache); }
clearMembershipRepeatTypesCache(): void { this.clearAnySpecificCache("MembershipRepeatTypes", this.cvApi.payments.ClearMembershipRepeatTypeCache); }
clearPaymentsCache(): void { this.clearAnySpecificCache("Payments", this.cvApi.payments.ClearPaymentCache); }
clearPaymentMethodsCache(): void { this.clearAnySpecificCache("PaymentMethods", this.cvApi.payments.ClearPaymentMethodCache); }
clearPaymentStatusesCache(): void { this.clearAnySpecificCache("PaymentStatuses", this.cvApi.payments.ClearPaymentStatusCache); }
clearPaymentTypesCache(): void { this.clearAnySpecificCache("PaymentTypes", this.cvApi.payments.ClearPaymentTypeCache); }
clearRepeatTypesCache(): void { this.clearAnySpecificCache("RepeatTypes", this.cvApi.payments.ClearRepeatTypeCache); }
clearSalesInvoicePaymentsCache(): void { this.clearAnySpecificCache("SalesInvoicePayments", this.cvApi.payments.ClearSalesInvoicePaymentCache); }
clearSalesOrderPaymentsCache(): void { this.clearAnySpecificCache("SalesOrderPayments", this.cvApi.payments.ClearSalesOrderPaymentCache); }
clearSalesReturnPaymentsCache(): void { this.clearAnySpecificCache("SalesReturnPayments", this.cvApi.payments.ClearSalesReturnPaymentCache); }
clearSubscriptionsCache(): void { this.clearAnySpecificCache("Subscriptions", this.cvApi.payments.ClearSubscriptionCache); }
clearSubscriptionHistoriesCache(): void { this.clearAnySpecificCache("SubscriptionHistories", this.cvApi.payments.ClearSubscriptionHistoryCache); }
clearSubscriptionStatusesCache(): void { this.clearAnySpecificCache("SubscriptionStatuses", this.cvApi.payments.ClearSubscriptionStatusCache); }
clearSubscriptionTypesCache(): void { this.clearAnySpecificCache("SubscriptionTypes", this.cvApi.payments.ClearSubscriptionTypeCache); }
clearSubscriptionTypeRepeatTypesCache(): void { this.clearAnySpecificCache("SubscriptionTypeRepeatTypes", this.cvApi.payments.ClearSubscriptionTypeRepeatTypeCache); }
clearWalletsCache(): void { this.clearAnySpecificCache("Wallets", this.cvApi.payments.ClearWalletCache); }
clearPricePointsCache(): void { this.clearAnySpecificCache("PricePoints", this.cvApi.pricing.ClearPricePointCache); }
clearPriceRoundingsCache(): void { this.clearAnySpecificCache("PriceRoundings", this.cvApi.pricing.ClearPriceRoundingCache); }
clearPriceRulesCache(): void { this.clearAnySpecificCache("PriceRules", this.cvApi.pricing.ClearPriceRuleCache); }
clearPriceRuleAccountsCache(): void { this.clearAnySpecificCache("PriceRuleAccounts", this.cvApi.pricing.ClearPriceRuleAccountCache); }
clearPriceRuleAccountTypesCache(): void { this.clearAnySpecificCache("PriceRuleAccountTypes", this.cvApi.pricing.ClearPriceRuleAccountTypeCache); }
clearPriceRuleBrandsCache(): void { this.clearAnySpecificCache("PriceRuleBrands", this.cvApi.pricing.ClearPriceRuleBrandCache); }
clearPriceRuleCategoriesCache(): void { this.clearAnySpecificCache("PriceRuleCategories", this.cvApi.pricing.ClearPriceRuleCategoryCache); }
clearPriceRuleCountriesCache(): void { this.clearAnySpecificCache("PriceRuleCountries", this.cvApi.pricing.ClearPriceRuleCountryCache); }
clearPriceRuleFranchisesCache(): void { this.clearAnySpecificCache("PriceRuleFranchises", this.cvApi.pricing.ClearPriceRuleFranchiseCache); }
clearPriceRuleManufacturersCache(): void { this.clearAnySpecificCache("PriceRuleManufacturers", this.cvApi.pricing.ClearPriceRuleManufacturerCache); }
clearPriceRuleProductsCache(): void { this.clearAnySpecificCache("PriceRuleProducts", this.cvApi.pricing.ClearPriceRuleProductCache); }
clearPriceRuleProductTypesCache(): void { this.clearAnySpecificCache("PriceRuleProductTypes", this.cvApi.pricing.ClearPriceRuleProductTypeCache); }
clearPriceRuleStoresCache(): void { this.clearAnySpecificCache("PriceRuleStores", this.cvApi.pricing.ClearPriceRuleStoreCache); }
clearPriceRuleUserRolesCache(): void { this.clearAnySpecificCache("PriceRuleUserRoles", this.cvApi.pricing.ClearPriceRuleUserRoleCache); }
clearPriceRuleVendorsCache(): void { this.clearAnySpecificCache("PriceRuleVendors", this.cvApi.pricing.ClearPriceRuleVendorCache); }
clearFutureImportsCache(): void { this.clearAnySpecificCache("FutureImports", this.cvApi.products.ClearFutureImportCache); }
clearFutureImportStatusesCache(): void { this.clearAnySpecificCache("FutureImportStatuses", this.cvApi.products.ClearFutureImportStatusCache); }
clearProductsCache(): void { this.clearAnySpecificCache("Products", this.cvApi.products.ClearProductCache); }
clearProductAssociationsCache(): void { this.clearAnySpecificCache("ProductAssociations", this.cvApi.products.ClearProductAssociationCache); }
clearProductAssociationTypesCache(): void { this.clearAnySpecificCache("ProductAssociationTypes", this.cvApi.products.ClearProductAssociationTypeCache); }
clearProductCategoriesCache(): void { this.clearAnySpecificCache("ProductCategories", this.cvApi.products.ClearProductCategoryCache); }
clearProductDownloadsCache(): void { this.clearAnySpecificCache("ProductDownloads", this.cvApi.products.ClearProductDownloadCache); }
clearProductDownloadTypesCache(): void { this.clearAnySpecificCache("ProductDownloadTypes", this.cvApi.products.ClearProductDownloadTypeCache); }
clearProductFilesCache(): void { this.clearAnySpecificCache("ProductFiles", this.cvApi.products.ClearProductFileCache); }
clearProductImagesCache(): void { this.clearAnySpecificCache("ProductImages", this.cvApi.products.ClearProductImageCache); }
clearProductImageTypesCache(): void { this.clearAnySpecificCache("ProductImageTypes", this.cvApi.products.ClearProductImageTypeCache); }
clearProductInventoryLocationSectionsCache(): void { this.clearAnySpecificCache("ProductInventoryLocationSections", this.cvApi.products.ClearProductInventoryLocationSectionCache); }
clearProductMembershipLevelsCache(): void { this.clearAnySpecificCache("ProductMembershipLevels", this.cvApi.products.ClearProductMembershipLevelCache); }
clearProductPricePointsCache(): void { this.clearAnySpecificCache("ProductPricePoints", this.cvApi.products.ClearProductPricePointCache); }
clearProductRestrictionsCache(): void { this.clearAnySpecificCache("ProductRestrictions", this.cvApi.products.ClearProductRestrictionCache); }
clearProductShipCarrierMethodsCache(): void { this.clearAnySpecificCache("ProductShipCarrierMethods", this.cvApi.products.ClearProductShipCarrierMethodCache); }
clearProductStatusesCache(): void { this.clearAnySpecificCache("ProductStatuses", this.cvApi.products.ClearProductStatusCache); }
clearProductSubscriptionTypesCache(): void { this.clearAnySpecificCache("ProductSubscriptionTypes", this.cvApi.products.ClearProductSubscriptionTypeCache); }
clearProductTypesCache(): void { this.clearAnySpecificCache("ProductTypes", this.cvApi.products.ClearProductTypeCache); }
clearPurchaseOrdersCache(): void { this.clearAnySpecificCache("PurchaseOrders", this.cvApi.purchasing.ClearPurchaseOrderCache); }
clearPurchaseOrderContactsCache(): void { this.clearAnySpecificCache("PurchaseOrderContacts", this.cvApi.purchasing.ClearPurchaseOrderContactCache); }
clearPurchaseOrderEventsCache(): void { this.clearAnySpecificCache("PurchaseOrderEvents", this.cvApi.purchasing.ClearPurchaseOrderEventCache); }
clearPurchaseOrderEventTypesCache(): void { this.clearAnySpecificCache("PurchaseOrderEventTypes", this.cvApi.purchasing.ClearPurchaseOrderEventTypeCache); }
clearPurchaseOrderFilesCache(): void { this.clearAnySpecificCache("PurchaseOrderFiles", this.cvApi.purchasing.ClearPurchaseOrderFileCache); }
clearPurchaseOrderItemsCache(): void { this.clearAnySpecificCache("PurchaseOrderItems", this.cvApi.purchasing.ClearPurchaseOrderItemCache); }
clearPurchaseOrderItemTargetsCache(): void { this.clearAnySpecificCache("PurchaseOrderItemTargets", this.cvApi.purchasing.ClearPurchaseOrderItemTargetCache); }
clearPurchaseOrderStatesCache(): void { this.clearAnySpecificCache("PurchaseOrderStates", this.cvApi.purchasing.ClearPurchaseOrderStateCache); }
clearPurchaseOrderStatusesCache(): void { this.clearAnySpecificCache("PurchaseOrderStatuses", this.cvApi.purchasing.ClearPurchaseOrderStatusCache); }
clearPurchaseOrderTypesCache(): void { this.clearAnySpecificCache("PurchaseOrderTypes", this.cvApi.purchasing.ClearPurchaseOrderTypeCache); }
clearSalesOrderPurchaseOrdersCache(): void { this.clearAnySpecificCache("SalesOrderPurchaseOrders", this.cvApi.purchasing.ClearSalesOrderPurchaseOrderCache); }
clearAnswersCache(): void { this.clearAnySpecificCache("Answers", this.cvApi.questionnaire.ClearAnswerCache); }
clearQuestionsCache(): void { this.clearAnySpecificCache("Questions", this.cvApi.questionnaire.ClearQuestionCache); }
clearQuestionOptionsCache(): void { this.clearAnySpecificCache("QuestionOptions", this.cvApi.questionnaire.ClearQuestionOptionCache); }
clearQuestionTypesCache(): void { this.clearAnySpecificCache("QuestionTypes", this.cvApi.questionnaire.ClearQuestionTypeCache); }
clearSalesQuotesCache(): void { this.clearAnySpecificCache("SalesQuotes", this.cvApi.quoting.ClearSalesQuoteCache); }
clearSalesQuoteCategoriesCache(): void { this.clearAnySpecificCache("SalesQuoteCategories", this.cvApi.quoting.ClearSalesQuoteCategoryCache); }
clearSalesQuoteContactsCache(): void { this.clearAnySpecificCache("SalesQuoteContacts", this.cvApi.quoting.ClearSalesQuoteContactCache); }
clearSalesQuoteEventsCache(): void { this.clearAnySpecificCache("SalesQuoteEvents", this.cvApi.quoting.ClearSalesQuoteEventCache); }
clearSalesQuoteEventTypesCache(): void { this.clearAnySpecificCache("SalesQuoteEventTypes", this.cvApi.quoting.ClearSalesQuoteEventTypeCache); }
clearSalesQuoteFilesCache(): void { this.clearAnySpecificCache("SalesQuoteFiles", this.cvApi.quoting.ClearSalesQuoteFileCache); }
clearSalesQuoteItemsCache(): void { this.clearAnySpecificCache("SalesQuoteItems", this.cvApi.quoting.ClearSalesQuoteItemCache); }
clearSalesQuoteItemTargetsCache(): void { this.clearAnySpecificCache("SalesQuoteItemTargets", this.cvApi.quoting.ClearSalesQuoteItemTargetCache); }
clearSalesQuoteSalesOrdersCache(): void { this.clearAnySpecificCache("SalesQuoteSalesOrders", this.cvApi.quoting.ClearSalesQuoteSalesOrderCache); }
clearSalesQuoteStatesCache(): void { this.clearAnySpecificCache("SalesQuoteStates", this.cvApi.quoting.ClearSalesQuoteStateCache); }
clearSalesQuoteStatusesCache(): void { this.clearAnySpecificCache("SalesQuoteStatuses", this.cvApi.quoting.ClearSalesQuoteStatusCache); }
clearSalesQuoteTypesCache(): void { this.clearAnySpecificCache("SalesQuoteTypes", this.cvApi.quoting.ClearSalesQuoteTypeCache); }
clearReportTypesCache(): void { this.clearAnySpecificCache("ReportTypes", this.cvApi.reporting.ClearReportTypeCache); }
clearSalesReturnsCache(): void { this.clearAnySpecificCache("SalesReturns", this.cvApi.returning.ClearSalesReturnCache); }
clearSalesReturnContactsCache(): void { this.clearAnySpecificCache("SalesReturnContacts", this.cvApi.returning.ClearSalesReturnContactCache); }
clearSalesReturnEventsCache(): void { this.clearAnySpecificCache("SalesReturnEvents", this.cvApi.returning.ClearSalesReturnEventCache); }
clearSalesReturnEventTypesCache(): void { this.clearAnySpecificCache("SalesReturnEventTypes", this.cvApi.returning.ClearSalesReturnEventTypeCache); }
clearSalesReturnFilesCache(): void { this.clearAnySpecificCache("SalesReturnFiles", this.cvApi.returning.ClearSalesReturnFileCache); }
clearSalesReturnItemsCache(): void { this.clearAnySpecificCache("SalesReturnItems", this.cvApi.returning.ClearSalesReturnItemCache); }
clearSalesReturnItemTargetsCache(): void { this.clearAnySpecificCache("SalesReturnItemTargets", this.cvApi.returning.ClearSalesReturnItemTargetCache); }
clearSalesReturnReasonsCache(): void { this.clearAnySpecificCache("SalesReturnReasons", this.cvApi.returning.ClearSalesReturnReasonCache); }
clearSalesReturnSalesOrdersCache(): void { this.clearAnySpecificCache("SalesReturnSalesOrders", this.cvApi.returning.ClearSalesReturnSalesOrderCache); }
clearSalesReturnStatesCache(): void { this.clearAnySpecificCache("SalesReturnStates", this.cvApi.returning.ClearSalesReturnStateCache); }
clearSalesReturnStatusesCache(): void { this.clearAnySpecificCache("SalesReturnStatuses", this.cvApi.returning.ClearSalesReturnStatusCache); }
clearSalesReturnTypesCache(): void { this.clearAnySpecificCache("SalesReturnTypes", this.cvApi.returning.ClearSalesReturnTypeCache); }
clearReviewsCache(): void { this.clearAnySpecificCache("Reviews", this.cvApi.reviews.ClearReviewCache); }
clearReviewTypesCache(): void { this.clearAnySpecificCache("ReviewTypes", this.cvApi.reviews.ClearReviewTypeCache); }
clearSalesGroupsCache(): void { this.clearAnySpecificCache("SalesGroups", this.cvApi.sales.ClearSalesGroupCache); }
clearSalesItemTargetTypesCache(): void { this.clearAnySpecificCache("SalesItemTargetTypes", this.cvApi.sales.ClearSalesItemTargetTypeCache); }
clearSampleRequestsCache(): void { this.clearAnySpecificCache("SampleRequests", this.cvApi.sampling.ClearSampleRequestCache); }
clearSampleRequestContactsCache(): void { this.clearAnySpecificCache("SampleRequestContacts", this.cvApi.sampling.ClearSampleRequestContactCache); }
clearSampleRequestEventsCache(): void { this.clearAnySpecificCache("SampleRequestEvents", this.cvApi.sampling.ClearSampleRequestEventCache); }
clearSampleRequestEventTypesCache(): void { this.clearAnySpecificCache("SampleRequestEventTypes", this.cvApi.sampling.ClearSampleRequestEventTypeCache); }
clearSampleRequestFilesCache(): void { this.clearAnySpecificCache("SampleRequestFiles", this.cvApi.sampling.ClearSampleRequestFileCache); }
clearSampleRequestItemsCache(): void { this.clearAnySpecificCache("SampleRequestItems", this.cvApi.sampling.ClearSampleRequestItemCache); }
clearSampleRequestItemTargetsCache(): void { this.clearAnySpecificCache("SampleRequestItemTargets", this.cvApi.sampling.ClearSampleRequestItemTargetCache); }
clearSampleRequestStatesCache(): void { this.clearAnySpecificCache("SampleRequestStates", this.cvApi.sampling.ClearSampleRequestStateCache); }
clearSampleRequestStatusesCache(): void { this.clearAnySpecificCache("SampleRequestStatuses", this.cvApi.sampling.ClearSampleRequestStatusCache); }
clearSampleRequestTypesCache(): void { this.clearAnySpecificCache("SampleRequestTypes", this.cvApi.sampling.ClearSampleRequestTypeCache); }
clearAppointmentsCache(): void { this.clearAnySpecificCache("Appointments", this.cvApi.scheduling.ClearAppointmentCache); }
clearAppointmentStatusesCache(): void { this.clearAnySpecificCache("AppointmentStatuses", this.cvApi.scheduling.ClearAppointmentStatusCache); }
clearAppointmentTypesCache(): void { this.clearAnySpecificCache("AppointmentTypes", this.cvApi.scheduling.ClearAppointmentTypeCache); }
clearCalendarsCache(): void { this.clearAnySpecificCache("Calendars", this.cvApi.scheduling.ClearCalendarCache); }
clearCalendarAppointmentsCache(): void { this.clearAnySpecificCache("CalendarAppointments", this.cvApi.scheduling.ClearCalendarAppointmentCache); }
clearScoutsCache(): void { this.clearAnySpecificCache("Scouts", this.cvApi.scouting.ClearScoutCache); }
clearScoutCategoriesCache(): void { this.clearAnySpecificCache("ScoutCategories", this.cvApi.scouting.ClearScoutCategoryCache); }
clearScoutCategoryTypesCache(): void { this.clearAnySpecificCache("ScoutCategoryTypes", this.cvApi.scouting.ClearScoutCategoryTypeCache); }
clearPackagesCache(): void { this.clearAnySpecificCache("Packages", this.cvApi.shipping.ClearPackageCache); }
clearPackageTypesCache(): void { this.clearAnySpecificCache("PackageTypes", this.cvApi.shipping.ClearPackageTypeCache); }
clearRateQuotesCache(): void { this.clearAnySpecificCache("RateQuotes", this.cvApi.shipping.ClearRateQuoteCache); }
clearShipCarriersCache(): void { this.clearAnySpecificCache("ShipCarriers", this.cvApi.shipping.ClearShipCarrierCache); }
clearShipCarrierMethodsCache(): void { this.clearAnySpecificCache("ShipCarrierMethods", this.cvApi.shipping.ClearShipCarrierMethodCache); }
clearShipmentsCache(): void { this.clearAnySpecificCache("Shipments", this.cvApi.shipping.ClearShipmentCache); }
clearShipmentEventsCache(): void { this.clearAnySpecificCache("ShipmentEvents", this.cvApi.shipping.ClearShipmentEventCache); }
clearShipmentStatusesCache(): void { this.clearAnySpecificCache("ShipmentStatuses", this.cvApi.shipping.ClearShipmentStatusCache); }
clearShipmentTypesCache(): void { this.clearAnySpecificCache("ShipmentTypes", this.cvApi.shipping.ClearShipmentTypeCache); }
clearCartsCache(): void { this.clearAnySpecificCache("Carts", this.cvApi.shopping.ClearCartCache); }
clearCartContactsCache(): void { this.clearAnySpecificCache("CartContacts", this.cvApi.shopping.ClearCartContactCache); }
clearCartEventsCache(): void { this.clearAnySpecificCache("CartEvents", this.cvApi.shopping.ClearCartEventCache); }
clearCartEventTypesCache(): void { this.clearAnySpecificCache("CartEventTypes", this.cvApi.shopping.ClearCartEventTypeCache); }
clearCartFilesCache(): void { this.clearAnySpecificCache("CartFiles", this.cvApi.shopping.ClearCartFileCache); }
clearCartItemsCache(): void { this.clearAnySpecificCache("CartItems", this.cvApi.shopping.ClearCartItemCache); }
clearCartItemTargetsCache(): void { this.clearAnySpecificCache("CartItemTargets", this.cvApi.shopping.ClearCartItemTargetCache); }
clearCartStatesCache(): void { this.clearAnySpecificCache("CartStates", this.cvApi.shopping.ClearCartStateCache); }
clearCartStatusesCache(): void { this.clearAnySpecificCache("CartStatuses", this.cvApi.shopping.ClearCartStatusCache); }
clearCartTypesCache(): void { this.clearAnySpecificCache("CartTypes", this.cvApi.shopping.ClearCartTypeCache); }
clearSiteDomainsCache(): void { this.clearAnySpecificCache("SiteDomains", this.cvApi.stores.ClearSiteDomainCache); }
clearSiteDomainSocialProvidersCache(): void { this.clearAnySpecificCache("SiteDomainSocialProviders", this.cvApi.stores.ClearSiteDomainSocialProviderCache); }
clearSocialProvidersCache(): void { this.clearAnySpecificCache("SocialProviders", this.cvApi.stores.ClearSocialProviderCache); }
clearStoresCache(): void { this.clearAnySpecificCache("Stores", this.cvApi.stores.ClearStoreCache); }
clearStoreAccountsCache(): void { this.clearAnySpecificCache("StoreAccounts", this.cvApi.stores.ClearStoreAccountCache); }
clearStoreBadgesCache(): void { this.clearAnySpecificCache("StoreBadges", this.cvApi.stores.ClearStoreBadgeCache); }
clearStoreCategoriesCache(): void { this.clearAnySpecificCache("StoreCategories", this.cvApi.stores.ClearStoreCategoryCache); }
clearStoreContactsCache(): void { this.clearAnySpecificCache("StoreContacts", this.cvApi.stores.ClearStoreContactCache); }
clearStoreCountriesCache(): void { this.clearAnySpecificCache("StoreCountries", this.cvApi.stores.ClearStoreCountryCache); }
clearStoreDistrictsCache(): void { this.clearAnySpecificCache("StoreDistricts", this.cvApi.stores.ClearStoreDistrictCache); }
clearStoreImagesCache(): void { this.clearAnySpecificCache("StoreImages", this.cvApi.stores.ClearStoreImageCache); }
clearStoreImageTypesCache(): void { this.clearAnySpecificCache("StoreImageTypes", this.cvApi.stores.ClearStoreImageTypeCache); }
clearStoreInventoryLocationsCache(): void { this.clearAnySpecificCache("StoreInventoryLocations", this.cvApi.stores.ClearStoreInventoryLocationCache); }
clearStoreInventoryLocationTypesCache(): void { this.clearAnySpecificCache("StoreInventoryLocationTypes", this.cvApi.stores.ClearStoreInventoryLocationTypeCache); }
clearStoreManufacturersCache(): void { this.clearAnySpecificCache("StoreManufacturers", this.cvApi.stores.ClearStoreManufacturerCache); }
clearStoreProductsCache(): void { this.clearAnySpecificCache("StoreProducts", this.cvApi.stores.ClearStoreProductCache); }
clearStoreRegionsCache(): void { this.clearAnySpecificCache("StoreRegions", this.cvApi.stores.ClearStoreRegionCache); }
clearStoreSubscriptionsCache(): void { this.clearAnySpecificCache("StoreSubscriptions", this.cvApi.stores.ClearStoreSubscriptionCache); }
clearStoreTypesCache(): void { this.clearAnySpecificCache("StoreTypes", this.cvApi.stores.ClearStoreTypeCache); }
clearStoreUsersCache(): void { this.clearAnySpecificCache("StoreUsers", this.cvApi.stores.ClearStoreUserCache); }
clearStoreVendorsCache(): void { this.clearAnySpecificCache("StoreVendors", this.cvApi.stores.ClearStoreVendorCache); }
clearImportExportMappingsCache(): void { this.clearAnySpecificCache("ImportExportMappings", this.cvApi.structure.ClearImportExportMappingCache); }
clearNotesCache(): void { this.clearAnySpecificCache("Notes", this.cvApi.structure.ClearNoteCache); }
clearNoteTypesCache(): void { this.clearAnySpecificCache("NoteTypes", this.cvApi.structure.ClearNoteTypeCache); }
clearRecordVersionsCache(): void { this.clearAnySpecificCache("RecordVersions", this.cvApi.structure.ClearRecordVersionCache); }
clearRecordVersionTypesCache(): void { this.clearAnySpecificCache("RecordVersionTypes", this.cvApi.structure.ClearRecordVersionTypeCache); }
clearSettingsCache(): void { this.clearAnySpecificCache("Settings", this.cvApi.structure.ClearSettingCache); }
clearSettingGroupsCache(): void { this.clearAnySpecificCache("SettingGroups", this.cvApi.structure.ClearSettingGroupCache); }
clearSettingTypesCache(): void { this.clearAnySpecificCache("SettingTypes", this.cvApi.structure.ClearSettingTypeCache); }
clearEventLogsCache(): void { this.clearAnySpecificCache("EventLogs", this.cvApi.structure.ClearEventLogCache); }
clearHistoricalTaxRatesCache(): void { this.clearAnySpecificCache("HistoricalTaxRates", this.cvApi.tax.ClearHistoricalTaxRateCache); }
clearTaxCountriesCache(): void { this.clearAnySpecificCache("TaxCountries", this.cvApi.tax.ClearTaxCountryCache); }
clearTaxDistrictsCache(): void { this.clearAnySpecificCache("TaxDistricts", this.cvApi.tax.ClearTaxDistrictCache); }
clearTaxRegionsCache(): void { this.clearAnySpecificCache("TaxRegions", this.cvApi.tax.ClearTaxRegionCache); }
clearCampaignsCache(): void { this.clearAnySpecificCache("Campaigns", this.cvApi.tracking.ClearCampaignCache); }
clearCampaignAdsCache(): void { this.clearAnySpecificCache("CampaignAds", this.cvApi.tracking.ClearCampaignAdCache); }
clearCampaignStatusesCache(): void { this.clearAnySpecificCache("CampaignStatuses", this.cvApi.tracking.ClearCampaignStatusCache); }
clearCampaignTypesCache(): void { this.clearAnySpecificCache("CampaignTypes", this.cvApi.tracking.ClearCampaignTypeCache); }
clearEventsCache(): void { this.clearAnySpecificCache("Events", this.cvApi.tracking.ClearEventCache); }
clearEventStatusesCache(): void { this.clearAnySpecificCache("EventStatuses", this.cvApi.tracking.ClearEventStatusCache); }
clearEventTypesCache(): void { this.clearAnySpecificCache("EventTypes", this.cvApi.tracking.ClearEventTypeCache); }
clearIPOrganizationsCache(): void { this.clearAnySpecificCache("IPOrganizations", this.cvApi.tracking.ClearIPOrganizationCache); }
clearIPOrganizationStatusesCache(): void { this.clearAnySpecificCache("IPOrganizationStatuses", this.cvApi.tracking.ClearIPOrganizationStatusCache); }
clearPageViewsCache(): void { this.clearAnySpecificCache("PageViews", this.cvApi.tracking.ClearPageViewCache); }
clearPageViewEventsCache(): void { this.clearAnySpecificCache("PageViewEvents", this.cvApi.tracking.ClearPageViewEventCache); }
clearPageViewStatusesCache(): void { this.clearAnySpecificCache("PageViewStatuses", this.cvApi.tracking.ClearPageViewStatusCache); }
clearPageViewTypesCache(): void { this.clearAnySpecificCache("PageViewTypes", this.cvApi.tracking.ClearPageViewTypeCache); }
clearVisitsCache(): void { this.clearAnySpecificCache("Visits", this.cvApi.tracking.ClearVisitCache); }
clearVisitorsCache(): void { this.clearAnySpecificCache("Visitors", this.cvApi.tracking.ClearVisitorCache); }
clearVisitStatusesCache(): void { this.clearAnySpecificCache("VisitStatuses", this.cvApi.tracking.ClearVisitStatusCache); }
clearVendorsCache(): void { this.clearAnySpecificCache("Vendors", this.cvApi.vendors.ClearVendorCache); }
clearVendorAccountsCache(): void { this.clearAnySpecificCache("VendorAccounts", this.cvApi.vendors.ClearVendorAccountCache); }
clearVendorImagesCache(): void { this.clearAnySpecificCache("VendorImages", this.cvApi.vendors.ClearVendorImageCache); }
clearVendorImageTypesCache(): void { this.clearAnySpecificCache("VendorImageTypes", this.cvApi.vendors.ClearVendorImageTypeCache); }
clearVendorManufacturersCache(): void { this.clearAnySpecificCache("VendorManufacturers", this.cvApi.vendors.ClearVendorManufacturerCache); }
clearVendorProductsCache(): void { this.clearAnySpecificCache("VendorProducts", this.cvApi.vendors.ClearVendorProductCache); }
clearVendorTypesCache(): void { this.clearAnySpecificCache("VendorTypes", this.cvApi.vendors.ClearVendorTypeCache); }
private clearAnySpecificCache(name: string, promise: () => ng.IHttpPromise<boolean>): void {
this.setRunning(`Clearing ${name}...`);
promise().then(response => {
if (!response || !response.data) {
this.finishRunning(false, `There was an issue clearing ${name}.`);
return;
}
this.finishRunning();
}, result => this.finishRunning(true, result)).catch(reason => this.finishRunning(true, reason));
}
// Events
// <None>
// Constructor
constructor(
private readonly $translate: ng.translate.ITranslateService,
private readonly $q: ng.IQService,
protected readonly cefConfig: core.CefConfig,
private readonly cvApi: api.ICEFAPI,
private readonly cvMessageModalFactory: modals.IMessageModalFactory) {
super(cefConfig);
}
}
adminApp.directive("clearCacheButtonsWidget", ($filter: ng.IFilterService): ng.IDirective => ({
restrict: "EA",
templateUrl: $filter("corsLink")("/framework/admin/controls/system/widgets/clearCacheButtonsWidget.html", "ui"),
controller: ClearCacheButtonsWidgetController,
controllerAs: "clearCacheButtonsWidgetCtrl"
}));
}
