// <autogenerated>
// <copyright file="IFranchiseModel.generated.cs" company="clarity-ventures.com">
// Copyright (c) 2016-2023 clarity-ventures.com. All rights reserved.
// </copyright>
// <summary>Implements the IModel Interfaces generated to provide base setups.</summary>
// <remarks>This file was auto-generated by IModels.tt, changes to this
// file will be overwritten automatically when the T4 template is run again.</remarks>
// </autogenerated>
// ReSharper disable BadEmptyBracesLineBreaks
#nullable enable
namespace Clarity.Ecommerce.Interfaces.Models
{
    /// <summary>Interface for franchise model.</summary>
    /// <seealso cref="INameableBaseModel"/>
    /// <seealso cref="IAmFilterableByAccountModel{IFranchiseAccountModel}"/>
    /// <seealso cref="IAmFilterableByBrandModel{IBrandFranchiseModel}"/>
    /// <seealso cref="IAmFilterableByCategoryModel{IFranchiseCategoryModel}"/>
    /// <seealso cref="IAmFilterableByManufacturerModel{IFranchiseManufacturerModel}"/>
    /// <seealso cref="IAmFilterableByProductModel{IFranchiseProductModel}"/>
    /// <seealso cref="IAmFilterableByStoreModel{IFranchiseStoreModel}"/>
    /// <seealso cref="IAmFilterableByUserModel{IFranchiseUserModel}"/>
    /// <seealso cref="IAmFilterableByVendorModel{IFranchiseVendorModel}"/>
    /// <seealso cref="IHaveATypeBaseModel{ITypeModel}"/>
    /// <seealso cref="IHaveOrderMinimumsBaseModel"/>
    /// <seealso cref="IHaveFreeShippingMinimumsBaseModel"/>
    /// <seealso cref="IHaveImagesBaseModel{IFranchiseImageModel,ITypeModel}"/>
    /// <seealso cref="IHaveNotesBaseModel"/>
    public partial interface IFranchiseModel
        : INameableBaseModel
            , IAmFilterableByAccountModel<IFranchiseAccountModel>
            , IAmFilterableByBrandModel<IBrandFranchiseModel>
            , IAmFilterableByCategoryModel<IFranchiseCategoryModel>
            , IAmFilterableByManufacturerModel<IFranchiseManufacturerModel>
            , IAmFilterableByProductModel<IFranchiseProductModel>
            , IAmFilterableByStoreModel<IFranchiseStoreModel>
            , IAmFilterableByUserModel<IFranchiseUserModel>
            , IAmFilterableByVendorModel<IFranchiseVendorModel>
            , IHaveATypeBaseModel<ITypeModel>
            , IHaveOrderMinimumsBaseModel
            , IHaveFreeShippingMinimumsBaseModel
            , IHaveImagesBaseModel<IFranchiseImageModel, ITypeModel>
            , IHaveNotesBaseModel
    {
    }
}
