// <autogenerated>
// <copyright file="Mapping.Auctions.LotGroup.cs" company="clarity-ventures.com">
// Copyright (c) 2016-2023 clarity-ventures.com. All rights reserved.
// </copyright>
// <summary>Implements the Auctions section of the Mapping class</summary>
// <remarks>This file was auto-generated by Mapping.tt, changes to this
// file will be overwritten automatically when the T4 template is run again</remarks>
// </autogenerated>
// ReSharper disable CyclomaticComplexity, FunctionComplexityOverflow, InvokeAsExtensionMethod, MergeCastWithTypeCheck
// ReSharper disable MissingLinebreak, RedundantDelegateInvoke, RedundantUsingDirective
#pragma warning disable CS0618 // Ignore Obsolete warnings
#nullable enable
namespace Clarity.Ecommerce.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Linq.Expressions;
    using DataModel;
    using Interfaces.DataModel;
    using Interfaces.Models;
    using LinqKit;
    using MoreLinq;
    using Utilities;

    public static partial class ModelMapperForLotGroup
    {
        public sealed class AnonLotGroup : LotGroup
        {
        }

        public static readonly Func<LotGroup?, string?, ILotGroupModel?> MapLotGroupModelFromEntityFull = CreateLotGroupModelFromEntityFull;

        public static readonly Func<LotGroup?, string?, ILotGroupModel?> MapLotGroupModelFromEntityLite = CreateLotGroupModelFromEntityLite;

        public static readonly Func<LotGroup?, string?, ILotGroupModel?> MapLotGroupModelFromEntityList = CreateLotGroupModelFromEntityList;

        public static Func<ILotGroup, ILotGroupModel, string?, ILotGroupModel>? CreateLotGroupModelFromEntityHooksFull { get; set; }

        public static Func<ILotGroup, ILotGroupModel, string?, ILotGroupModel>? CreateLotGroupModelFromEntityHooksLite { get; set; }

        public static Func<ILotGroup, ILotGroupModel, string?, ILotGroupModel>? CreateLotGroupModelFromEntityHooksList { get; set; }

        public static Expression<Func<LotGroup, AnonLotGroup>>? PreBuiltLotGroupSQLSelectorFull { get; set; }

        public static Expression<Func<LotGroup, AnonLotGroup>>? PreBuiltLotGroupSQLSelectorLite { get; set; }

        public static Expression<Func<LotGroup, AnonLotGroup>>? PreBuiltLotGroupSQLSelectorList { get; set; }

        /// <summary>An <see cref="ILotGroupModel"/> extension method that creates a(n) <see cref="LotGroup"/> entity.</summary>
        /// <param name="model">            The model to act on.</param>
        /// <param name="timestamp">        The timestamp Date/Time.</param>
        /// <param name="contextProfileName">Name of the context profile.</param>
        /// <returns>The new <see cref="LotGroup"/> entity.</returns>
        public static ILotGroup CreateLotGroupEntity(
            this ILotGroupModel model,
            DateTime timestamp,
            string? contextProfileName)
        {
            // Create the object and Map the Inherited Properties
            return Contract.RequiresNotNull(model)
                .CreateEntityTypableBase<ILotGroupModel, LotGroup>(timestamp, contextProfileName)
                // Use the Update method to map non-inherited properties
                .UpdateLotGroupFromModel(model, timestamp, null);
        }

        /// <summary>An <see cref="ILotGroupModel"/> extension method that updates a(n) <see cref="LotGroup"/> entity.</summary>
        /// <param name="entity">         The entity to act on.</param>
        /// <param name="model">          The model to read from.</param>
        /// <param name="timestamp">      The timestamp Date/Time.</param>
        /// <param name="updateTimestamp">The update timestamp Date/Time.</param>
        /// <returns>The updated <see cref="LotGroup"/> entity.</returns>
        public static ILotGroup UpdateLotGroupFromModel(
            this ILotGroup entity,
            ILotGroupModel model,
            DateTime timestamp,
            DateTime? updateTimestamp)
        {
            // Map the Inherited Properties
            entity = Contract.RequiresNotNull(entity)
                .MapTypableBaseModelPropertiesToEntity(Contract.RequiresNotNull(model));
            // Finally, update the timestamp
            entity.UpdatedDate = updateTimestamp == null || updateTimestamp == DateTime.MinValue ? null : updateTimestamp;
            // Return
            return entity;
        }

        public static void GenLotGroupSQLSelectorFull()
        {
            PreBuiltLotGroupSQLSelectorFull = x => x == null ? null! : new AnonLotGroup
            {
                DisplayName = x.DisplayName,
                SortOrder = x.SortOrder,
                TranslationKey = x.TranslationKey,
                Name = x.Name,
                Description = x.Description,
                ID = x.ID,
                CustomKey = x.CustomKey,
                CreatedDate = x.CreatedDate,
                UpdatedDate = x.UpdatedDate,
                Active = x.Active,
                Hash = x.Hash,
                JsonAttributes = x.JsonAttributes,
            };
        }

        public static void GenLotGroupSQLSelectorLite()
        {
            PreBuiltLotGroupSQLSelectorLite = x => x == null ? null! : new AnonLotGroup
            {
                DisplayName = x.DisplayName,
                SortOrder = x.SortOrder,
                TranslationKey = x.TranslationKey,
                Name = x.Name,
                Description = x.Description,
                ID = x.ID,
                CustomKey = x.CustomKey,
                CreatedDate = x.CreatedDate,
                UpdatedDate = x.UpdatedDate,
                Active = x.Active,
                Hash = x.Hash,
                JsonAttributes = x.JsonAttributes,
            };
        }

        public static void GenLotGroupSQLSelectorList()
        {
            PreBuiltLotGroupSQLSelectorList = x => x == null ? null! : new AnonLotGroup
            {
                DisplayName = x.DisplayName,
                SortOrder = x.SortOrder,
                TranslationKey = x.TranslationKey,
                Name = x.Name,
                ID = x.ID,
                CustomKey = x.CustomKey,
                CreatedDate = x.CreatedDate,
                Active = x.Active,
                Hash = x.Hash,
                JsonAttributes = x.JsonAttributes,
            };
        }

        public static IEnumerable<ILotGroupModel> SelectFullLotGroupAndMapToLotGroupModel(
            this IQueryable<LotGroup> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltLotGroupSQLSelectorFull == null);
            return dbSetWithFilters
                .AsExpandable()
                .Select(PreBuiltLotGroupSQLSelectorFull!.Compile())
                .ToList()
                .Select(x => CreateLotGroupModelFromEntityFull(x, contextProfileName))!;
        }

        public static IEnumerable<ILotGroupModel> SelectLiteLotGroupAndMapToLotGroupModel(
            this IQueryable<LotGroup> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltLotGroupSQLSelectorLite == null);
            return dbSetWithFilters
                .AsExpandable()
                .Select(PreBuiltLotGroupSQLSelectorLite!.Compile())
                .ToList()
                .Select(x => CreateLotGroupModelFromEntityLite(x, contextProfileName))!;
        }

        public static IEnumerable<ILotGroupModel> SelectListLotGroupAndMapToLotGroupModel(
            this IQueryable<LotGroup> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltLotGroupSQLSelectorList == null);
            return dbSetWithFilters
                .AsExpandable()
                .Select(PreBuiltLotGroupSQLSelectorList!.Compile())
                .ToList()
                .Select(x => CreateLotGroupModelFromEntityList(x, contextProfileName))!;
        }

        public static ILotGroupModel? SelectFirstFullLotGroupAndMapToLotGroupModel(
            this IQueryable<LotGroup> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltLotGroupSQLSelectorFull == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltLotGroupSQLSelectorFull!.Compile())
                .ToList()
                .Select(x => CreateLotGroupModelFromEntityFull(x, contextProfileName))
                .FirstOrDefault();
        }

        public static ILotGroupModel? SelectFirstListLotGroupAndMapToLotGroupModel(
            this IQueryable<LotGroup> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltLotGroupSQLSelectorList == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltLotGroupSQLSelectorList!.Compile())
                .ToList()
                .Select(x => CreateLotGroupModelFromEntityList(x, contextProfileName))
                .FirstOrDefault();
        }

        public static ILotGroupModel? SelectSingleFullLotGroupAndMapToLotGroupModel(
            this IQueryable<LotGroup> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltLotGroupSQLSelectorFull == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltLotGroupSQLSelectorFull!.Compile())
                .ToList()
                .Select(x => CreateLotGroupModelFromEntityFull(x, contextProfileName))
                .SingleOrDefault();
        }

        public static ILotGroupModel? SelectSingleLiteLotGroupAndMapToLotGroupModel(
            this IQueryable<LotGroup> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltLotGroupSQLSelectorLite == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltLotGroupSQLSelectorLite!.Compile())
                .ToList()
                .Select(x => CreateLotGroupModelFromEntityLite(x, contextProfileName))
                .SingleOrDefault();
        }

        public static ILotGroupModel? SelectSingleListLotGroupAndMapToLotGroupModel(
            this IQueryable<LotGroup> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltLotGroupSQLSelectorList == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltLotGroupSQLSelectorList!.Compile())
                .ToList()
                .Select(x => CreateLotGroupModelFromEntityList(x, contextProfileName))
                .SingleOrDefault();
        }

        public static (IEnumerable<ILotGroupModel> results, int totalPages, int totalCount) SelectFullLotGroupAndMapToLotGroupModel(
            this IQueryable<LotGroup> dbSetWithFilters,
            Paging? paging,
            Sort[]? sorts,
            Grouping[]? groupings,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltLotGroupSQLSelectorFull == null);
            return (dbSetWithFilters
                    .AsExpandable()
                    .ApplySorting(sorts, groupings, contextProfileName)
                    .FilterByPaging(paging, out var totalPages, out var totalCount)
                    .Select(PreBuiltLotGroupSQLSelectorFull!.Compile())
                    .ToList()
                    .Select(x => CreateLotGroupModelFromEntityFull(x, contextProfileName)),
                totalPages,
                totalCount)!;
        }

        public static (IEnumerable<ILotGroupModel> results, int totalPages, int totalCount) SelectLiteLotGroupAndMapToLotGroupModel(
            this IQueryable<LotGroup> dbSetWithFilters,
            Paging? paging,
            Sort[]? sorts,
            Grouping[]? groupings,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltLotGroupSQLSelectorLite == null);
            return (dbSetWithFilters
                    .AsExpandable()
                    .ApplySorting(sorts, groupings, contextProfileName)
                    .FilterByPaging(paging, out var totalPages, out var totalCount)
                    .Select(PreBuiltLotGroupSQLSelectorLite!.Compile())
                    .ToList()
                    .Select(x => CreateLotGroupModelFromEntityLite(x, contextProfileName)),
                totalPages,
                totalCount)!;
        }

        public static (IEnumerable<ILotGroupModel> results, int totalPages, int totalCount) SelectListLotGroupAndMapToLotGroupModel(
            this IQueryable<LotGroup> dbSetWithFilters,
            Paging? paging,
            Sort[]? sorts,
            Grouping[]? groupings,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltLotGroupSQLSelectorList == null);
            return (dbSetWithFilters
                    .AsExpandable()
                    .ApplySorting(sorts, groupings, contextProfileName)
                    .FilterByPaging(paging, out var totalPages, out var totalCount)
                    .Select(PreBuiltLotGroupSQLSelectorList!.Compile())
                    .ToList()
                    .Select(x => CreateLotGroupModelFromEntityList(x, contextProfileName)),
                totalPages,
                totalCount)!;
        }

        public static ILotGroupModel? CreateLotGroupModelFromEntityFull(this ILotGroup? entity, string? contextProfileName)
        {
            return CreateLotGroupModelFromEntity(entity, MappingMode.Full, contextProfileName);
        }

        public static ILotGroupModel? CreateLotGroupModelFromEntityLite(this ILotGroup? entity, string? contextProfileName)
        {
            return CreateLotGroupModelFromEntity(entity, MappingMode.Lite, contextProfileName);
        }

        public static ILotGroupModel? CreateLotGroupModelFromEntityList(this ILotGroup? entity, string? contextProfileName)
        {
            return CreateLotGroupModelFromEntity(entity, MappingMode.List, contextProfileName);
        }

        public static ILotGroupModel? CreateLotGroupModelFromEntity(
            this ILotGroup? entity,
            MappingMode mode,
            string? contextProfileName)
        {
            if (entity == null) { return null; }
            // Map the Inherited Properties
            // ReSharper disable once InvokeAsExtensionMethod
            var model = BaseModelMapper.MapTypableBaseEntityPropertiesToModel(
                RegistryLoaderWrapper.GetInstance<ILotGroupModel>(contextProfileName),
                Contract.RequiresNotNull(entity),
                mode,
                contextProfileName);
            // Map this level's Properties
            switch (mode)
            {
                case MappingMode.Full: //////////////////////////////////////////////////////////////////////////////////////////////////////////////
                {
                    // LotGroup's Properties
                    // LotGroup's Related Objects
                    // LotGroup's Associated Objects
                    // Additional Mappings
                    if (CreateLotGroupModelFromEntityHooksFull != null) { model = CreateLotGroupModelFromEntityHooksFull(entity, model, contextProfileName); }
                    goto case MappingMode.Lite;
                }
                case MappingMode.Lite: //////////////////////////////////////////////////////////////////////////////////////////////////////////////
                {
                    // LotGroup's Properties
                    // LotGroup's Related Objects (Not Mapped unless Forced, or a flattening property)
                    // LotGroup's Associated Objects (Not Mapped unless Forced)
                    // Additional Mappings
                    if (CreateLotGroupModelFromEntityHooksLite != null) { model = CreateLotGroupModelFromEntityHooksLite(entity, model, contextProfileName); }
                    goto case MappingMode.List;
                }
                case MappingMode.List: //////////////////////////////////////////////////////////////////////////////////////////////////////////////
                default:
                {
                    // IHaveJsonAttributesBase Properties (Forced)
                    model.SerializableAttributes = entity.JsonAttributes.DeserializeAttributesDictionary();
                    // LotGroup's Properties
                    // LotGroup's Related Objects (Not Mapped unless Forced, or a flattening property)
                    // LotGroup's Associated Objects (Not Mapped unless Forced)
                    // Additional Mappings
                    if (CreateLotGroupModelFromEntityHooksList != null) { model = CreateLotGroupModelFromEntityHooksList(entity, model, contextProfileName); }
                    break;
                }
            } ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            // Finished!
            return model;
        }
    }
}
