// <autogenerated>
// <copyright file="Mapping.Geography.DistrictImage.cs" company="clarity-ventures.com">
// Copyright (c) 2016-2023 clarity-ventures.com. All rights reserved.
// </copyright>
// <summary>Implements the Geography section of the Mapping class</summary>
// <remarks>This file was auto-generated by Mapping.tt, changes to this
// file will be overwritten automatically when the T4 template is run again</remarks>
// </autogenerated>
// ReSharper disable CyclomaticComplexity, FunctionComplexityOverflow, InvokeAsExtensionMethod, MergeCastWithTypeCheck
// ReSharper disable MissingLinebreak, RedundantDelegateInvoke, RedundantUsingDirective
#pragma warning disable CS0618 // Ignore Obsolete warnings
#nullable enable
namespace Clarity.Ecommerce.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Linq.Expressions;
    using DataModel;
    using Interfaces.DataModel;
    using Interfaces.Models;
    using LinqKit;
    using MoreLinq;
    using Utilities;

    public static partial class ModelMapperForDistrictImage
    {
        public sealed class AnonDistrictImage : DistrictImage
        {
            // public new District? Master { get; set; }
        }

        public static readonly Func<DistrictImage?, string?, IDistrictImageModel?> MapDistrictImageModelFromEntityFull = CreateDistrictImageModelFromEntityFull;

        public static readonly Func<DistrictImage?, string?, IDistrictImageModel?> MapDistrictImageModelFromEntityLite = CreateDistrictImageModelFromEntityLite;

        public static readonly Func<DistrictImage?, string?, IDistrictImageModel?> MapDistrictImageModelFromEntityList = CreateDistrictImageModelFromEntityList;

        public static Func<IDistrictImage, IDistrictImageModel, string?, IDistrictImageModel>? CreateDistrictImageModelFromEntityHooksFull { get; set; }

        public static Func<IDistrictImage, IDistrictImageModel, string?, IDistrictImageModel>? CreateDistrictImageModelFromEntityHooksLite { get; set; }

        public static Func<IDistrictImage, IDistrictImageModel, string?, IDistrictImageModel>? CreateDistrictImageModelFromEntityHooksList { get; set; }

        public static Expression<Func<DistrictImage, AnonDistrictImage>>? PreBuiltDistrictImageSQLSelectorFull { get; set; }

        public static Expression<Func<DistrictImage, AnonDistrictImage>>? PreBuiltDistrictImageSQLSelectorLite { get; set; }

        public static Expression<Func<DistrictImage, AnonDistrictImage>>? PreBuiltDistrictImageSQLSelectorList { get; set; }

        /// <summary>An <see cref="IDistrictImageModel"/> extension method that creates a(n) <see cref="DistrictImage"/> entity.</summary>
        /// <param name="model">            The model to act on.</param>
        /// <param name="timestamp">        The timestamp Date/Time.</param>
        /// <param name="contextProfileName">Name of the context profile.</param>
        /// <returns>The new <see cref="DistrictImage"/> entity.</returns>
        public static IDistrictImage CreateDistrictImageEntity(
            this IDistrictImageModel model,
            DateTime timestamp,
            string? contextProfileName)
        {
            // Create the object and Map the Inherited Properties
            return Contract.RequiresNotNull(model)
                .CreateEntityFromModelNameableBase<IDistrictImageModel, DistrictImage>(timestamp, contextProfileName)
                // Use the Update method to map non-inherited properties
                .UpdateDistrictImageFromModel(model, timestamp, null);
        }

        /// <summary>An <see cref="IDistrictImageModel"/> extension method that updates a(n) <see cref="DistrictImage"/> entity.</summary>
        /// <param name="entity">         The entity to act on.</param>
        /// <param name="model">          The model to read from.</param>
        /// <param name="timestamp">      The timestamp Date/Time.</param>
        /// <param name="updateTimestamp">The update timestamp Date/Time.</param>
        /// <returns>The updated <see cref="DistrictImage"/> entity.</returns>
        public static IDistrictImage UpdateDistrictImageFromModel(
            this IDistrictImage entity,
            IDistrictImageModel model,
            DateTime timestamp,
            DateTime? updateTimestamp)
        {
            // Map the Inherited Properties
            entity = Contract.RequiresNotNull(entity)
                .MapNameableBaseModelPropertiesToEntity(Contract.RequiresNotNull(model));
            // DistrictImage Properties
            entity.Author = model.Author;
            entity.Copyright = model.Copyright;
            entity.DisplayName = model.DisplayName;
            entity.IsPrimary = model.IsPrimary;
            entity.Latitude = model.Latitude;
            entity.Location = model.Location;
            entity.Longitude = model.Longitude;
            entity.MediaDate = model.MediaDate;
            entity.OriginalBytes = model.OriginalBytes;
            entity.OriginalFileFormat = model.OriginalFileFormat;
            entity.OriginalFileName = model.OriginalFileName;
            entity.OriginalHeight = model.OriginalHeight;
            entity.OriginalIsStoredInDB = model.OriginalIsStoredInDB;
            entity.OriginalWidth = model.OriginalWidth;
            entity.SeoTitle = model.SeoTitle;
            entity.SortOrder = model.SortOrder;
            entity.ThumbnailBytes = model.ThumbnailBytes;
            entity.ThumbnailFileFormat = model.ThumbnailFileFormat;
            entity.ThumbnailFileName = model.ThumbnailFileName;
            entity.ThumbnailHeight = model.ThumbnailHeight;
            entity.ThumbnailIsStoredInDB = model.ThumbnailIsStoredInDB;
            entity.ThumbnailWidth = model.ThumbnailWidth;
            // DistrictImage's Related Objects
            // Finally, update the timestamp
            entity.UpdatedDate = updateTimestamp == null || updateTimestamp == DateTime.MinValue ? null : updateTimestamp;
            // Return
            return entity;
        }

        public static void GenDistrictImageSQLSelectorFull()
        {
            PreBuiltDistrictImageSQLSelectorFull = x => x == null ? null! : new AnonDistrictImage
            {
                MasterID = x.MasterID,
                TypeID = x.TypeID,
                Type = ModelMapperForDistrictImageType.PreBuiltDistrictImageTypeSQLSelectorList.Expand().Compile().Invoke(x.Type!),
                SortOrder = x.SortOrder,
                DisplayName = x.DisplayName,
                SeoTitle = x.SeoTitle,
                Author = x.Author,
                MediaDate = x.MediaDate,
                Copyright = x.Copyright,
                Location = x.Location,
                Latitude = x.Latitude,
                Longitude = x.Longitude,
                IsPrimary = x.IsPrimary,
                OriginalWidth = x.OriginalWidth,
                OriginalHeight = x.OriginalHeight,
                OriginalFileFormat = x.OriginalFileFormat,
                OriginalFileName = x.OriginalFileName,
                OriginalIsStoredInDB = x.OriginalIsStoredInDB,
                OriginalBytes = x.OriginalBytes,
                ThumbnailWidth = x.ThumbnailWidth,
                ThumbnailHeight = x.ThumbnailHeight,
                ThumbnailFileFormat = x.ThumbnailFileFormat,
                ThumbnailFileName = x.ThumbnailFileName,
                ThumbnailIsStoredInDB = x.ThumbnailIsStoredInDB,
                ThumbnailBytes = x.ThumbnailBytes,
                Name = x.Name,
                Description = x.Description,
                ID = x.ID,
                CustomKey = x.CustomKey,
                CreatedDate = x.CreatedDate,
                UpdatedDate = x.UpdatedDate,
                Active = x.Active,
                Hash = x.Hash,
                JsonAttributes = x.JsonAttributes,
            };
        }

        public static void GenDistrictImageSQLSelectorLite()
        {
            PreBuiltDistrictImageSQLSelectorLite = x => x == null ? null! : new AnonDistrictImage
            {
                MasterID = x.MasterID,
                TypeID = x.TypeID,
                Type = ModelMapperForDistrictImageType.PreBuiltDistrictImageTypeSQLSelectorList.Expand().Compile().Invoke(x.Type!),
                SortOrder = x.SortOrder,
                DisplayName = x.DisplayName,
                SeoTitle = x.SeoTitle,
                Author = x.Author,
                MediaDate = x.MediaDate,
                Copyright = x.Copyright,
                Location = x.Location,
                Latitude = x.Latitude,
                Longitude = x.Longitude,
                IsPrimary = x.IsPrimary,
                OriginalWidth = x.OriginalWidth,
                OriginalHeight = x.OriginalHeight,
                OriginalFileFormat = x.OriginalFileFormat,
                OriginalFileName = x.OriginalFileName,
                OriginalIsStoredInDB = x.OriginalIsStoredInDB,
                OriginalBytes = x.OriginalBytes,
                ThumbnailWidth = x.ThumbnailWidth,
                ThumbnailHeight = x.ThumbnailHeight,
                ThumbnailFileFormat = x.ThumbnailFileFormat,
                ThumbnailFileName = x.ThumbnailFileName,
                ThumbnailIsStoredInDB = x.ThumbnailIsStoredInDB,
                ThumbnailBytes = x.ThumbnailBytes,
                Name = x.Name,
                Description = x.Description,
                ID = x.ID,
                CustomKey = x.CustomKey,
                CreatedDate = x.CreatedDate,
                UpdatedDate = x.UpdatedDate,
                Active = x.Active,
                Hash = x.Hash,
                JsonAttributes = x.JsonAttributes,
            };
        }

        public static void GenDistrictImageSQLSelectorList()
        {
            PreBuiltDistrictImageSQLSelectorList = x => x == null ? null! : new AnonDistrictImage
            {
                MasterID = x.MasterID,
                TypeID = x.TypeID,
                Type = ModelMapperForDistrictImageType.PreBuiltDistrictImageTypeSQLSelectorList.Expand().Compile().Invoke(x.Type!), // For Flattening Properties (List)
                SortOrder = x.SortOrder,
                DisplayName = x.DisplayName,
                SeoTitle = x.SeoTitle,
                Author = x.Author,
                MediaDate = x.MediaDate,
                Copyright = x.Copyright,
                Location = x.Location,
                Latitude = x.Latitude,
                Longitude = x.Longitude,
                IsPrimary = x.IsPrimary,
                OriginalWidth = x.OriginalWidth,
                OriginalHeight = x.OriginalHeight,
                OriginalFileFormat = x.OriginalFileFormat,
                OriginalFileName = x.OriginalFileName,
                OriginalIsStoredInDB = x.OriginalIsStoredInDB,
                OriginalBytes = x.OriginalBytes,
                ThumbnailWidth = x.ThumbnailWidth,
                ThumbnailHeight = x.ThumbnailHeight,
                ThumbnailFileFormat = x.ThumbnailFileFormat,
                ThumbnailFileName = x.ThumbnailFileName,
                ThumbnailIsStoredInDB = x.ThumbnailIsStoredInDB,
                ThumbnailBytes = x.ThumbnailBytes,
                Name = x.Name,
                ID = x.ID,
                CustomKey = x.CustomKey,
                CreatedDate = x.CreatedDate,
                Active = x.Active,
                Hash = x.Hash,
                JsonAttributes = x.JsonAttributes,
            };
        }

        public static IEnumerable<IDistrictImageModel> SelectFullDistrictImageAndMapToDistrictImageModel(
            this IQueryable<DistrictImage> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltDistrictImageSQLSelectorFull == null);
            return dbSetWithFilters
                .AsExpandable()
                .Select(PreBuiltDistrictImageSQLSelectorFull!.Compile())
                .ToList()
                .Select(x => CreateDistrictImageModelFromEntityFull(x, contextProfileName))!;
        }

        public static IEnumerable<IDistrictImageModel> SelectLiteDistrictImageAndMapToDistrictImageModel(
            this IQueryable<DistrictImage> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltDistrictImageSQLSelectorLite == null);
            return dbSetWithFilters
                .AsExpandable()
                .Select(PreBuiltDistrictImageSQLSelectorLite!.Compile())
                .ToList()
                .Select(x => CreateDistrictImageModelFromEntityLite(x, contextProfileName))!;
        }

        public static IEnumerable<IDistrictImageModel> SelectListDistrictImageAndMapToDistrictImageModel(
            this IQueryable<DistrictImage> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltDistrictImageSQLSelectorList == null);
            return dbSetWithFilters
                .AsExpandable()
                .Select(PreBuiltDistrictImageSQLSelectorList!.Compile())
                .ToList()
                .Select(x => CreateDistrictImageModelFromEntityList(x, contextProfileName))!;
        }

        public static IDistrictImageModel? SelectFirstFullDistrictImageAndMapToDistrictImageModel(
            this IQueryable<DistrictImage> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltDistrictImageSQLSelectorFull == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltDistrictImageSQLSelectorFull!.Compile())
                .ToList()
                .Select(x => CreateDistrictImageModelFromEntityFull(x, contextProfileName))
                .FirstOrDefault();
        }

        public static IDistrictImageModel? SelectFirstListDistrictImageAndMapToDistrictImageModel(
            this IQueryable<DistrictImage> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltDistrictImageSQLSelectorList == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltDistrictImageSQLSelectorList!.Compile())
                .ToList()
                .Select(x => CreateDistrictImageModelFromEntityList(x, contextProfileName))
                .FirstOrDefault();
        }

        public static IDistrictImageModel? SelectSingleFullDistrictImageAndMapToDistrictImageModel(
            this IQueryable<DistrictImage> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltDistrictImageSQLSelectorFull == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltDistrictImageSQLSelectorFull!.Compile())
                .ToList()
                .Select(x => CreateDistrictImageModelFromEntityFull(x, contextProfileName))
                .SingleOrDefault();
        }

        public static IDistrictImageModel? SelectSingleLiteDistrictImageAndMapToDistrictImageModel(
            this IQueryable<DistrictImage> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltDistrictImageSQLSelectorLite == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltDistrictImageSQLSelectorLite!.Compile())
                .ToList()
                .Select(x => CreateDistrictImageModelFromEntityLite(x, contextProfileName))
                .SingleOrDefault();
        }

        public static IDistrictImageModel? SelectSingleListDistrictImageAndMapToDistrictImageModel(
            this IQueryable<DistrictImage> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltDistrictImageSQLSelectorList == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltDistrictImageSQLSelectorList!.Compile())
                .ToList()
                .Select(x => CreateDistrictImageModelFromEntityList(x, contextProfileName))
                .SingleOrDefault();
        }

        public static (IEnumerable<IDistrictImageModel> results, int totalPages, int totalCount) SelectFullDistrictImageAndMapToDistrictImageModel(
            this IQueryable<DistrictImage> dbSetWithFilters,
            Paging? paging,
            Sort[]? sorts,
            Grouping[]? groupings,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltDistrictImageSQLSelectorFull == null);
            return (dbSetWithFilters
                    .AsExpandable()
                    .ApplySorting(sorts, groupings, contextProfileName)
                    .FilterByPaging(paging, out var totalPages, out var totalCount)
                    .Select(PreBuiltDistrictImageSQLSelectorFull!.Compile())
                    .ToList()
                    .Select(x => CreateDistrictImageModelFromEntityFull(x, contextProfileName)),
                totalPages,
                totalCount)!;
        }

        public static (IEnumerable<IDistrictImageModel> results, int totalPages, int totalCount) SelectLiteDistrictImageAndMapToDistrictImageModel(
            this IQueryable<DistrictImage> dbSetWithFilters,
            Paging? paging,
            Sort[]? sorts,
            Grouping[]? groupings,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltDistrictImageSQLSelectorLite == null);
            return (dbSetWithFilters
                    .AsExpandable()
                    .ApplySorting(sorts, groupings, contextProfileName)
                    .FilterByPaging(paging, out var totalPages, out var totalCount)
                    .Select(PreBuiltDistrictImageSQLSelectorLite!.Compile())
                    .ToList()
                    .Select(x => CreateDistrictImageModelFromEntityLite(x, contextProfileName)),
                totalPages,
                totalCount)!;
        }

        public static (IEnumerable<IDistrictImageModel> results, int totalPages, int totalCount) SelectListDistrictImageAndMapToDistrictImageModel(
            this IQueryable<DistrictImage> dbSetWithFilters,
            Paging? paging,
            Sort[]? sorts,
            Grouping[]? groupings,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltDistrictImageSQLSelectorList == null);
            return (dbSetWithFilters
                    .AsExpandable()
                    .ApplySorting(sorts, groupings, contextProfileName)
                    .FilterByPaging(paging, out var totalPages, out var totalCount)
                    .Select(PreBuiltDistrictImageSQLSelectorList!.Compile())
                    .ToList()
                    .Select(x => CreateDistrictImageModelFromEntityList(x, contextProfileName)),
                totalPages,
                totalCount)!;
        }

        public static IDistrictImageModel? CreateDistrictImageModelFromEntityFull(this IDistrictImage? entity, string? contextProfileName)
        {
            return CreateDistrictImageModelFromEntity(entity, MappingMode.Full, contextProfileName);
        }

        public static IDistrictImageModel? CreateDistrictImageModelFromEntityLite(this IDistrictImage? entity, string? contextProfileName)
        {
            return CreateDistrictImageModelFromEntity(entity, MappingMode.Lite, contextProfileName);
        }

        public static IDistrictImageModel? CreateDistrictImageModelFromEntityList(this IDistrictImage? entity, string? contextProfileName)
        {
            return CreateDistrictImageModelFromEntity(entity, MappingMode.List, contextProfileName);
        }

        public static IDistrictImageModel? CreateDistrictImageModelFromEntity(
            this IDistrictImage? entity,
            MappingMode mode,
            string? contextProfileName)
        {
            if (entity == null) { return null; }
            // Map the Inherited Properties
            // ReSharper disable once InvokeAsExtensionMethod
            var model = BaseModelMapper.MapNameableBaseEntityPropertiesToModel(
                RegistryLoaderWrapper.GetInstance<IDistrictImageModel>(contextProfileName),
                Contract.RequiresNotNull(entity),
                mode,
                contextProfileName);
            // Map this level's Properties
            switch (mode)
            {
                case MappingMode.Full: //////////////////////////////////////////////////////////////////////////////////////////////////////////////
                {
                    // DistrictImage's Properties
                    // DistrictImage's Related Objects
                    // DistrictImage's Associated Objects
                    // Additional Mappings
                    if (CreateDistrictImageModelFromEntityHooksFull != null) { model = CreateDistrictImageModelFromEntityHooksFull(entity, model, contextProfileName); }
                    goto case MappingMode.Lite;
                }
                case MappingMode.Lite: //////////////////////////////////////////////////////////////////////////////////////////////////////////////
                {
                    // DistrictImage's Properties
                    // IHaveATypeBase Properties (Forced)
                    model.Type = ModelMapperForDistrictImageType.CreateDistrictImageTypeModelFromEntityLite(entity.Type, contextProfileName);
                    // DistrictImage's Related Objects (Not Mapped unless Forced, or a flattening property)
                    // DistrictImage's Associated Objects (Not Mapped unless Forced)
                    // Additional Mappings
                    if (CreateDistrictImageModelFromEntityHooksLite != null) { model = CreateDistrictImageModelFromEntityHooksLite(entity, model, contextProfileName); }
                    goto case MappingMode.List;
                }
                case MappingMode.List: //////////////////////////////////////////////////////////////////////////////////////////////////////////////
                default:
                {
                    // IHaveATypeBase Properties
                    model.TypeID = entity.TypeID;
                    if (entity.Type != null)
                    {
                        model.TypeKey = entity.Type.CustomKey;
                        model.TypeName = entity.Type.Name;
                        model.TypeDisplayName = entity.Type.DisplayName;
                        model.TypeTranslationKey = entity.Type.TranslationKey;
                        model.TypeSortOrder = entity.Type.SortOrder;
                    }
                    // IHaveJsonAttributesBase Properties (Forced)
                    model.SerializableAttributes = entity.JsonAttributes.DeserializeAttributesDictionary();
                    // IImageBase Properties
                    model.MasterID = entity.MasterID;
                    // DistrictImage's Properties
                    model.Author = entity.Author;
                    model.Copyright = entity.Copyright;
                    model.DisplayName = entity.DisplayName;
                    model.IsPrimary = entity.IsPrimary;
                    model.Latitude = entity.Latitude;
                    model.Location = entity.Location;
                    model.Longitude = entity.Longitude;
                    model.MediaDate = entity.MediaDate;
                    model.OriginalBytes = entity.OriginalBytes;
                    model.OriginalFileFormat = entity.OriginalFileFormat;
                    model.OriginalFileName = entity.OriginalFileName;
                    model.OriginalHeight = entity.OriginalHeight;
                    model.OriginalIsStoredInDB = entity.OriginalIsStoredInDB;
                    model.OriginalWidth = entity.OriginalWidth;
                    model.SeoTitle = entity.SeoTitle;
                    model.SortOrder = entity.SortOrder;
                    model.ThumbnailBytes = entity.ThumbnailBytes;
                    model.ThumbnailFileFormat = entity.ThumbnailFileFormat;
                    model.ThumbnailFileName = entity.ThumbnailFileName;
                    model.ThumbnailHeight = entity.ThumbnailHeight;
                    model.ThumbnailIsStoredInDB = entity.ThumbnailIsStoredInDB;
                    model.ThumbnailWidth = entity.ThumbnailWidth;
                    // DistrictImage's Related Objects (Not Mapped unless Forced, or a flattening property)
                    // DistrictImage's Associated Objects (Not Mapped unless Forced)
                    // Additional Mappings
                    if (CreateDistrictImageModelFromEntityHooksList != null) { model = CreateDistrictImageModelFromEntityHooksList(entity, model, contextProfileName); }
                    break;
                }
            } ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            // Finished!
            return model;
        }
    }
}
