// <autogenerated>
// <copyright file="Mapping.Groups.GroupStatus.cs" company="clarity-ventures.com">
// Copyright (c) 2016-2023 clarity-ventures.com. All rights reserved.
// </copyright>
// <summary>Implements the Groups section of the Mapping class</summary>
// <remarks>This file was auto-generated by Mapping.tt, changes to this
// file will be overwritten automatically when the T4 template is run again</remarks>
// </autogenerated>
// ReSharper disable CyclomaticComplexity, FunctionComplexityOverflow, InvokeAsExtensionMethod, MergeCastWithTypeCheck
// ReSharper disable MissingLinebreak, RedundantDelegateInvoke, RedundantUsingDirective
#pragma warning disable CS0618 // Ignore Obsolete warnings
#nullable enable
namespace Clarity.Ecommerce.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Linq.Expressions;
    using DataModel;
    using Interfaces.DataModel;
    using Interfaces.Models;
    using LinqKit;
    using MoreLinq;
    using Utilities;

    public static partial class ModelMapperForGroupStatus
    {
        public sealed class AnonGroupStatus : GroupStatus
        {
        }

        public static readonly Func<GroupStatus?, string?, IStatusModel?> MapGroupStatusModelFromEntityFull = CreateGroupStatusModelFromEntityFull;

        public static readonly Func<GroupStatus?, string?, IStatusModel?> MapGroupStatusModelFromEntityLite = CreateGroupStatusModelFromEntityLite;

        public static readonly Func<GroupStatus?, string?, IStatusModel?> MapGroupStatusModelFromEntityList = CreateGroupStatusModelFromEntityList;

        public static Func<IGroupStatus, IStatusModel, string?, IStatusModel>? CreateGroupStatusModelFromEntityHooksFull { get; set; }

        public static Func<IGroupStatus, IStatusModel, string?, IStatusModel>? CreateGroupStatusModelFromEntityHooksLite { get; set; }

        public static Func<IGroupStatus, IStatusModel, string?, IStatusModel>? CreateGroupStatusModelFromEntityHooksList { get; set; }

        public static Expression<Func<GroupStatus, AnonGroupStatus>>? PreBuiltGroupStatusSQLSelectorFull { get; set; }

        public static Expression<Func<GroupStatus, AnonGroupStatus>>? PreBuiltGroupStatusSQLSelectorLite { get; set; }

        public static Expression<Func<GroupStatus, AnonGroupStatus>>? PreBuiltGroupStatusSQLSelectorList { get; set; }

        /// <summary>An <see cref="IStatusModel"/> extension method that creates a(n) <see cref="GroupStatus"/> entity.</summary>
        /// <param name="model">            The model to act on.</param>
        /// <param name="timestamp">        The timestamp Date/Time.</param>
        /// <param name="contextProfileName">Name of the context profile.</param>
        /// <returns>The new <see cref="GroupStatus"/> entity.</returns>
        public static IGroupStatus CreateGroupStatusEntity(
            this IStatusModel model,
            DateTime timestamp,
            string? contextProfileName)
        {
            // Create the object and Map the Inherited Properties
            return Contract.RequiresNotNull(model)
                .CreateEntityStatusableBase<IStatusModel, GroupStatus>(timestamp, contextProfileName)
                // Use the Update method to map non-inherited properties
                .UpdateGroupStatusFromModel(model, timestamp, null);
        }

        /// <summary>An <see cref="IStatusModel"/> extension method that updates a(n) <see cref="GroupStatus"/> entity.</summary>
        /// <param name="entity">         The entity to act on.</param>
        /// <param name="model">          The model to read from.</param>
        /// <param name="timestamp">      The timestamp Date/Time.</param>
        /// <param name="updateTimestamp">The update timestamp Date/Time.</param>
        /// <returns>The updated <see cref="GroupStatus"/> entity.</returns>
        public static IGroupStatus UpdateGroupStatusFromModel(
            this IGroupStatus entity,
            IStatusModel model,
            DateTime timestamp,
            DateTime? updateTimestamp)
        {
            // Map the Inherited Properties
            entity = Contract.RequiresNotNull(entity)
                .MapStatusableBaseModelPropertiesToEntity(Contract.RequiresNotNull(model));
            // Finally, update the timestamp
            entity.UpdatedDate = updateTimestamp == null || updateTimestamp == DateTime.MinValue ? null : updateTimestamp;
            // Return
            return entity;
        }

        public static void GenGroupStatusSQLSelectorFull()
        {
            PreBuiltGroupStatusSQLSelectorFull = x => x == null ? null! : new AnonGroupStatus
            {
                DisplayName = x.DisplayName,
                SortOrder = x.SortOrder,
                TranslationKey = x.TranslationKey,
                Name = x.Name,
                Description = x.Description,
                ID = x.ID,
                CustomKey = x.CustomKey,
                CreatedDate = x.CreatedDate,
                UpdatedDate = x.UpdatedDate,
                Active = x.Active,
                Hash = x.Hash,
                JsonAttributes = x.JsonAttributes,
            };
        }

        public static void GenGroupStatusSQLSelectorLite()
        {
            PreBuiltGroupStatusSQLSelectorLite = x => x == null ? null! : new AnonGroupStatus
            {
                DisplayName = x.DisplayName,
                SortOrder = x.SortOrder,
                TranslationKey = x.TranslationKey,
                Name = x.Name,
                Description = x.Description,
                ID = x.ID,
                CustomKey = x.CustomKey,
                CreatedDate = x.CreatedDate,
                UpdatedDate = x.UpdatedDate,
                Active = x.Active,
                Hash = x.Hash,
                JsonAttributes = x.JsonAttributes,
            };
        }

        public static void GenGroupStatusSQLSelectorList()
        {
            PreBuiltGroupStatusSQLSelectorList = x => x == null ? null! : new AnonGroupStatus
            {
                DisplayName = x.DisplayName,
                SortOrder = x.SortOrder,
                TranslationKey = x.TranslationKey,
                Name = x.Name,
                ID = x.ID,
                CustomKey = x.CustomKey,
                CreatedDate = x.CreatedDate,
                Active = x.Active,
                Hash = x.Hash,
                JsonAttributes = x.JsonAttributes,
            };
        }

        public static IEnumerable<IStatusModel> SelectFullGroupStatusAndMapToStatusModel(
            this IQueryable<GroupStatus> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltGroupStatusSQLSelectorFull == null);
            return dbSetWithFilters
                .AsExpandable()
                .Select(PreBuiltGroupStatusSQLSelectorFull!.Compile())
                .ToList()
                .Select(x => CreateGroupStatusModelFromEntityFull(x, contextProfileName))!;
        }

        public static IEnumerable<IStatusModel> SelectLiteGroupStatusAndMapToStatusModel(
            this IQueryable<GroupStatus> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltGroupStatusSQLSelectorLite == null);
            return dbSetWithFilters
                .AsExpandable()
                .Select(PreBuiltGroupStatusSQLSelectorLite!.Compile())
                .ToList()
                .Select(x => CreateGroupStatusModelFromEntityLite(x, contextProfileName))!;
        }

        public static IEnumerable<IStatusModel> SelectListGroupStatusAndMapToStatusModel(
            this IQueryable<GroupStatus> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltGroupStatusSQLSelectorList == null);
            return dbSetWithFilters
                .AsExpandable()
                .Select(PreBuiltGroupStatusSQLSelectorList!.Compile())
                .ToList()
                .Select(x => CreateGroupStatusModelFromEntityList(x, contextProfileName))!;
        }

        public static IStatusModel? SelectFirstFullGroupStatusAndMapToStatusModel(
            this IQueryable<GroupStatus> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltGroupStatusSQLSelectorFull == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltGroupStatusSQLSelectorFull!.Compile())
                .ToList()
                .Select(x => CreateGroupStatusModelFromEntityFull(x, contextProfileName))
                .FirstOrDefault();
        }

        public static IStatusModel? SelectFirstListGroupStatusAndMapToStatusModel(
            this IQueryable<GroupStatus> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltGroupStatusSQLSelectorList == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltGroupStatusSQLSelectorList!.Compile())
                .ToList()
                .Select(x => CreateGroupStatusModelFromEntityList(x, contextProfileName))
                .FirstOrDefault();
        }

        public static IStatusModel? SelectSingleFullGroupStatusAndMapToStatusModel(
            this IQueryable<GroupStatus> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltGroupStatusSQLSelectorFull == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltGroupStatusSQLSelectorFull!.Compile())
                .ToList()
                .Select(x => CreateGroupStatusModelFromEntityFull(x, contextProfileName))
                .SingleOrDefault();
        }

        public static IStatusModel? SelectSingleLiteGroupStatusAndMapToStatusModel(
            this IQueryable<GroupStatus> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltGroupStatusSQLSelectorLite == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltGroupStatusSQLSelectorLite!.Compile())
                .ToList()
                .Select(x => CreateGroupStatusModelFromEntityLite(x, contextProfileName))
                .SingleOrDefault();
        }

        public static IStatusModel? SelectSingleListGroupStatusAndMapToStatusModel(
            this IQueryable<GroupStatus> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltGroupStatusSQLSelectorList == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltGroupStatusSQLSelectorList!.Compile())
                .ToList()
                .Select(x => CreateGroupStatusModelFromEntityList(x, contextProfileName))
                .SingleOrDefault();
        }

        public static (IEnumerable<IStatusModel> results, int totalPages, int totalCount) SelectFullGroupStatusAndMapToStatusModel(
            this IQueryable<GroupStatus> dbSetWithFilters,
            Paging? paging,
            Sort[]? sorts,
            Grouping[]? groupings,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltGroupStatusSQLSelectorFull == null);
            return (dbSetWithFilters
                    .AsExpandable()
                    .ApplySorting(sorts, groupings, contextProfileName)
                    .FilterByPaging(paging, out var totalPages, out var totalCount)
                    .Select(PreBuiltGroupStatusSQLSelectorFull!.Compile())
                    .ToList()
                    .Select(x => CreateGroupStatusModelFromEntityFull(x, contextProfileName)),
                totalPages,
                totalCount)!;
        }

        public static (IEnumerable<IStatusModel> results, int totalPages, int totalCount) SelectLiteGroupStatusAndMapToStatusModel(
            this IQueryable<GroupStatus> dbSetWithFilters,
            Paging? paging,
            Sort[]? sorts,
            Grouping[]? groupings,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltGroupStatusSQLSelectorLite == null);
            return (dbSetWithFilters
                    .AsExpandable()
                    .ApplySorting(sorts, groupings, contextProfileName)
                    .FilterByPaging(paging, out var totalPages, out var totalCount)
                    .Select(PreBuiltGroupStatusSQLSelectorLite!.Compile())
                    .ToList()
                    .Select(x => CreateGroupStatusModelFromEntityLite(x, contextProfileName)),
                totalPages,
                totalCount)!;
        }

        public static (IEnumerable<IStatusModel> results, int totalPages, int totalCount) SelectListGroupStatusAndMapToStatusModel(
            this IQueryable<GroupStatus> dbSetWithFilters,
            Paging? paging,
            Sort[]? sorts,
            Grouping[]? groupings,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltGroupStatusSQLSelectorList == null);
            return (dbSetWithFilters
                    .AsExpandable()
                    .ApplySorting(sorts, groupings, contextProfileName)
                    .FilterByPaging(paging, out var totalPages, out var totalCount)
                    .Select(PreBuiltGroupStatusSQLSelectorList!.Compile())
                    .ToList()
                    .Select(x => CreateGroupStatusModelFromEntityList(x, contextProfileName)),
                totalPages,
                totalCount)!;
        }

        public static IStatusModel? CreateGroupStatusModelFromEntityFull(this IGroupStatus? entity, string? contextProfileName)
        {
            return CreateGroupStatusModelFromEntity(entity, MappingMode.Full, contextProfileName);
        }

        public static IStatusModel? CreateGroupStatusModelFromEntityLite(this IGroupStatus? entity, string? contextProfileName)
        {
            return CreateGroupStatusModelFromEntity(entity, MappingMode.Lite, contextProfileName);
        }

        public static IStatusModel? CreateGroupStatusModelFromEntityList(this IGroupStatus? entity, string? contextProfileName)
        {
            return CreateGroupStatusModelFromEntity(entity, MappingMode.List, contextProfileName);
        }

        public static IStatusModel? CreateGroupStatusModelFromEntity(
            this IGroupStatus? entity,
            MappingMode mode,
            string? contextProfileName)
        {
            if (entity == null) { return null; }
            // Map the Inherited Properties
            // ReSharper disable once InvokeAsExtensionMethod
            var model = BaseModelMapper.MapStatusableBaseEntityPropertiesToModel(
                RegistryLoaderWrapper.GetInstance<IStatusModel>(contextProfileName),
                Contract.RequiresNotNull(entity),
                mode,
                contextProfileName);
            // Map this level's Properties
            switch (mode)
            {
                case MappingMode.Full: //////////////////////////////////////////////////////////////////////////////////////////////////////////////
                {
                    // GroupStatus's Properties
                    // GroupStatus's Related Objects
                    // GroupStatus's Associated Objects
                    // Additional Mappings
                    if (CreateGroupStatusModelFromEntityHooksFull != null) { model = CreateGroupStatusModelFromEntityHooksFull(entity, model, contextProfileName); }
                    goto case MappingMode.Lite;
                }
                case MappingMode.Lite: //////////////////////////////////////////////////////////////////////////////////////////////////////////////
                {
                    // GroupStatus's Properties
                    // GroupStatus's Related Objects (Not Mapped unless Forced, or a flattening property)
                    // GroupStatus's Associated Objects (Not Mapped unless Forced)
                    // Additional Mappings
                    if (CreateGroupStatusModelFromEntityHooksLite != null) { model = CreateGroupStatusModelFromEntityHooksLite(entity, model, contextProfileName); }
                    goto case MappingMode.List;
                }
                case MappingMode.List: //////////////////////////////////////////////////////////////////////////////////////////////////////////////
                default:
                {
                    // IHaveJsonAttributesBase Properties (Forced)
                    model.SerializableAttributes = entity.JsonAttributes.DeserializeAttributesDictionary();
                    // GroupStatus's Properties
                    // GroupStatus's Related Objects (Not Mapped unless Forced, or a flattening property)
                    // GroupStatus's Associated Objects (Not Mapped unless Forced)
                    // Additional Mappings
                    if (CreateGroupStatusModelFromEntityHooksList != null) { model = CreateGroupStatusModelFromEntityHooksList(entity, model, contextProfileName); }
                    break;
                }
            } ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            // Finished!
            return model;
        }
    }
}
