// <autogenerated>
// <copyright file="Mapping.Payments.MembershipAdZoneAccessByLevel.cs" company="clarity-ventures.com">
// Copyright (c) 2016-2023 clarity-ventures.com. All rights reserved.
// </copyright>
// <summary>Implements the Payments section of the Mapping class</summary>
// <remarks>This file was auto-generated by Mapping.tt, changes to this
// file will be overwritten automatically when the T4 template is run again</remarks>
// </autogenerated>
// ReSharper disable CyclomaticComplexity, FunctionComplexityOverflow, InvokeAsExtensionMethod, MergeCastWithTypeCheck
// ReSharper disable MissingLinebreak, RedundantDelegateInvoke, RedundantUsingDirective
#pragma warning disable CS0618 // Ignore Obsolete warnings
#nullable enable
namespace Clarity.Ecommerce.Mapper
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Linq.Expressions;
    using DataModel;
    using Interfaces.DataModel;
    using Interfaces.Models;
    using LinqKit;
    using MoreLinq;
    using Utilities;

    public static partial class ModelMapperForMembershipAdZoneAccessByLevel
    {
        public sealed class AnonMembershipAdZoneAccessByLevel : MembershipAdZoneAccessByLevel
        {
            // public new MembershipAdZoneAccess? Master { get; set; }
        }

        public static readonly Func<MembershipAdZoneAccessByLevel?, string?, IMembershipAdZoneAccessByLevelModel?> MapMembershipAdZoneAccessByLevelModelFromEntityFull = CreateMembershipAdZoneAccessByLevelModelFromEntityFull;

        public static readonly Func<MembershipAdZoneAccessByLevel?, string?, IMembershipAdZoneAccessByLevelModel?> MapMembershipAdZoneAccessByLevelModelFromEntityLite = CreateMembershipAdZoneAccessByLevelModelFromEntityLite;

        public static readonly Func<MembershipAdZoneAccessByLevel?, string?, IMembershipAdZoneAccessByLevelModel?> MapMembershipAdZoneAccessByLevelModelFromEntityList = CreateMembershipAdZoneAccessByLevelModelFromEntityList;

        public static Func<IMembershipAdZoneAccessByLevel, IMembershipAdZoneAccessByLevelModel, string?, IMembershipAdZoneAccessByLevelModel>? CreateMembershipAdZoneAccessByLevelModelFromEntityHooksFull { get; set; }

        public static Func<IMembershipAdZoneAccessByLevel, IMembershipAdZoneAccessByLevelModel, string?, IMembershipAdZoneAccessByLevelModel>? CreateMembershipAdZoneAccessByLevelModelFromEntityHooksLite { get; set; }

        public static Func<IMembershipAdZoneAccessByLevel, IMembershipAdZoneAccessByLevelModel, string?, IMembershipAdZoneAccessByLevelModel>? CreateMembershipAdZoneAccessByLevelModelFromEntityHooksList { get; set; }

        public static Expression<Func<MembershipAdZoneAccessByLevel, AnonMembershipAdZoneAccessByLevel>>? PreBuiltMembershipAdZoneAccessByLevelSQLSelectorFull { get; set; }

        public static Expression<Func<MembershipAdZoneAccessByLevel, AnonMembershipAdZoneAccessByLevel>>? PreBuiltMembershipAdZoneAccessByLevelSQLSelectorLite { get; set; }

        public static Expression<Func<MembershipAdZoneAccessByLevel, AnonMembershipAdZoneAccessByLevel>>? PreBuiltMembershipAdZoneAccessByLevelSQLSelectorList { get; set; }

        /// <summary>An <see cref="IMembershipAdZoneAccessByLevelModel"/> extension method that creates a(n) <see cref="MembershipAdZoneAccessByLevel"/> entity.</summary>
        /// <param name="model">            The model to act on.</param>
        /// <param name="timestamp">        The timestamp Date/Time.</param>
        /// <param name="contextProfileName">Name of the context profile.</param>
        /// <returns>The new <see cref="MembershipAdZoneAccessByLevel"/> entity.</returns>
        public static IMembershipAdZoneAccessByLevel CreateMembershipAdZoneAccessByLevelEntity(
            this IMembershipAdZoneAccessByLevelModel model,
            DateTime timestamp,
            string? contextProfileName)
        {
            // Create the object and Map the Inherited Properties
            return Contract.RequiresNotNull(model)
                .CreateEntityFromModelBase<IMembershipAdZoneAccessByLevelModel, MembershipAdZoneAccessByLevel>(timestamp, contextProfileName)
                // Use the Update method to map non-inherited properties
                .UpdateMembershipAdZoneAccessByLevelFromModel(model, timestamp, null);
        }

        /// <summary>An <see cref="IMembershipAdZoneAccessByLevelModel"/> extension method that updates a(n) <see cref="MembershipAdZoneAccessByLevel"/> entity.</summary>
        /// <param name="entity">         The entity to act on.</param>
        /// <param name="model">          The model to read from.</param>
        /// <param name="timestamp">      The timestamp Date/Time.</param>
        /// <param name="updateTimestamp">The update timestamp Date/Time.</param>
        /// <returns>The updated <see cref="MembershipAdZoneAccessByLevel"/> entity.</returns>
        public static IMembershipAdZoneAccessByLevel UpdateMembershipAdZoneAccessByLevelFromModel(
            this IMembershipAdZoneAccessByLevel entity,
            IMembershipAdZoneAccessByLevelModel model,
            DateTime timestamp,
            DateTime? updateTimestamp)
        {
            // Map the Inherited Properties
            entity = Contract.RequiresNotNull(entity)
                .MapIAmARelationshipTableBaseModelPropertiesToEntity(Contract.RequiresNotNull(model));
            // MembershipAdZoneAccessByLevel Properties
            entity.SubscriberCountThreshold = model.SubscriberCountThreshold;
            entity.UniqueAdLimit = model.UniqueAdLimit;
            // MembershipAdZoneAccessByLevel's Related Objects
            // Finally, update the timestamp
            entity.UpdatedDate = updateTimestamp == null || updateTimestamp == DateTime.MinValue ? null : updateTimestamp;
            // Return
            return entity;
        }

        public static void GenMembershipAdZoneAccessByLevelSQLSelectorFull()
        {
            PreBuiltMembershipAdZoneAccessByLevelSQLSelectorFull = x => x == null ? null! : new AnonMembershipAdZoneAccessByLevel
            {
                MasterID = x.MasterID,
                SlaveID = x.SlaveID,
                Slave = ModelMapperForMembershipLevel.PreBuiltMembershipLevelSQLSelectorList.Expand().Compile().Invoke(x.Slave!),
                SubscriberCountThreshold = x.SubscriberCountThreshold,
                UniqueAdLimit = x.UniqueAdLimit,
                ID = x.ID,
                CustomKey = x.CustomKey,
                CreatedDate = x.CreatedDate,
                UpdatedDate = x.UpdatedDate,
                Active = x.Active,
                Hash = x.Hash,
                JsonAttributes = x.JsonAttributes,
            };
        }

        public static void GenMembershipAdZoneAccessByLevelSQLSelectorLite()
        {
            PreBuiltMembershipAdZoneAccessByLevelSQLSelectorLite = x => x == null ? null! : new AnonMembershipAdZoneAccessByLevel
            {
                MasterID = x.MasterID,
                SlaveID = x.SlaveID,
                Slave = ModelMapperForMembershipLevel.PreBuiltMembershipLevelSQLSelectorList.Expand().Compile().Invoke(x.Slave!),
                SubscriberCountThreshold = x.SubscriberCountThreshold,
                UniqueAdLimit = x.UniqueAdLimit,
                ID = x.ID,
                CustomKey = x.CustomKey,
                CreatedDate = x.CreatedDate,
                UpdatedDate = x.UpdatedDate,
                Active = x.Active,
                Hash = x.Hash,
                JsonAttributes = x.JsonAttributes,
            };
        }

        public static void GenMembershipAdZoneAccessByLevelSQLSelectorList()
        {
            PreBuiltMembershipAdZoneAccessByLevelSQLSelectorList = x => x == null ? null! : new AnonMembershipAdZoneAccessByLevel
            {
                MasterID = x.MasterID,
                SlaveID = x.SlaveID,
                Slave = ModelMapperForMembershipLevel.PreBuiltMembershipLevelSQLSelectorList.Expand().Compile().Invoke(x.Slave!), // For Flattening Properties (List)
                SubscriberCountThreshold = x.SubscriberCountThreshold,
                UniqueAdLimit = x.UniqueAdLimit,
                ID = x.ID,
                CustomKey = x.CustomKey,
                CreatedDate = x.CreatedDate,
                Active = x.Active,
                Hash = x.Hash,
                JsonAttributes = x.JsonAttributes,
                Master = ModelMapperForMembershipAdZoneAccess.PreBuiltMembershipAdZoneAccessSQLSelectorList.Expand().Compile().Invoke(x.Master!), // For Flattening Properties
            };
        }

        public static IEnumerable<IMembershipAdZoneAccessByLevelModel> SelectFullMembershipAdZoneAccessByLevelAndMapToMembershipAdZoneAccessByLevelModel(
            this IQueryable<MembershipAdZoneAccessByLevel> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorFull == null);
            return dbSetWithFilters
                .AsExpandable()
                .Select(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorFull!.Compile())
                .ToList()
                .Select(x => CreateMembershipAdZoneAccessByLevelModelFromEntityFull(x, contextProfileName))!;
        }

        public static IEnumerable<IMembershipAdZoneAccessByLevelModel> SelectLiteMembershipAdZoneAccessByLevelAndMapToMembershipAdZoneAccessByLevelModel(
            this IQueryable<MembershipAdZoneAccessByLevel> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorLite == null);
            return dbSetWithFilters
                .AsExpandable()
                .Select(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorLite!.Compile())
                .ToList()
                .Select(x => CreateMembershipAdZoneAccessByLevelModelFromEntityLite(x, contextProfileName))!;
        }

        public static IEnumerable<IMembershipAdZoneAccessByLevelModel> SelectListMembershipAdZoneAccessByLevelAndMapToMembershipAdZoneAccessByLevelModel(
            this IQueryable<MembershipAdZoneAccessByLevel> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorList == null);
            return dbSetWithFilters
                .AsExpandable()
                .Select(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorList!.Compile())
                .ToList()
                .Select(x => CreateMembershipAdZoneAccessByLevelModelFromEntityList(x, contextProfileName))!;
        }

        public static IMembershipAdZoneAccessByLevelModel? SelectFirstFullMembershipAdZoneAccessByLevelAndMapToMembershipAdZoneAccessByLevelModel(
            this IQueryable<MembershipAdZoneAccessByLevel> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorFull == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorFull!.Compile())
                .ToList()
                .Select(x => CreateMembershipAdZoneAccessByLevelModelFromEntityFull(x, contextProfileName))
                .FirstOrDefault();
        }

        public static IMembershipAdZoneAccessByLevelModel? SelectFirstListMembershipAdZoneAccessByLevelAndMapToMembershipAdZoneAccessByLevelModel(
            this IQueryable<MembershipAdZoneAccessByLevel> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorList == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorList!.Compile())
                .ToList()
                .Select(x => CreateMembershipAdZoneAccessByLevelModelFromEntityList(x, contextProfileName))
                .FirstOrDefault();
        }

        public static IMembershipAdZoneAccessByLevelModel? SelectSingleFullMembershipAdZoneAccessByLevelAndMapToMembershipAdZoneAccessByLevelModel(
            this IQueryable<MembershipAdZoneAccessByLevel> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorFull == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorFull!.Compile())
                .ToList()
                .Select(x => CreateMembershipAdZoneAccessByLevelModelFromEntityFull(x, contextProfileName))
                .SingleOrDefault();
        }

        public static IMembershipAdZoneAccessByLevelModel? SelectSingleLiteMembershipAdZoneAccessByLevelAndMapToMembershipAdZoneAccessByLevelModel(
            this IQueryable<MembershipAdZoneAccessByLevel> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorLite == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorLite!.Compile())
                .ToList()
                .Select(x => CreateMembershipAdZoneAccessByLevelModelFromEntityLite(x, contextProfileName))
                .SingleOrDefault();
        }

        public static IMembershipAdZoneAccessByLevelModel? SelectSingleListMembershipAdZoneAccessByLevelAndMapToMembershipAdZoneAccessByLevelModel(
            this IQueryable<MembershipAdZoneAccessByLevel> dbSetWithFilters,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorList == null);
            return dbSetWithFilters
                .AsExpandable()
                .OrderBy(x => x.ID)
                .Take(1)
                .Select(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorList!.Compile())
                .ToList()
                .Select(x => CreateMembershipAdZoneAccessByLevelModelFromEntityList(x, contextProfileName))
                .SingleOrDefault();
        }

        public static (IEnumerable<IMembershipAdZoneAccessByLevelModel> results, int totalPages, int totalCount) SelectFullMembershipAdZoneAccessByLevelAndMapToMembershipAdZoneAccessByLevelModel(
            this IQueryable<MembershipAdZoneAccessByLevel> dbSetWithFilters,
            Paging? paging,
            Sort[]? sorts,
            Grouping[]? groupings,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorFull == null);
            return (dbSetWithFilters
                    .AsExpandable()
                    .ApplySorting(sorts, groupings, contextProfileName)
                    .FilterByPaging(paging, out var totalPages, out var totalCount)
                    .Select(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorFull!.Compile())
                    .ToList()
                    .Select(x => CreateMembershipAdZoneAccessByLevelModelFromEntityFull(x, contextProfileName)),
                totalPages,
                totalCount)!;
        }

        public static (IEnumerable<IMembershipAdZoneAccessByLevelModel> results, int totalPages, int totalCount) SelectLiteMembershipAdZoneAccessByLevelAndMapToMembershipAdZoneAccessByLevelModel(
            this IQueryable<MembershipAdZoneAccessByLevel> dbSetWithFilters,
            Paging? paging,
            Sort[]? sorts,
            Grouping[]? groupings,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorLite == null);
            return (dbSetWithFilters
                    .AsExpandable()
                    .ApplySorting(sorts, groupings, contextProfileName)
                    .FilterByPaging(paging, out var totalPages, out var totalCount)
                    .Select(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorLite!.Compile())
                    .ToList()
                    .Select(x => CreateMembershipAdZoneAccessByLevelModelFromEntityLite(x, contextProfileName)),
                totalPages,
                totalCount)!;
        }

        public static (IEnumerable<IMembershipAdZoneAccessByLevelModel> results, int totalPages, int totalCount) SelectListMembershipAdZoneAccessByLevelAndMapToMembershipAdZoneAccessByLevelModel(
            this IQueryable<MembershipAdZoneAccessByLevel> dbSetWithFilters,
            Paging? paging,
            Sort[]? sorts,
            Grouping[]? groupings,
            string? contextProfileName)
        {
            BaseModelMapper.Initialize(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorList == null);
            return (dbSetWithFilters
                    .AsExpandable()
                    .ApplySorting(sorts, groupings, contextProfileName)
                    .FilterByPaging(paging, out var totalPages, out var totalCount)
                    .Select(PreBuiltMembershipAdZoneAccessByLevelSQLSelectorList!.Compile())
                    .ToList()
                    .Select(x => CreateMembershipAdZoneAccessByLevelModelFromEntityList(x, contextProfileName)),
                totalPages,
                totalCount)!;
        }

        public static IMembershipAdZoneAccessByLevelModel? CreateMembershipAdZoneAccessByLevelModelFromEntityFull(this IMembershipAdZoneAccessByLevel? entity, string? contextProfileName)
        {
            return CreateMembershipAdZoneAccessByLevelModelFromEntity(entity, MappingMode.Full, contextProfileName);
        }

        public static IMembershipAdZoneAccessByLevelModel? CreateMembershipAdZoneAccessByLevelModelFromEntityLite(this IMembershipAdZoneAccessByLevel? entity, string? contextProfileName)
        {
            return CreateMembershipAdZoneAccessByLevelModelFromEntity(entity, MappingMode.Lite, contextProfileName);
        }

        public static IMembershipAdZoneAccessByLevelModel? CreateMembershipAdZoneAccessByLevelModelFromEntityList(this IMembershipAdZoneAccessByLevel? entity, string? contextProfileName)
        {
            return CreateMembershipAdZoneAccessByLevelModelFromEntity(entity, MappingMode.List, contextProfileName);
        }

        public static IMembershipAdZoneAccessByLevelModel? CreateMembershipAdZoneAccessByLevelModelFromEntity(
            this IMembershipAdZoneAccessByLevel? entity,
            MappingMode mode,
            string? contextProfileName)
        {
            if (entity == null) { return null; }
            // Map the Inherited Properties
            // ReSharper disable once InvokeAsExtensionMethod
            var model = BaseModelMapper.MapBaseEntityPropertiesToModel(
                RegistryLoaderWrapper.GetInstance<IMembershipAdZoneAccessByLevelModel>(contextProfileName),
                Contract.RequiresNotNull(entity),
                mode,
                contextProfileName);
            // Map this level's Properties
            switch (mode)
            {
                case MappingMode.Full: //////////////////////////////////////////////////////////////////////////////////////////////////////////////
                {
                    // MembershipAdZoneAccessByLevel's Properties
                    // MembershipAdZoneAccessByLevel's Related Objects
                    // MembershipAdZoneAccessByLevel's Associated Objects
                    // Additional Mappings
                    if (CreateMembershipAdZoneAccessByLevelModelFromEntityHooksFull != null) { model = CreateMembershipAdZoneAccessByLevelModelFromEntityHooksFull(entity, model, contextProfileName); }
                    goto case MappingMode.Lite;
                }
                case MappingMode.Lite: //////////////////////////////////////////////////////////////////////////////////////////////////////////////
                {
                    // MembershipAdZoneAccessByLevel's Properties
                    // MembershipAdZoneAccessByLevel's Related Objects (Not Mapped unless Forced, or a flattening property)
                    // MembershipAdZoneAccessByLevel's Associated Objects (Not Mapped unless Forced)
                    // Additional Mappings
                    if (CreateMembershipAdZoneAccessByLevelModelFromEntityHooksLite != null) { model = CreateMembershipAdZoneAccessByLevelModelFromEntityHooksLite(entity, model, contextProfileName); }
                    goto case MappingMode.List;
                }
                case MappingMode.List: //////////////////////////////////////////////////////////////////////////////////////////////////////////////
                default:
                {
                    // IHaveJsonAttributesBase Properties (Forced)
                    model.SerializableAttributes = entity.JsonAttributes.DeserializeAttributesDictionary();
                    // MembershipAdZoneAccessByLevel's Properties
                    model.SubscriberCountThreshold = entity.SubscriberCountThreshold;
                    model.UniqueAdLimit = entity.UniqueAdLimit;
                    // MembershipAdZoneAccessByLevel's Related Objects (Not Mapped unless Forced, or a flattening property)
                    model.MasterID = entity.MasterID;
                    model.MasterKey = entity.Master?.CustomKey;
                    model.SlaveID = entity.SlaveID;
                    model.Slave = ModelMapperForMembershipLevel.CreateMembershipLevelModelFromEntityLite(entity.Slave, contextProfileName);
                    model.SlaveKey = entity.Slave?.CustomKey;
                    model.SlaveName = entity.Slave?.Name;
                    // MembershipAdZoneAccessByLevel's Associated Objects (Not Mapped unless Forced)
                    // Additional Mappings
                    if (CreateMembershipAdZoneAccessByLevelModelFromEntityHooksList != null) { model = CreateMembershipAdZoneAccessByLevelModelFromEntityHooksList(entity, model, contextProfileName); }
                    break;
                }
            } ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            // Finished!
            return model;
        }
    }
}
